### ISSUE TITLE
Support installation of Grafana

### ISSUE THREAD

**Issue by durera** [ibm-mas/ansible-devops#10]
We can use this as a starting point, but it may be quite out of date: 

https://github.com/ibm-watson-iot/iot-docs/tree/master/monitoring#3-grafana-setup

This should be added to the `ocp_setup_mas_deps` role

**Comment by alequint** [comment]
I am working on this one, can you please assign it to me @durera? (no permission to self-assign it)

**Comment by alequint** [comment]
Pull Request (ready to review/merge): https://github.com/ibm-mas/ansible-devops/pull/31

**Comment by durera** [comment]
Any news on this one?
