### ISSUE TITLE
Use Sensible defaults for PVC size based on historical data

### ISSUE THREAD

**Issue by maulik-modi22** [ibm-mas/ansible-devops#1002]
![image (21)](https://github.com/ibm-mas/ansible-devops/assets/108735641/3ea93c5c-5e85-450d-969a-dff7184fd241)

Prometheus PVC uses 300 GB initially. Although using cluster for 1 month, size does not go beyond 20 GB.
cc: @lokesh-sreedhara

**Comment by andrercm** [comment]
@cuddlyporcupine what would you think it's a good default sizing for the storage classes for it?
We set `PROMETHEUS_STORAGE_SIZE` and `PROMETHEUS_USERWORKLOAD_STORAGE_SIZE` that are `300Gi` by default.

**Comment by whitfiea** [comment]
Fixed in PR https://github.com/ibm-mas/ansible-devops/pull/1030
