### ISSUE TITLE
Unify roles that setup manage doclinks

### ISSUE THREAD

**Issue by alequint** [ibm-mas/ansible-devops#1010]
Please refer to slack thread here: https://ibm-watson-iot.slack.com/archives/C040TETRV2T/p1694466952230229

We have two roles that do the same thing but in different ways:
- `suite_manage_attachments_config`: https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/suite_manage_attachments_config/README.md -> updates doclink propeties in database, and support file storage, ibm cos and aws s3

- `suite_manage_doclinks_config`: https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/suite_manage_doclinks_config/README.md -> updates doclink propeties in ManageWorkspace CR (under bundles), and support ibm cos and aws s3 only

This is really confuse for a customer to know what to use.

My suggestion is merge then in a single role and use that role in pipeline config flow with given options to choose (file/cos/s3) - always better to avoid database updates directly, we need to pass thru CR instead like in doclinks_config role

**Comment by alequint** [comment]
@andrercm @whitfiea  pulling this to CI Squad to start in Milestone 3

**Comment by alequint** [comment]
Discussion happening in CI Squad issue here: https://jsw.ibm.com/browse/MASCORE-1205

**Comment by JonahLuckett** [comment]
@alequint was this issue solved by https://github.com/ibm-mas/ansible-devops/pull/1319 ?
