### ISSUE TITLE
Getting catalog tag from ibm-operator-catalog is breaking one-click install in dev instances

### ISSUE THREAD

**Issue by fyeh** [ibm-mas/ansible-devops#1012]
The change made in this PR https://github.com/ibm-mas/ansible-devops/pull/1006 means that the mongodb role is now trying to get the `catalog_tag` from the displayName of the `ibm-operator-cataalog` CatalogSource. The `catalog_tag` is then used to lookup a case bundle from https://github.com/ibm-mas/ansible-devops/tree/master/ibm/mas_devops/common_vars/casebundles.

The [playbook for ibm_catalogs](https://ibm-mas.github.io/ansible-devops/roles/ibm_catalogs/#ibm_catalogs) says the default value for `MAS_CATALOG_VERSION` is `v8-amd64` but in our dev clusters we have been using `v8-master-amd64`. When we run the one-click install playbook now, it fails while trying to look up the  `/../../common_vars/casebundles/v8-master-amd64.yml` case bundle. Regardless of whether the catalog version is set to `v8-amd64` or `v8-master-amd64`, the case bundle lookup in roles/mongodb/tasks/providers/community/install.yml is failing.

If I try updating the catalog to something recent (EG `v8-230829-amd64'`) the catalog can't find an image in Artifactory with a matching tag. The latest one there is `v8-230616-amd64`.

I'm working around this now by changing the displayName in the `ibm-operator-catalog` CatalogSource to match the case bundle I want to use but this doesn't seem like the final solution.

**Comment by andrercm** [comment]
@whitfiea @racree can one of you help with this one?

**Comment by whitfiea** [comment]
fixed in https://github.com/ibm-mas/ansible-devops/pull/1011
