### ISSUE TITLE
oneclick installation fails on ibm.mas_devops.suite_verify

### ISSUE THREAD

**Issue by thinktank9** [ibm-mas/ansible-devops#1016]
The oneclick installation fails on the ibm.mas_devops.suite_verify step. It seems that the mas operator is waiting for condition `BasIntegrationReady` and BAS Integration is waiting for `milestonesapi` to be ready. The `milestonesapi` has readiness probe failing because of `[CRITICAL] WORKER TIMEOUT` just after `Initialising catalog_items cache` step. I checked, the `catalogmgr` seems to be up and running so not sure why it is timing out.

See the logs attached.

ansible log - 

Thursday 14 September 2023  20:33:50 +0000 (0:51:17.392)       1:49:28.072 ****
===============================================================================
ibm.mas_devops.suite_verify : Wait for Suite Components to be ready (60s delay) ------------------------------------------------------------------------------------------------------------------------------- 3077.39s
ibm.mas_devops.uds : Wait for the AnalyticsProxy to be ready -------------------------------------------------------------------------------------------------------------------------------------------------- 1339.07s
ibm.mas_devops.sls : Wait for LicenseService to be ready (60s delay) ------------------------------------------------------------------------------------------------------------------------------------------- 739.92s
ibm.mas_devops.uds : Wait for GenerateKey to be ready (60s delay) ---------------------------------------------------------------------------------------------------------------------------------------------- 308.82s
ibm.mas_devops.mongodb : community : install : Wait for stateful set to be ready ------------------------------------------------------------------------------------------------------------------------------- 186.18s

[ansible-error.log](https://github.com/ibm-mas/ansible-devops/files/12670737/ansible-error.log)
[dev-licensing-mediator-65f8894785-w5gvz-licensing-mediator.log](https://github.com/ibm-mas/ansible-devops/files/12670738/dev-licensing-mediator-65f8894785-w5gvz-licensing-mediator.log)
[dev-milestonesapi-78ccb686fd-wbhrl-milestonesapi.log](https://github.com/ibm-mas/ansible-devops/files/12670739/dev-milestonesapi-78ccb686fd-wbhrl-milestonesapi.log)
[ibm-mas-operator-8645949cb9-n5x85-manager.log](https://github.com/ibm-mas/ansible-devops/files/12670742/ibm-mas-operator-8645949cb9-n5x85-manager.log)

**Comment by andrercm** [comment]
Hi @thinktank9 can you please provide the outputs for the following commands?

```
oc get pods -n ibm-common-services
oc get pods -n mas-$INSTANCE_ID-core
oc get nodes
```

Want to understand if the pods and nodes are running in expected state. From your logs, it seems like one or more pods might be encountering errors to be deployed in one of the cluster's worker nodes.

**Comment by andrercm** [comment]
@thinktank9 any updates on this case?

**Comment by andrercm** [comment]
no response for the past month, please reopen the case if still need help
