### ISSUE TITLE
Verify default router secret is created in ROKS

### ISSUE THREAD

**Issue by durera** [ibm-mas/ansible-devops#102]
BAS install fails due to ROKS provisioning errors, we don't know why sometimes ROKS messes up this aspect of the cluster config, but it causes problems for one of our dependencies; BAS.  

We can put something in ocp verify that checks for one of the two secrets that we are expecting on ROKS ... if things are going to fail because sometimes this secret is missing we should make them fail as early as possible seeing as we don't know how to resolve the issue.

Reference: https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/bas_install/tasks/bascfg.yml#L63-L103 ... We need to have similar logic in ocp verify that checks that either of these secrets exists.  If it doesn't, then fail the verify because the cluster is not ready for MAS.

**Comment by andrercm** [comment]
Took a stab at it on: https://github.com/ibm-mas/ansible-devops/pull/109
