### ISSUE TITLE
Unable to lookup file

### ISSUE THREAD

**Issue by hariskhancs12** [ibm-mas/ansible-devops#1024]
fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'file'. Error was a <class 'ansible.errors.Ansibl
eError'>, original message: could not locate file in lookup: /opt/app-root/src/license.dat. could not locate file in lookup: /opt/app-root/src/license.da
t"}

**Comment by andrercm** [comment]
@hariskhancs12 can you elaborate more on the issue you're having?

- which playbook or role you're running? seems to be `sls` ?
- what variables are you exporting ?
- can you provide the automation output logs ?

**Comment by hariskhancs12** [comment]
I am running it using podman and stuck on this error  could not locate file in lookup: /opt/app-root/src/license.dat
and if i check the file license.dat it is available in the location 

I am running below command 
podman run -ti -v /home/muhammad.haris/license.dat:/opt/app-root/src/license.dat quay.io/ibmmas/ansible-devops:latest bash
then passing the parameter's 

Its expecting export SLS_LICENSE_FILE=/opt/app-root/src/license.dat
then i am running ansible-playbook ibm.mas_devops.oneclick_core

**Comment by andrercm** [comment]
Try to map the container's volume for the local folder where the file is located instead of mapping the full file path as in:

```
podman run -ti -v /home/muhammad.haris:/opt/app-root/src quay.io/ibmmas/ansible-devops:latest bash
```

once you're in the container, run this to ensure the file is in the expected path

```
cat /opt/app-root/src/license.dat
```

if it is, then you're ready to set the variable:
```
export SLS_LICENSE_FILE=/opt/app-root/src/license.dat
```

**Comment by hariskhancs12** [comment]
Its giving below

**Comment by hariskhancs12** [comment]
it seems some permission issue
[muhammad.haris@dev-bastion-02 ~]$ podman run -ti -v /home/muhammad.haris/license.dat:/opt/app-root/src/license.dat quay.io/ibmmas/ansible-devops:latest 
bash
(app-root) cat /opt/app-root/src/license.dat
cat: /opt/app-root/src/license.dat: Permission denied

**Comment by hariskhancs12** [comment]
Hi 

@andrercm  Thank for your help
The issue is when i am copying the file in container its making it as directory as below

[root@dev-bastion-02 ~]# podman run -ti -v license.dat:/opt/app-root/src/license.dat quay.io/ibmmas/ansible-devops:latest bash
(app-root) ls
ansible.cfg       env.sh      license.dat  requirements.txt  run-playbook.sh  save-junit-to-mongo.py
clear-mustgather-workspace.sh  ibm-mas_devops.tar.gz  README.md    requirements.yml  run-role.sh
(app-root) cat license.dat/
cat: license.dat/: Is a directory

**Comment by andrercm** [comment]
hey @hariskhancs12 were you able to solve the problem then?

**Comment by hariskhancs12** [comment]
Hi @andrercm yes its fixed thanks 
But i got another one 

![Screenshot 2023-09-28 162903](https://github.com/ibm-mas/ansible-devops/assets/146227228/49babcc4-5dcd-413a-9ff4-e7fe5895251a)

**Comment by andrercm** [comment]
@hariskhancs12 can you list all the variables you are exporting to run `oneclick_core.yml` playbook? 
from the error above it seems you are missing to export `SLS_MONGODB_CFG_FILE` which should point to the path for the mongo configuration yaml file that was generated by the `mongodb` role (this is one of the tasks that is ran by the oneclick_core playbook)

**Comment by andrercm** [comment]
ok i see you opened a separate one to deal with this new issue: https://github.com/ibm-mas/ansible-devops/issues/1027
