### ISSUE TITLE
Getting error in ansible-playbook ibm.mas_devops.oneclick_core 

### ISSUE THREAD

**Issue by hariskhancs12** [ibm-mas/ansible-devops#1027]
I am installing MAS using ansible palybook. I provided the parameters and every thing went fine.
Now its stuck on ibm.mas devops.sls : Wait for License Service to be running

TRYING: [localhost]: Wait for LicenseService to be running (60s delay) (7 retries left).
FAILED - RETRYING: [localhost]: Wait for LicenseService to be running (60s delay) (6 retries left).
FAILED - RETRYING: [localhost]: Wait for LicenseService to be running (60s delay) (5 retries left).
FAILED - RETRYING: [localhost]: Wait for LicenseService to be running (60s delay) (4 retries left).
FAILED - RETRYING: [localhost]: Wait for LicenseService to be running (60s delay) (3 retries left).
FAILED - RETRYING: [localhost]: Wait for LicenseService to be running (60s delay) (2 retries left).
FAILED - RETRYING: [localhost]: Wait for LicenseService to be running (60s delay) (1 retries left).
fatal: [localhost]: FAILED! => {"api_found": true, "attempts": 30, "changed": false, "resources": [{"apiVersion": "sls.ibm.com/v1", "kind": "LicenseServi
ce", "metadata": {"creationTimestamp": "2023-09-28T12:20:01Z", "generation": 1, "managedFields": [{"apiVersion": "sls.ibm.com/v1", "fieldsType": "FieldsV
1", "fieldsV1": {"f:spec": {".": {}, "f:domain": {}, "f:license": {".": {}, "f:accept": {}}, "f:mongo": {".": {}, "f:configDb": {}, "f:nodes": {}, "f:ret
ryWrites": {}, "f:secretName": {}}, "f:settings": {".": {}, "f:auth": {".": {}, "f:enforce": {}}, "f:compliance": {".": {}, "f:enforce": {}}, "f:registra
tion": {".": {}, "f:open": {}}, "f:registry": {}}}}, "manager": "OpenAPI-Generator", "operation": "Update", "time": "2023-09-28T12:20:01Z"}, {"apiVersion
": "sls.ibm.com/v1", "fieldsType": "FieldsV1", "fieldsV1": {"f:status": {"f:licenseId": {}, "f:registrationKey": {}, "f:versions": {".": {}, "f:reconcile
d": {}}}}, "manager": "OpenAPI-Generator", "operation": "Update", "subresource": "status", "time": "2023-09-28T12:20:12Z"}, {"apiVersion": "sls.ibm.com/v
1", "fieldsType": "FieldsV1", "fieldsV1": {"f:status": {".": {}, "f:conditions": {}}}, "manager": "ansible-operator", "operation": "Update", "subresource
": "status", "time": "2023-09-29T07:45:26Z"}], "name": "sls", "namespace": "ibm-sls", "resourceVersion": "22155795", "uid": "ac33bdc6-0840-4d21-ac0c-5713
82640595"}, "spec": {"domain": "apps.qhscactm.dev.openshift.sevenit.cloud", "license": {"accept": true}, "mongo": {"configDb": "admin", "nodes": [{"host"
: "mas-mongo-ce-0.mas-mongo-ce-svc.mongo.svc.cluster.local", "port": 27017}, {"host": "mas-mongo-ce-1.mas-mongo-ce-svc.mongo.svc.cluster.local", "port": 
27017}, {"host": "mas-mongo-ce-2.mas-mongo-ce-svc.mongo.svc.cluster.local", "port": 27017}], "retryWrites": true, "secretName": "ibm-sls-mongo-credential
s"}, "settings": {"auth": {"enforce": true}, "compliance": {"enforce": true}, "registration": {"open": true}, "registry": "cp.icr.io/cp"}}, "status": {"c
onditions": [{"lastTransitionTime": "2023-09-28T12:20:12Z", "message": "mongo.certificates is missing or incorrectly configured in CR. Check that certifi
cates are present and valid. ", "reason": "NotReady", "status": "False", "type": "Ready"}, {"lastTransitionTime": "2023-09-28T12:20:12Z", "message": "mon
go.certificates is missing or incorrectly configured in CR ", "reason": "MissingMongoCertificates", "status": "False", "type": "SystemDatabaseReady"}, {"
lastTransitionTime": "2023-09-28T12:20:12Z", "message": "", "reason": "", "status": "False", "type": "Successful"}, {"lastTransitionTime": "2023-09-29T07
:45:19Z", "message": "Running reconciliation", "reason": "Running", "status": "False", "type": "Running"}, {"ansibleResult": {"changed": 0, "completion":
 "2023-09-29T07:45:26.245126", "failures": 1, "ok": 30, "skipped": 12}, "lastTransitionTime": "2023-09-29T07:45:26Z", "message": "NotReady: mongo.certifi
cates is missing or incorrectly configured in CR. Check that certificates are present and valid.", "reason": "Failed", "status": "True", "type": "Failure
"}], "licenseId": "4201c0a8400a", "registrationKey": "d850ce16-5570-52d5-9e98-ba30f0510781", "versions": {"reconciled": "3.8.0"}}}]}

**Comment by ely-barros** [comment]
I'm hitting the same error.

It fails to pull the _sls-api_ image: 

`Failed to pull image "cp.icr.io/cp/ibm-sls/api-licensing@sha256:382be651a9a56572a222677bbe7013952d4bcfa3d68926265fb0929f12845b01": rpc error: code = Unknown desc = reading manifest sha256:382be651a9a56572a222677bbe7013952d4bcfa3d68926265fb0929f12845b01 in cp.icr.io/cp/ibm-sls/api-licensing: manifest unknown: manifest unknown`

**Comment by hariskhancs12** [comment]
@ely-barros  Did you able to find the solution i am also getting the same now?

**Comment by ely-barros** [comment]
@hariskhancs12, it eventually worked without doing anything.

Hopefully, it worked for you as well.

**Comment by whitfiea** [comment]
@hariskhancs12 Did you provide the mongo certificates? 
```
mongo.certificates is missing or incorrectly configured in CR. Check that certificates are present and valid.
```

**Comment by andrercm** [comment]
@hariskhancs12 as @whitfiea mentioned, it seems it is missing the mongo certificates, you can provide them by exporting `SLS_MONGODB_CFG_FILE` variable which should point to the path for the mongo configuration yaml file that is generated by the mongodb role (this is one of the tasks that is ran by the oneclick_core playbook). If you can list all the variables you are exporting to run the `oneclick_core.yml` playbook that will help while assisting you.

**Comment by andrercm** [comment]
@hariskhancs12 any updates on this case?

**Comment by hariskhancs12** [comment]
Hi 
I installed openshift 4.12 because as per IBM 4.13 is not supported.
after that i used mascli to install MAS. The installation failed with the below error.

MongoDb integration disabled because DEVOPS_MONGO_URI is not set

Reagrds

**Comment by andrercm** [comment]
Is this still an issue? 
if so, can you provide the log outputs from your `mas install` run?

**Comment by hariskhancs12** [comment]
Yes it was fixed
