### ISSUE TITLE
Automate Cloud Object Storage provisioning

### ISSUE THREAD

**Issue by alequint** [ibm-mas/ansible-devops#103]
- [ ] Automated Provisioning
- [ ] Create ObjectStorageCFG in config folder at the end of the process

**Comment by durera** [comment]
I've seperated the cos work from the massive pr here https://github.com/ibm-mas/ansible-devops/pull/110 into this branch: https://github.com/ibm-mas/ansible-devops/tree/cosonly

Ideally we want smaller PRs, do one thing at a time, get it merged and release, then add the next thing.  It's much easier to test, review and generally ensure a high quality ifPRs are for one thing if it's something big.
