### ISSUE TITLE
Addition of Image Groups and Separately Entitled Add-on in Manage 8.7.0 CASE Breaking Generate Mirror-Manifests 

### ISSUE THREAD

**Issue by chriscochran** [ibm-mas/ansible-devops#1033]
The Manage 8.7.0 CASE now includes image groups and a separately entitled add-on which result this playbook error:

`"error: unable to retrieve source image cp.icr.io/cp/manage/extension-icd manifest sha256:884cd4063a0369975743c9746831f4ab06deef915cc9a3e8790bb24e359d5fe0: denied: You are not authorized to access the specified resource. See https://cloud.ibm.com/docs/Registry?topic=Registry-troubleshoot-access-denied", "error: an error occurred during planning"`.

Changes in the `oc ibm-pak generate mirror-manifests` command (link below) to include `--filter ibmmasManage` for customers not entitled for Maximo IT and `--filter ibmmasManage ibmmasMaximoIT` for customers entitled to both.
https://github.com/ibm-mas/ansible-devops/blob/a47a0c4c307e30d70ca33899f74ae7eadd49a801/ibm/mas_devops/roles/mirror_case_prepare/tasks/prepare-released.yml#L59

Related Issue: https://github.com/ibm-mas/cli/issues/539

**Comment by durera** [comment]
This was fixed, but the issue left open.  Closing issue now.
