### ISSUE TITLE
Inconsistency in when: clauses mix of String and boolean comparison

### ISSUE THREAD

**Issue by pohlkamp** [ibm-mas/ansible-devops#1041]
Issue at client install when deploying client's certificates using the ansible scripts. 

The skipping suggests that when: `mas_manual_cert_mgmt == True` is false.
`mas_manual_cert_mgmt: "{{ lookup('env', 'MAS_MANUAL_CERT_MGMT') | default(False, true) }}"`

When running it with 
`export MAS_MANUAL_CERT_MGMT=true` it fails, only with 'True' (captal T) it works well. This is not boolean, it's String comparison. 

https://github.com/ibm-mas/ansible-devops/blob/5b70f23552bf591f52c67d18bc5c72dcaba4c2fc/ibm/mas_devops/roles/suite_certs/tasks/run.yml#L58

In other scripts it is the other way around, as in https://github.com/ibm-mas/ansible-devops/blob/5b70f23552bf591f52c67d18bc5c72dcaba4c2fc/ibm/mas_devops/playbooks/oneclick_add_manage.yml#L100 stating `when: install_cp4d_platform == true`

Please correct capital writings in the scripts to avoid interruptions during installs and bring it in line to the standards.

**Comment by andrercm** [comment]
Should be fixed with this PR: https://github.com/ibm-mas/ansible-devops/pull/1114
