### ISSUE TITLE
oneclick add manage does not set the default mas_config_scope 

### ISSUE THREAD

**Issue by witekwww** [ibm-mas/ansible-devops#1056]
Changes made in #1021 are not reflected in docs.
mas_config_scope var is now not set with default value (previously there was a default 'system').
If this variable is not set by user it will cause db2 role to fail on generating jdbcCfg
![image](https://github.com/ibm-mas/ansible-devops/assets/118370754/2eb91a5e-d381-4611-8ffb-2d8df512f081)

Please revert this change or update docs that this variable is now required and not optional.

**Comment by davidstacy** [comment]
+1 have noticed this. with mas_manage installs.

**Comment by andrercm** [comment]
This has been fixed with https://github.com/ibm-mas/ansible-devops/pull/1090
