### ISSUE TITLE
Script doesn't add all UDS certificates to basCfg

### ISSUE THREAD

**Issue by pohlkamp** [ibm-mas/ansible-devops#1058]
When configuring UDS only the first two certificates are added to the basCfg. We have a host, intermediate and a root CA to be added to the config. But based on the ansible script here it is adding only part 1 and 2, adding further certs is only an if clause, not a loop.
-> https://github.com/ibm-mas/ansible-devops/blob/16554ead1d2dcc21b1b490fc23e9dfa4a4e46b4c/ibm/mas_devops/roles/uds/templates/bascfg.yml.j2#L47

Therefore the ansible script adds first two parts, but the client's CA (third part) is not added, instead it adds the Letsencrypt cert given in the template. Therefore the chain is broken. 

Manually adding the root CA as third part in the MAS UI fixed it. 

Btw please also correct the template that the alias doesn't contain dashes (-)  - it fails to manage (remove) it in the MAS UI with an error message as the UI doesn't allow dashes. 
-> https://github.com/ibm-mas/ansible-devops/blob/16554ead1d2dcc21b1b490fc23e9dfa4a4e46b4c/ibm/mas_devops/roles/uds/templates/bascfg.yml.j2#L52

<img width="1141" alt="Bildschirmfoto 2023-10-18 um 11 33 47" src="https://github.com/ibm-mas/ansible-devops/assets/5946095/68c48bf3-83a6-4b5a-9b36-0be5de5491c6">

**Comment by andrercm** [comment]
@pohlkamp I have worked on a fix for this issue within the PR: https://github.com/ibm-mas/ansible-devops/pull/1097
