### ISSUE TITLE
the gencfg_jdbc role does not support pem file with multiple certificates

### ISSUE THREAD

**Issue by cuddlyporcupine** [ibm-mas/ansible-devops#1059]
the [jdbccfg template](https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/gencfg_jdbc/templates/jdbccfg.yml.j2#L39) file will only create 1 entry in the certificates array and will stuff all the certificates in the provided pem file into this array entry.  

the jdbccfg template should loop over the contents in the pem file and create an array entry for each certificate found in the pem file

**Comment by maulik-modi22** [comment]
To replicate the issue, use ` https://truststore.pki.rds.amazonaws.com/ca-central-1/ca-central-1-bundle.pem ` as an example

**Comment by maulik-modi22** [comment]
@andrercm , appreciate your inputs on this

**Comment by andrercm** [comment]
Alright, we'll assign this to be fixed in the upcoming ansible-devops releases

**Comment by maulik-modi22** [comment]
thank you @andrercm for prioritising it, eager to get it merged and released
