### ISSUE TITLE
Getting error in ansible-playbook ibm.mas_devops.oneclick_core

### ISSUE THREAD

**Issue by helmml** [ibm-mas/ansible-devops#1064]
Fresh install of MAS 8.11.  Script is failing during the Wait for Suite Components to be ready (60s delay).

Seeing two errors in Openshift.

maslab-accapppoints-28295580-btb4m
MountVolume.SetUp failed for volume "sls-secrets" : secret "maslab-sls-cfg" not found

maslab-catalogmgr-78764dc6f-qx5qt
Unable to attach or mount volumes: unmounted volumes=[sls-cfg], unattached volumes=[mongo-config mongo-credentials sls-cfg kube-api-access-cf4nx catalog-settings catalog-items cert-internal-volume]: timed out waiting for the condition

Lastly error after it failed out.
fatal: [localhost]: FAILED! => {"api_found": true, "attempts": 50, "changed": false, "resources": [{"apiVersion": "core.mas.ibm.com/v1", "kind": "Suite", "metadata": {"creationTimestamp": "2023-10-19T16:15:36Z", "finalizers": ["core.mas.ibm.com/finalizer"], "generation": 1, "labels": {"mas.ibm.com/instanceId": "maslab"}, "managedFields": [{"apiVersion": "core.mas.ibm.com/v1", "fieldsType": "FieldsV1", "fieldsV1": {"f:metadata": {"f:labels": {".": {}, "f:mas.ibm.com/instanceId": {}}}, "f:spec": {".": {}, "f:certManagerNamespace": {}, "f:domain": {}, "f:license": {".": {}, "f:accept": {}}, "f:settings": {".": {}, "f:dataDictionary": {".": {}, "f:catalog": {}}, "f:icr": {".": {}, "f:cp": {}, "f:cpopen": {}}, "f:manualCertMgmt": {}}}}, "manager": "OpenAPI-Generator", "operation": "Update", "time": "2023-10-19T16:15:36Z"}, {"apiVersion": "core.mas.ibm.com/v1", "fieldsType": "FieldsV1", "fieldsV1": {"f:metadata": {"f:finalizers": {".": {}, "v:\"core.mas.ibm.com/finalizer\"": {}}}}, "manager": "ansible-operator", "operation": "Update", "time": "2023-10-19T16:15:55Z"}, {"apiVersion": "core.mas.ibm.com/v1", "fieldsType": "FieldsV1", "fieldsV1": {"f:status": {}}, "manager": "ansible-operator", "operation": "Update", "subresource": "status", "time": "2023-10-19T17:05:33Z"}, {"apiVersion": "core.mas.ibm.com/v1", "fieldsType": "FieldsV1", "fieldsV1": {"f:status": {"f:apis": {".": {}, "f:internal": {".": {}, "f:url": {}}}, "f:cert-manager": {".": {}, "f:external": {".": {}, "f:duration": {}, "f:name": {}, "f:renewBefore": {}}, "f:internal": {".": {}, "f:duration": {}, "f:name": {}, "f:renewBefore": {}}}, "f:conditions": {}, "f:domain": {}, "f:keys": {".": {}, "f:jwt": {}, "f:ltpa": {}}, "f:podTemplates": {}, "f:settings": {".": {}, "f:cors": {".": {}, "f:allowedOrigins": {}}, "f:customUserDataModel": {".": {}, "f:emailTypes": {}, "f:phoneTypes": {}}, "f:dataDictionary": {".": {}, "f:catalog": {}, "f:channel": {}, "f:strategy": {}}, "f:icr": {".": {}, "f:cp": {}, "f:cpopen": {}}, "f:images": {".": {}, "f:pullPolicy": {}, "f:registry": {}}, "f:locale": {".": {}, "f:country": {}, "f:language": {}}, "f:manualCertMgmt": {}, "f:secrets": {".": {}, "f:certificates": {".": {}, "f:external": {}}, "f:images": {".": {}, "f:pullSecretName": {}}}, "f:sso": {".": {}, "f:accessTokenTimeout": {}, "f:defaultIDP": {}, "f:idleTimeout": {}, "f:idpSessionTimeout": {}, "f:refreshTokenTimeout": {}, "f:seamlessLogin": {}}, "f:trustDefaultCAs": {}}, "f:versions": {".": {}, "f:controller": {}, "f:generation": {}, "f:reconciled": {}, "f:supported": {}}}}, "manager": "OpenAPI-Generator", "operation": "Update", "subresource": "status", "time": "2023-10-19T17:06:33Z"}], "name": "maslab", "namespace": "mas-maslab-core", "resourceVersion": "991385", "uid": "7b06a31d-5d8e-4b67-bc39-b89ed83ab483"}, "spec": {"certManagerNamespace": "ibm-common-services", "domain": "maslab.apps.mas1.williams.com", "license": {"accept": true}, "settings": {"dataDictionary": {"catalog": "ibm-operator-catalog"}, "icr": {"cp": "cp.icr.io/cp", "cpopen": "icr.io/cpopen"}, "manualCertMgmt": false}}, "status": {"apis": {"internal": {"url": "https://internalapi.mas-maslab-core.svc"}}, "cert-manager": {"external": {"duration": "8760h0m0s", "name": "mas-maslab-core-public-issuer", "renewBefore": "720h0m0s"}, "internal": {"duration": "175200h0m0s", "name": "mas-maslab-core-internal-issuer", "renewBefore": "2160h0m0s"}}, "conditions": [{"lastTransitionTime": "2023-10-19T16:16:07Z", "message": "Controller updated primary entity manager to supported version (8.11.1)", "reason": "VersionUpdateCompleted", "status": "True", "type": "ControllerHealth"}, {"lastTransitionTime": "2023-10-19T17:06:33Z", "message": "Required condition(s) not ready: ['SystemDatabaseReady', 'BasIntegrationReady', 'SlsIntegrationReady']", "reason": "IncompleteConfiguration", "status": "False", "type": "Ready"}, {"lastTransitionTime": "2023-10-19T16:20:05Z", "message": "Running reconciliation", "reason": "ApplyingConfiguration", "status": "False", "type": "SystemDatabaseReady"}, {"lastTransitionTime": "2023-10-19T16:21:53Z", "message": "CoreIDP truststore ready", "reason": "Ready", "status": "True", "type": "CoreIDPReady"}, {"lastTransitionTime": "2023-10-19T16:27:13Z", "message": "Required app(s) not ready: ['maslab-milestonesapi']", "reason": "ApplyingConfiguration", "status": "False", "type": "BASIntegrationReady"}, {"lastTransitionTime": "2023-10-19T16:49:34Z", "message": "SLS client registration was unsuccessful: Unable to register SLS client for MAS: An unhandled error was returned from SLS: Unable to register SLS client maslab-f4753ee9: An unhandled error was returned from SLS: HTTPSConnectionPool(host='sls.ibm-sls.tuldxmaxocp01.williams.com', port=443): Max retries exceeded with url: /api/registrations (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f12f933b1c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))", "reason": "InvalidConfiguration", "status": "False", "type": "SLSIntegrationReady"}, {"lastTransitionTime": "2023-10-19T16:21:26Z", "message": "", "reason": "", "status": "False", "type": "Failure"}, {"lastTransitionTime": "2023-10-19T17:05:27Z", "message": "Last reconciliation succeeded", "reason": "Successful", "status": "False", "type": "Successful"}, {"lastTransitionTime": "2023-10-19T16:21:26Z", "message": "Running reconciliation", "reason": "Running", "status": "True", "type": "Running"}], "domain": "maslab.apps.mas1.williams.com", "keys": {"jwt": "maslab-keys-jwt", "ltpa": "maslab-keys-ltpa"}, "podTemplates": [], "settings": {"cors": {"allowedOrigins": []}, "customUserDataModel": {"emailTypes": [{"id": "work", "value": "Work"}, {"id": "home", "value": "Home"}], "phoneTypes": [{"id": "work", "value": "Work"}, {"id": "mobile", "value": "Mobile"}]}, "dataDictionary": {"catalog": "ibm-operator-catalog", "channel": "1.1.x", "strategy": "Automatic"}, "icr": {"cp": "cp.icr.io/cp", "cpopen": "icr.io/cpopen"}, "images": {"pullPolicy": "IfNotPresent", "registry": "cp.icr.io/cp"}, "locale": {"country": "GB", "language": "en"}, "manualCertMgmt": false, "secrets": {"certificates": {"external": ["maslab-cert-public"]}, "images": {"pullSecretName": "ibm-entitlement"}}, "sso": {"accessTokenTimeout": "30m", "defaultIDP": "local", "idleTimeout": "1800", "idpSessionTimeout": "12h", "refreshTokenTimeout": "12h", "seamlessLogin": false}, "trustDefaultCAs": true}, "versions": {"controller": "8.11.1", "generation": "1", "reconciled": "8.11.1", "supported": ["8.11.1"]}}}]}

**Comment by andrercm** [comment]
Please verify and provide the status for all the following MAS dependencies:

```
export MAS_INSTANCE_ID=replace-your-mas-instance-id

oc get Suite $MAS_INSTANCE_ID -n mas-$MAS_INSTANCE_ID-core -o yaml # output MAS instance overall status
oc get MongoCfg $MAS_INSTANCE_ID-mongo-system -n mas-$MAS_INSTANCE_ID-core -o yaml # output Mongo status
oc get BasCfg $MAS_INSTANCE_ID-bas-system -n mas-$MAS_INSTANCE_ID-core -o yaml # output UDS status
oc get SlsCfg $MAS_INSTANCE_ID-sls-system -n mas-$MAS_INSTANCE_ID-core -o yaml # output SLS status
```

**Comment by helmml** [comment]
Got it figured out with an assist from IBM.  Need to comment out the SLS_DOMAIN as it is no longer needed.
