### ISSUE TITLE
MAS installation failed using mascli error on cp4d

### ISSUE THREAD

**Issue by hariskhancs12** [ibm-mas/ansible-devops#1065]
![image](https://github.com/ibm-mas/ansible-devops/assets/146227228/4cb13033-d8a6-4653-83d2-7c1b69cf3790)

**Comment by davidstacy** [comment]
can you check and see if if db2 etcd pod is crashlooping?  if it is then delete it and restart the pipeline.  I think this is a known problem.

**Comment by hariskhancs12** [comment]
Hi 
Thanks it worked

**Comment by hariskhancs12** [comment]
@davidstacy  I need to know, how can i copy all configuration from 7.6 to MAS8

**Comment by GuilhermeFAC** [comment]
HI 

I have this problem, but my instalation is with external DB oracle

**Comment by GuilhermeFAC** [comment]
This issue has been resolved?
