### ISSUE TITLE
BAS issues

### ISSUE THREAD

**Issue by aroute** [ibm-mas/ansible-devops#107]
1. BAS playbook requires 2 explicit storageclass variable declaration. Please consider documenting.
2. BAS playbook deploys FullDeployment. Please consider using AnalyticsProxy instead. There is a lack of clarity on why FullDeployment is needed when Analyticsproxy also works. As is, BAS has large footprint.

**Comment by durera** [comment]
Discussing this internally.  I'm all in favour of reducing footprint if at all possible.
