### ISSUE TITLE
Error running ansible-playbook ibm.mas_devops.oneclick_add_manage.yml

### ISSUE THREAD

**Issue by helmml** [ibm-mas/ansible-devops#1072]
TASK [ibm.mas_devops.gencfg_jdbc : Prepare vars file from template.] *****************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not find or access 'vars/jdbccfg/.yml.j2'\nSearched in:\n\t/home/ec2-user/.ansible/collections/ansible_collections/ibm/mas_devops/roles/gencfg_jdbc/templates/vars/jdbccfg/.yml.j2\n\t/home/ec2-user/.ansible/collections/ansible_collections/ibm/mas_devops/roles/gencfg_jdbc/vars/jdbccfg/.yml.j2\n\t/home/ec2-user/.ansible/collections/ansible_collections/ibm/mas_devops/roles/gencfg_jdbc/tasks/templates/vars/jdbccfg/.yml.j2\n\t/home/ec2-user/.ansible/collections/ansible_collections/ibm/mas_devops/roles/gencfg_jdbc/tasks/vars/jdbccfg/.yml.j2\n\t/home/ec2-user/.ansible/collections/ansible_collections/ibm/mas_devops/playbooks/templates/vars/jdbccfg/.yml.j2\n\t/home/ec2-user/.ansible/collections/ansible_collections/ibm/mas_devops/playbooks/vars/jdbccfg/.yml.j2 on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}

**Comment by SalaryTheft** [comment]
See #1056

**Comment by helmml** [comment]
Added the below to my env.sh file still getting the same error.

export MAS_CONFIG_SCOPE="wsapp"
export MAS_APPWS_BINDINGS_JDBC="workspace-application"

**Comment by helmml** [comment]
Changed it to just and it worked.
export MAS_CONFIG_SCOPE="system"

**Comment by andrercm** [comment]
This has been fixed with https://github.com/ibm-mas/ansible-devops/pull/1090
