### ISSUE TITLE
Add custom route(domain) for CP4D installation.

### ISSUE THREAD

**Issue by SalaryTheft** [ibm-mas/ansible-devops#1088]
It would be nice to have a variable for a custom route for CP4D installations.
CP4D custom route can be defined in the ZenService type object's spec: zenCustomRoute: route_host.

**Comment by andrercm** [comment]
@SalaryTheft thanks for the feedback... i tend to think that what you want might be accomplished with something available in `suite_dns` role: https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/suite_dns/defaults/main.yaml#L95

When you configure MAS with a well-known certificate authority (i.e Let's Encrypt) for public certificates, you can also do same to configure custom public certs/routes for your CloudPak for Data instance.

You need to export the vars to point to your CPD instance while running `suite_dns` role, ensuring the following condition is met:
https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/suite_dns/tasks/run.yml#L43-L44

meaning, you need to export:

- `DNS_PROVIDER` (pointing to the DNS provider that you want to use)
- `CPD_INSTANCE_NAMESPACE` (pointing to the CPD namespace/project)
- `CPD_CUSTOM_DOMAIN` (your CPD custom domain - by default it will use same custom domain used for MAS instance)

**Comment by SalaryTheft** [comment]
Thanks, I didn't know that existed.
