### ISSUE TITLE
Bug Report: Exception in Ansible Task Execution during Object Storage Configuration Copy

### ISSUE THREAD

**Issue by miles-canton** [ibm-mas/ansible-devops#1106]
Encountered an exception during the installation process
```
TASK [ibm.mas_devops.cos : ocs/objectstorage : Copy objectstorageCfg to filesytem] ***
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleUndefinedVariable: list object has no element 1. list object has no element 1
fatal: [localhost]: FAILED! => changed=false 
  msg: 'AnsibleUndefinedVariable: list object has no element 1. list object has no element 1'
```

Workaround Applied:
```
File: ibm/mas_devops/roles/cos/tasks/providers/ocs/provision.yml
Line: 103
Modification: Change cluster_ingress_tls_crt to cluster_ingress_tls_crt_full
```

Reason:
`File changed :   ibm/mas_devops/common_tasks/get_ingress_cert.yml    
`

**Comment by andrercm** [comment]
@miles-canton i have a potential fix for your problem still under testing... if you want to have a test run on that, you can use the collection from this branch: https://github.com/ibm-mas/ansible-devops/tree/jdbc-cert-fix

**Comment by andrercm** [comment]
Will be fixed when this PR is merged: https://github.com/ibm-mas/ansible-devops/pull/1097
