### ISSUE TITLE
Incorrect UDS version in MAS Catalog v8-231031-amd64 when mirroring the image

### ISSUE THREAD

**Issue by liupinyi** [ibm-mas/ansible-devops#1108]
In the catalogsource, we can see the UDS version is 2.0.12

![image](https://github.com/ibm-mas/cli/assets/21214618/70817839-2815-4663-8294-fd56c02415f7)

But the mirrored UDS images is for 2.0.11:

```
[root@probates1 cpopen]# cd ibm-user-data-services-operator-bundle/
[root@probates1 ibm-user-data-services-operator-bundle]# ll
total 0
drwxr-xr-x 3 root root 20 Nov 17 20:28 _layers
drwxr-xr-x 4 root root 35 Nov 17 20:29 _manifests
drwxr-xr-x 2 root root  6 Nov 17 20:28 _uploads
[root@probates1 ibm-user-data-services-operator-bundle]# cd _manifests/
[root@probates1 _manifests]# ll
total 0
drwxr-xr-x 3 root root 20 Nov 17 20:29 revisions
drwxr-xr-x 3 root root 20 Nov 17 20:29 tags
[root@probates1 _manifests]# cd tags/
[root@probates1 tags]# ll
total 0
drwxr-xr-x 4 root root 34 Nov 17 20:29 2.0.11
[root@probates1 tags]#
```

![bdd295d50b10353b9cc1544df02b12e](https://github.com/ibm-mas/cli/assets/21214618/7279bb9b-3a9e-4d5a-9e52-c417a7f8f0ff)

![767c1ee4fcc1b8ebfc1e5083012ce44](https://github.com/ibm-mas/cli/assets/21214618/4951f603-637a-417c-8420-66961716de72)

Please help double check if we should mirror UDS 2.0.12 version images. Thank you.

**Comment by andrercm** [comment]
@liupinyi I just installed `v8-231031-amd64` and I see UDS operator 2.0.12 indeed.



Can you please check whats the actual reason why the install plan can not successfully be unpacked. 
You can provide the following log outputs:

**1. This command will tell if any pods are not running as expected:**

```
oc get pods -n openshift-marketplace
```

Output sample:

```
NAME                                                              READY   STATUS      RESTARTS   AGE
150dabc07e4254dc7abb573836a16326f9959e72cfdb621487e3ea5b5bqzrlg   0/1     Completed   0          2d1h
8d47eaa93482e1b5faef3c963e9627e023c280266347ac6dce69ab3966zdq7p   0/1     Completed   0          29h
certified-operators-xmvwf                                         1/1     Running     0          14h
community-operators-jdc2h                                         1/1     Running     0          30m
db4ec48f46e5d73952ec137ad6ebf02aef10d079036e2aaa8fdb7f0135w9l5j   0/1     Completed   0          29h
ibm-operator-catalog-zslf4                                        1/1     Running     0          11m
marketplace-operator-7f8c874464-xhc5v                             1/1     Running     0          2d2h
redhat-marketplace-tffhw                                          1/1     Running     0          2d1h
redhat-operators-bsmdr                                            1/1     Running     0          42h
```

**2. This will verify which job failed to complete**
```
oc get jobs -n openshift-marketplace
```

Output will be similar to:

```
NAME                                                              COMPLETIONS   DURATION   AGE
150dabc07e4254dc7abb573836a16326f9959e72cfdb621487e3ea5b5b15980   1/1           26s        2d1h
8d47eaa93482e1b5faef3c963e9627e023c280266347ac6dce69ab3966fd84d   1/1           18s        29h
db4ec48f46e5d73952ec137ad6ebf02aef10d079036e2aaa8fdb7f013548273   1/1           14s        29h
```

Then you will be able to extract the logs from the failing one, as example:

```
oc logs 150dabc07e4254dc7abb573836a16326f9959e72cfdb621487e3ea5b5b15980 -n openshift-marketplace
```

Please provide the logs as above so we can continue debugging your problem.

Also if no evident error found, you can simply delete the uncompleted job, delete the UDS subscription and try to reinstall its subscription to see if the job that is supposed to unpack the install plan's resources can go through a second time.

**Comment by durera** [comment]
Fixed in https://github.com/ibm-mas/ansible-devops/pull/1109
