### ISSUE TITLE
Include CP4D dashboard url in CIS and Cert-Manager process

### ISSUE THREAD

**Issue by alequint** [ibm-mas/ansible-devops#112]
Predict and H&P Utilities customers must access Cloud Pak for Data dashbord to look at their Analytics projects and design notebooks, but cp4d url is not secure. This is important either for MAS MS or MAS Demo environments and whatever one used by customers.

- Have a new cname in CIS for cp4d
- Have an automation that creates a Certificate resource (cert-manager) using the same cluster issuer mas uses
- Have an automation which get the cert and key created by the cert-manager and apply in cp4d dashboard route

By the end of this process cp4d would be accessible also by using a suite.maximo.com domain

**Comment by whitfiea** [comment]
The process to get cp4d to use a real certificate for the dashboard is here https://www.ibm.com/docs/en/cloud-paks/cp-data/4.0?topic=client-using-custom-tls-certificate-connect-platform but this won't get you a new route.

Trying to work out where to place the logic (in cp4d role or suite_dns role (cis)). As this is only really needed when using a custom cluster issuer my feeling was to add it to the suite_dns role and just check if cp4d has been installed or not. Any preference on where the logic is @alequint ?

**Comment by whitfiea** [comment]
Decided to have the extra DNS entry in suite_dns and then logic in suite_install to create the cert and create the route. The route needs to be in the same namespace as the service that it is connecting too. The suite_install will only create the cert/route if custom_domain or custom_issuer is set and if a new flag to configure the route is true.

End result is a new route called cp4d.<masdomain> that is secure:

![image](https://user-images.githubusercontent.com/6817894/162790920-5a372204-b554-45b2-a1bb-f0cca9f46699.png)
