### ISSUE TITLE
DRO role changes the cluster default StorageClass

### ISSUE THREAD

**Issue by witekwww** [ibm-mas/ansible-devops#1132]
The playbook ibm/mas_devops/roles/dro/tasks/install-dro/determine-storage-classes.yml annotates the DRO storage class as default SC. If there was a different SC already annotated as default it will result in two SCs being annotated as default and 'critical error' from OpenShift.

**Comment by andrercm** [comment]
hello @yuvraj-vansure i see this might have something to due with the change done in this PR: https://github.com/ibm-mas/ansible-devops/pull/1081/files

Can you please help assess the reported issue?

**Comment by durera** [comment]
This has already been addressed in my initial feedback regarding DRO adoption.
