### ISSUE TITLE
Create ansible playbook for NFS provisioner and storage class 

### ISSUE THREAD

**Issue by QiJunWang-DS** [ibm-mas/ansible-devops#1164]
We need to create ansible playbooks for NFS provisioner and storage class. NFS storage dynamic provisioner is very popular in lots of client's MAS deployments, but it typically will take some time to make it completed with manual steps and sometimes it's easy to make some mistake with manual configurations, thus we may need to automate the provisioner and storage class creation process.

**Comment by durera** [comment]
We've discussed this internally on and off for a while now.  Unfortunately we are not going to be able to provide a general-purpose role for setting up NFS and configuring storage classes to access it.  We did add the ability to set up NFS specifically inside a FYRE OpenShift Cluster, but that is not generally re-usable: https://github.com/ibm-mas/ansible-devops/tree/master/ibm/mas_devops/roles/ocp_provision/tasks/providers/fyre/nfs

We would welcome a PR that was able to deliver a general purpose NFS role, but it's just not something the team are going to be able to deliver I'm afraid.
