### ISSUE TITLE
Grafana operator fails to install in Airgap mode

### ISSUE THREAD

**Issue by saurabhrajguru** [ibm-mas/ansible-devops#1196]
Grafana operator fails to install in the airgap mode.

The issue in airgap seems to isolated to Grafana, setting up 'CLUSTER_MONITORING_INCLUDE_GRAFANA=False' helps to skip so installation does not fail.

Observed issues with pulling up images, perhaps the operator should pick images via hash in airgap mode.
Certain images does not seem to be mirrored.

![image](https://github.com/ibm-mas/ansible-devops/assets/7845334/d12c166f-ec84-4738-b652-2ec0a9b9efc4)

**Comment by durera** [comment]
This is a known bug in Grafana v4 Operator, the only thing we could do ourselves is provide an option to disable the install of Grafana.  The maintainers of the operator package need to fix the issue (and they ended support of Grafana v4 at the end of last year without fixing this unfortunately).

Grafana v5 operator support will launch with the MAS February 2024 catalog update, and based on our testing Grafana v5 operator does not have the same problems that the v4 one does.
