### ISSUE TITLE
CP4D role installing IBM Cert Manager even when RH Cert Manager is already installed

### ISSUE THREAD

**Issue by rene-oromtz** [ibm-mas/ansible-devops#1207]
Summary
----
While attempting to run CP4D role to install CloudPak for Data 4.6.4, and during the "Wait for ibm-zen-operator to be ready" section, the role is installing IBM Cert Manager which is no longer the default cert-manager starting from Jan 2024 catalog update as it was replaced by RH Cert Manager. It is not advised to have two separate instances of cert-managers in the same cluster

Environment
----
MAS Core v8.11.6
Maximo Manage 8.7.4
RH Cert Manager 1.12.1
VPC in IBM Cloud
Container image used: quay.io/ibmmas/cli:latest

Steps to reproduce
----
1. Cluster is using online catalog, which replaced IBM Cert Manager to RH Cert Manager as the default operator. Both cert-manager projects already exist in the cluster.
```
$ oc get project|egrep "cert-manager|NAME"
NAME                                               DISPLAY NAME                  STATUS
cert-manager                                                                     Active
cert-manager-operator                                                            Active
```

2. Validating subscriptions and csv from ibm-common-services, there is no current sub or csv referencing to IBM cert Manager
```
$ oc get sub,csv -n ibm-common-services
NAME                                                                         PACKAGE                           SOURCE                 CHANNEL
subscription.operators.coreos.com/crunchy-postgres-operator                  crunchy-postgres-operator         certified-operators    v5
subscription.operators.coreos.com/ibm-common-service-operator                ibm-common-service-operator       ibm-operator-catalog   v3.23
subscription.operators.coreos.com/ibm-events-operator                        ibm-events-operator               ibm-operator-catalog   v3
subscription.operators.coreos.com/ibm-namespace-scope-operator               ibm-namespace-scope-operator      ibm-operator-catalog   v3.23
subscription.operators.coreos.com/ibm-user-data-services-operator            ibm-user-data-services-operator   ibm-operator-catalog   alpha
subscription.operators.coreos.com/operand-deployment-lifecycle-manager-app   ibm-odlm                          ibm-operator-catalog   v3.23

NAME                                                                                       DISPLAY                                VERSION   REPLACES                                       PHASE
clusterserviceversion.operators.coreos.com/ibm-common-service-operator.v3.23.11            IBM Cloud Pak foundational services    3.23.11   ibm-common-service-operator.v3.23.10           Succeeded
clusterserviceversion.operators.coreos.com/ibm-events-operator.v4.9.0                      IBM Events Operator                    4.9.0                                                    Succeeded
clusterserviceversion.operators.coreos.com/ibm-namespace-scope-operator.v1.17.10           IBM NamespaceScope Operator            1.17.10   ibm-namespace-scope-operator.v1.17.9           Succeeded
clusterserviceversion.operators.coreos.com/openshift-pipelines-operator-rh.v1.13.1         Red Hat OpenShift Pipelines            1.13.1    openshift-pipelines-operator-rh.v1.13.0        Succeeded
clusterserviceversion.operators.coreos.com/operand-deployment-lifecycle-manager.v1.21.10   Operand Deployment Lifecycle Manager   1.21.10   operand-deployment-lifecycle-manager.v1.21.9   Succeeded
clusterserviceversion.operators.coreos.com/postgresoperator.v5.5.0                         Crunchy Postgres for Kubernetes        5.5.0     postgresoperator.v5.4.4                        Succeeded
clusterserviceversion.operators.coreos.com/user-data-services-operator.v2.0.12             IBM User Data Services                 2.0.12    user-data-services-operator.v2.0.11            Succeeded
```

3. From the mascli container, export variables needed for cp4d role:
```
export CPD_PRODUCT_VERSION=4.6.4
export IBM_ENTITLEMENT_KEY=eyxxxxxxxxxxxxxxxxx
export CPD_PRIMARY_STORAGE_CLASS=ocs-storagecluster-cephfs
export CPD_METADATA_STORAGE_CLASS=ocs-storagecluster-ceph-rbd
```

4. Run CP4D role:
`ROLE_NAME=cp4d ansible-playbook ibm.mas_devops.run_role`

5. During the wait for zen operator to be ready, IBM Cert Manager is getting installed. In ibm-cpd there are two OperandRequest related to imm-cert-manager, one owned by ibmcpd and the other one by lite-cr

`$ oc get operandrequest -n ibm-cpd cert-manager -o yaml`
<details>
<summary>cert-manager YAML</summary>
<br>
<pre>
apiVersion: operator.ibm.com/v1alpha1
kind: OperandRequest
metadata:
  annotations:
    operator.ibm.com/operandregistry-is-not-found: "false"
  creationTimestamp: "2024-02-14T20:48:04Z"
  finalizers:
  - finalizer.request.ibm.com
  generation: 1
  labels:
    ibm-common-services.common-service/config: "true"
    ibm-common-services.common-service/registry: "true"
  name: cert-manager
  namespace: ibm-cpd
  ownerReferences:
  - apiVersion: cpd.ibm.com/v1
    kind: Ibmcpd
    name: ibmcpd
    uid: 6f246bb1-5635-4f6f-a5f5-c0c495d9f12d
  resourceVersion: "66201987"
  uid: 399c9d31-b5db-42cf-a31a-aaf7b2751693
spec:
  requests:
  - operands:
    - name: ibm-cert-manager-operator
    registry: common-service
    registryNamespace: ibm-common-services
status:
  conditions:
  - lastTransitionTime: "2024-02-14T20:48:05Z"
    lastUpdateTime: "2024-02-14T20:48:05Z"
    message: operator ibm-cert-manager-operator is ready
    reason: operator is ready
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-02-14T20:48:05Z"
    lastUpdateTime: "2024-02-14T20:48:05Z"
    message: operands from ibm-cert-manager-operator are created
    reason: operands are created
    status: "True"
    type: Ready
  members:
  - name: ibm-cert-manager-operator
    phase:
      operandPhase: Running
      operatorPhase: Running
  phase: Running
</pre>
</details>

`$ oc get operandrequest -n ibm-cpd  ibm-cpd-cert-mgr-dep -o yaml`
<details>
<summary> ibm-cpd-cert-mgr-dep YAML</summary>
<pre>
apiVersion: operator.ibm.com/v1alpha1
kind: OperandRequest
metadata:
  annotations:
    operator.ibm.com/operandregistry-is-not-found: "false"
  creationTimestamp: "2024-02-14T20:52:33Z"
  finalizers:
  - finalizer.request.ibm.com
  generation: 1
  labels:
    ibm-common-services.common-service/config: "true"
    ibm-common-services.common-service/registry: "true"
  name: ibm-cpd-cert-mgr-dep
  namespace: ibm-cpd
  ownerReferences:
  - apiVersion: zen.cpd.ibm.com/v1
    kind: ZenService
    name: lite-cr
    uid: 9d095816-7a47-4888-98c8-a8c130775cbe
  resourceVersion: "66209850"
  uid: 427746df-fbee-4098-a081-dc2c5d2aa14a
spec:
  requests:
  - operands:
    - name: ibm-cert-manager-operator
    registry: common-service
    registryNamespace: ibm-common-services
status:
  conditions:
  - lastTransitionTime: "2024-02-14T20:52:34Z"
    lastUpdateTime: "2024-02-14T20:52:34Z"
    message: operator ibm-cert-manager-operator is ready
    reason: operator is ready
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-02-14T20:52:34Z"
    lastUpdateTime: "2024-02-14T20:52:34Z"
    message: operands from ibm-cert-manager-operator are created
    reason: operands are created
    status: "True"
    type: Ready
  members:
  - name: ibm-cert-manager-operator
    phase:
      operandPhase: Running
      operatorPhase: Running
  phase: Running
</pre>
</details>

6. After CP4D role succeeds, validate that IBM Cert Manager was added:
```
$ oc get sub,csv -n ibm-common-services|egrep "cert-|NAME"
NAME                                                                         PACKAGE                           SOURCE                 CHANNEL
subscription.operators.coreos.com/ibm-cert-manager-operator                  ibm-cert-manager-operator         ibm-operator-catalog   v3.23
NAME                                                                                       DISPLAY                                VERSION   REPLACES                                       PHASE
clusterserviceversion.operators.coreos.com/ibm-cert-manager-operator.v3.25.10              IBM Cert Manager                       3.25.10                                                  Succeeded
```

**Comment by andrercm** [comment]
Having only the `ibm-cert-manager-operator.v3.25.10` operator pod should be fine as long as it does not spins up the actual cert-manager deployments and pods i.e cert-manager-webhook or cert-manager-cainjector pods (these should only exist in cert-manager namespace after January).

**Comment by rene-oromtz** [comment]
Thanks @andrercm!
As you mentioned, no pods related to webhooks and cainjector were created in the ibm-common-services. Running the command you shared in did is only showing cert-manager:

```
$ oc get pods -A | grep cert-manager-cainjector | awk '{print $1}'
cert-manager
```

**Comment by andrercm** [comment]
Great so you're all set! You just have one cert-manager instance running which is the expected. 
Let me know if you have any further questions, cheers.
