### ISSUE TITLE
File generated with Gencfg_mongo for an existing DocumentDB having issues with sls role

### ISSUE THREAD

**Issue by whoiscnu** [ibm-mas/ansible-devops#1219]
Hello Team,
While generating configuration from an existing DocumentDB configuration, issues are seen while running the role sls.
The snippet of mongodb yaml when DOcuementDB is created (through ansible role mongodb )is different from the yaml generated from an existing installation(created manually from AWS console).  Request to look into the issue

Error while running sls role with an mongo config generated from existing installation.

TASK [ibm.mas_devops.sls : Fail if mongocfg missing required mongo connection details] ***************************************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}
TASK [ibm.mas_devops.sls : Override MongoDb facts bases on mongocfg] *********************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'certificates'. 'dict object' has no attribute 'certificates'. 'dict object' has no attribute 'certificates'. 'dict object' has no attribute 'certificates'\n\nThe error appears to be in '/root/.ansible/collections/ansible_collections/ibm/mas_devops/roles/sls/tasks/install/main.yml': line 225, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Override MongoDb facts bases on mongocfg\n  ^ here\n"}

NO MORE HOSTS LEFT ***********************************************************************************************************************************************************************************************

PLAY RECAP *******************************************************************************************************************************************************************************************************
localhost                  : ok=31   changed=0    unreachable=0    failed=1    skipped=17   rescued=0    ignored=0

**Comment by whoiscnu** [comment]
The issue was with the incorrect indentation for certificates in 
https://github.com/ibm-mas/ansible-devops/edit/master/ibm/mas_devops/roles/gencfg_mongo/templates/suite_mongocfg.yml.j2
Also Rewrites are defaulted to true inspite of setting false for docdb. 
The ca certificates configured are 2019 and not 2048rsa for even new docdb created with mongo role.

spec:
  displayName: "External MongoDB in 'mas-{{mas_instance_id}}-core' namespace"
  type: external
  config:
    configDb: admin
    retryWrites: {{mongodb_retry_writes}}
    authMechanism: DEFAULT
    credentials:
      secretName: mongodb-{{mas_instance_id|lower}}-admin
    hosts:
      {{ mongodb_hosts | indent(6) }}
{%- if mongo_certs is defined and mongo_certs | length > 0 %}
certificates:
      {{ mongo_certs | indent(width=6, first=False) }}
{%- endif %}

**Comment by whitfiea** [comment]
This should be fixed in https://github.com/ibm-mas/ansible-devops/pull/1256
