### ISSUE TITLE
DocDB CA cert incorrect

### ISSUE THREAD

**Issue by whitfiea** [ibm-mas/ansible-devops#1223]
The docDB CA cert that is added into the mongocfg is now incorrect as AWS have removed the use the the 2019 CA and are now using a different CA with a longer expire time.

**Comment by whoiscnu** [comment]
Yes, global.pem has to be replaced in this section for the root CA.

Also I had to add an Intermediate CA (Subsidiary CA) in certiificates section (which I got by connecting through Openssl with the DocDB and not the server certificate ) in absence of which error that local issuer is not available was thrown.

# 5. Download DocDB CA Cert from AWS and Create DocDB creds Secret and MongoCfg
# -----------------------------------------------------------------------------
- name: "Download Amazon DocumentDB Certificate Authority (CA) certificates"
  shell: |
    wget https://s3.amazonaws.com/rds-downloads/rds-ca-2019-root.pem -O /tmp/rds-ca-2019-root.pem
    wget [https://s3.amazonaws.com/rds-downloads/rds-ca-2019-{{aws_region}}.pem](https://s3.amazonaws.com/rds-downloads/rds-ca-2019-%7B%7Baws_region%7D%7D.pem) -O /tmp/rds-ca-2019-{{aws_region}}.pem
 
- name: Set DocumentDB certificates
  set_fact:
    docdb_master_root_cert: "{{ lookup('file', '/tmp/rds-ca-2019-root.pem') }}"
    docdb_master_cert: "{{ lookup('file', '/tmp/rds-ca-2019-{{aws_region}}.pem') }}"
 
- name: "Generate MongoCfg with DocDB details mongo-{{ mongodb_namespace }}.yml"
  ansible.builtin.template:
    src: aws/suite_mongocfg.yml.j2
    dest: "{{ mas_config_dir }}/mongo-{{ mongodb_namespace }}.yml"

**Comment by whitfiea** [comment]
This is now fixed via https://github.com/ibm-mas/ansible-devops/pull/1229
