### ISSUE TITLE
SLS Installation fails with MODULE Error for version 5 of Document DB Engine Version

### ISSUE THREAD

**Issue by whoiscnu** [ibm-mas/ansible-devops#1227]
SLS installation fails during LicenseService activation with DocumentDB Version 5.0 Engine. It works fine with v 4.0

**Comment by whoiscnu** [comment]
conditions:
    - lastTransitionTime: '2024-04-03T02:26:49Z'
      message: 'MongoDB configuration (certificates or credentials) is not valid. Ensure that mongo configuration, including certificates and credentials is correct '
      reason: NotReady
      status: 'False'
      type: Ready
    - lastTransitionTime: '2024-04-03T23:07:08Z'
      message: 'MongoDB configuration (certificates or credentials) is not valid: docdb-nonprod.cluster-cb26ayaug7kr.ap-southeast-2.docdb.amazonaws.com:27018: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 660de0fba6acbf17140fd6b8, topology_type: Unknown, servers: [<ServerDescription (''docdb-XXXX.cluster-XXXXX.ap-southeast-2.docdb.amazonaws.com'', 27018) server_type: Unknown, rtt: None, error=NetworkTimeout(''docdb-nonprod.cluster-XXXX.ap-southeast-2.docdb.amazonaws.com:27018: timed out'')>]> '
      reason: IncorrectMongoCredentialsOrCertificates
      status: 'False'
      type: SystemDatabaseReady
    - lastTransitionTime: '2024-04-03T02:26:49Z'
      message: ''

**Comment by whoiscnu** [comment]
The certificates indentation is not yet fixed but still the sls fails with invalid mongo configuration.  is the latest ansible version collection tested with documentdb?

**Comment by durera** [comment]
If you haven't already, please raise a support ticket against SLS for this so that this report/query gets to the SLS development team.  Issues in this repo are for issues with the automation/ansible code rather than problems with the things that it deploys.

**Comment by whitfiea** [comment]
@whoiscnu DocDB v5 works with SLS. The error looks to be one of connectivity rather than engine version. You should also ensure that you are using an up to date ansible-devops that has this change https://github.com/ibm-mas/ansible-devops/pull/1229 that updated the certificates used for new docDB instances.
