### ISSUE TITLE
Grafana V5 operator fails to install in Airgap mode

### ISSUE THREAD

**Issue by saurabhrajguru** [ibm-mas/ansible-devops#1230]
After the last update from V4 to V5 we have attempted installations.
https://github.com/ibm-mas/ansible-devops/issues/1196

Grafana V5 operator fails to install in the airgap mode.

This time we are observing the failures within install plan.
We are seeing errors about.

`unpack job not completed: Unpack pod(openshift-marketplace/67894be2e29a8ac0ffa0cd0ea7a6ef4760ffb784a688bd1624783b5ccbv6xm7) container(pull) is pending. Reason: ImagePullBackOff, Message: Back-off pulling image "quay.io/community-operator-pipeline-prod/grafana-operator@sha256:2e1074f75d88b0371b8ea7cabc35c051db3ace5095df5d9ceec6c37922b71b42". `

We have checked in the private registry and it looks like that image and tag do exist.

Subscription failure.
![image](https://github.com/ibm-mas/ansible-devops/assets/7845334/4de28ace-1515-430e-abdc-c63c07a1fea8)

**Comment by andrercm** [comment]
@saurabhrajguru is this issue still valid with latest ansible-devops collection?

**Comment by SalaryTheft** [comment]
@andrercm I got same error with latest ansible-devops collection (19.0.0).
Modifying ICSP (#1264) didn't worked for me so I had to skip Grafana installation. 

```bash
export CLUSTER_MONITORING_INCLUDE_GRAFANA=False
```

**Comment by durera** [comment]
Merging duplicate issue https://github.com/ibm-mas/ansible-devops/issues/1264 into this and closing 1264.

Hello,

the Grafana operator gets its dependencies from `ghcr.io/grafana` and `docker.io/grafana`

These are not in [redhat-catalogs.yml.j2](https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/ocp_contentsourcepolicy/templates/redhat-catalogs.yml.j2) and thus the installation fails

For example I had to add the following entries to the generated ICSP:
```yaml
    - mirrors:
        - 'registry.gym.lan:8443/grafana'
      source: ghcr.io/grafana
    - mirrors:
        - 'registry.gym.lan:8443/grafana'
      source: docker.io/grafana
```

**Comment by stonepd** [comment]
Fixed in https://github.com/ibm-mas/ansible-devops/releases/tag/20.1.0 with https://github.com/ibm-mas/ansible-devops/pull/1314
