### ISSUE TITLE
Issue creating Customer File Storage for MAS

### ISSUE THREAD

**Issue by whoiscnu** [ibm-mas/ansible-devops#1242]
https://github.com/ibm-mas/ansible-devops/blame/63268c32c0ab8b421b5590578f6fbf96c756ee58/ibm/mas_devops/roles/suite_manage_customer_files_config/tasks/main.yml#L39

HelloTeam,

Faced issue during setup of customer file storage for MAS
community.kubernetes.k8s_info:  needs to be changed to kubernetes.core.k8s_info 

Regards
Srinivasa

**Comment by faangbait** [comment]
#1404

**Comment by whitfiea** [comment]
Fixed in https://github.com/ibm-mas/ansible-devops/pull/1404
