### ISSUE TITLE
Support Manage timezone configuration

### ISSUE THREAD

**Issue by andrercm** [ibm-mas/ansible-devops#1245]
It has been requested by a business partner to also allow timezone configuration to be supported during Manage workspace configuration.

**Comment by GuilhermeFAC** [comment]
Boa tarde André
Seria um melhoria para escolher tanto o fuso horário do manage que defini o horário do log nos pods bundle all, report …e também poder escolher o fuso horário do servidor DB2, pois o manage usa o horário do DB2 que herda o horário do servidor que por padrão cria com UTC, hoje tem como mudar manual seguindo esse documento https://www.ibm.com/docs/en/cloud-paks/cp-data/4.8.x?topic=administering-setting-timezone-new-existing-deployments

**Comment by andrercm** [comment]
Fix is available in this PR: https://github.com/ibm-mas/ansible-devops/pull/1247
