### ISSUE TITLE
enable option in mascli to select base and secondary language when installing manage

### ISSUE THREAD

**Issue by GuilhermeFAC** [ibm-mas/ansible-devops#1249]
@andrercm

**Comment by andrercm** [comment]
@GuilhermeFAC so this feature is already enabled here in ansible-devops collection, you just need  `export MAS_APP_SETTINGS_SECONDARY_LANGS=JA,DE,AR` as example... but we did not have this enabled in MAS CLI... I have worked on this in this PR:  https://github.com/ibm-mas/cli/pull/854

If you want to have a preview test, you can install MAS/Manage using this cli version `7.18.0-pre.manage-additional-settings`

As in:

```
docker run -v $HOME:/tmp -ti --rm --pull always quay.io/ibmmas/cli:7.18.0-pre.manage-additional-settings
```

This beta version will have the following features with the `mas install` command:

```
- Base and secondary languages
- Allow Manage dedicated Db2 instance to be configured with db2oltp type instead of default db2wh. The db2wh will continue to be the default option, although allowing db2oltp for Manage might be useful for customers using Manage & Cognos integration in the same database since Cognos does not support db2wh type.
- Server timezone: Allow a timezone to be set at ManageWorkspace CR level with {{ mas_app_settings_server_timezone }} property. If this is defined, we will also set Manage dedicated DB2ucluster with the same value in spec.advOpts.timezone: {{ db2_timezone }} property. This way, both Manage server and the corresponding DB2 instance will be running within the same timezone.
```

**Comment by andrercm** [comment]
This is how it should look like now with the supported languages settings enabled in MAS CLI:

<img width="1313" alt="image" src="https://github.com/ibm-mas/ansible-devops/assets/31037381/d284c690-6ae1-4afb-baf0-529ad7cff967">

**Comment by andrercm** [comment]
Also, as we discussed, I am adding option to choose the Manage dedicated DB2 type:

<img width="1646" alt="image" src="https://github.com/ibm-mas/ansible-devops/assets/31037381/a5660ca2-1839-4f54-bd83-9403869cf736">

**Comment by GuilhermeFAC** [comment]
Hi @andrercm, Thank you for the improvements, as soon as possible I will test it on an installation and give you feedback

**Comment by andrercm** [comment]
@GuilhermeFAC were you able to test the above changes for DB2 type and secondary languages in Manage? Are they all good? I'll trust your feedback to promote the changes.

**Comment by GuilhermeFAC** [comment]
The only issue remaining is the db2 timezone, which in the pod needs to have that TZ variable in the environment

**Comment by andrercm** [comment]
@GuilhermeFAC this timezone issue hopefully have been address in this cli version: `8.1.0-pre.manage-additional-settings`
