### ISSUE TITLE
improvement when installing JMS via mascli when installing manage

### ISSUE THREAD

**Issue by GuilhermeFAC** [ibm-mas/ansible-devops#1250]
@andrercm 
Good afternoon, see the possibility of improvement by selecting the option to install jms server when installing manage.

1 - Make the jms go up by enabling the cqin and cqout queues by default (cqout only available in 8.11) following document: https://www.ibm.com/support/pages/node/6962441

2 - Today, when choosing to install jms using mascli, maange goes up with separate report, ui, integration bundles, see the possibility of adding an option to upload jms + pod "all" only.

**Comment by andrercm** [comment]
Hi @GuilhermeFAC so these two features should be also available already in ansible-devops... when calling `suite_app_config` while installing Manage, you can provide the following parameters:

```
export MAS_APP_SETTINGS_SERVER_BUNDLES_SIZE="snojms" # This server bundle flavor deploys only all + jms pods
export MAS_APP_SETTINGS_DEFAULT_JMS="true" # This should enable both cqin and cqout queues. By default it is set to `false`
```

If you want to have a preview test, you can install MAS/Manage using this cli version 7.18.0-pre.manage-additional-settings

As in:

```
docker run -v $HOME:/tmp -ti --rm --pull always quay.io/ibmmas/cli:7.18.0-pre.manage-additional-settings
```

Any feedbacks are welcome!

**Comment by andrercm** [comment]
Here's how it should look like with `7.18.0-pre.manage-additional-settings`

<img width="1695" alt="image" src="https://github.com/ibm-mas/ansible-devops/assets/31037381/c8cb4ec9-a126-4b51-afa0-57d75800e60f">

**Comment by GuilhermeFAC** [comment]
Very good @andrercm , exactly the way I imagined, it makes it a lot easier. If you test it, I'll give you feedback.

**Comment by GuilhermeFAC** [comment]
Hi @andrercm 

![image](https://github.com/ibm-mas/ansible-devops/assets/105025248/c3917bfc-3254-4927-963f-293b7e7aabeb)

and the ingress is ok in the cluster

**Comment by andrercm** [comment]
@GuilhermeFAC is this an IBM Cloud cluster?

**Comment by andrercm** [comment]
interesting... in my IBM Cloud env, this issue does not happen... can you pull the cli image again? I added some debugs in this task to understand what's happening:

```
docker run -v $HOME:/tmp -ti --rm --pull always quay.io/ibmmas/cli:7.18.0-pre.manage-additional-settings
```

If you can provide me the debug logs from the next time you execute that would help assess the issue.

**Comment by GuilhermeFAC** [comment]
What logs? I rerun Docker and return the same error
[itconsol-install-j7l7n-pre-install-check-pod-step-ocp-verify.log](https://github.com/ibm-mas/ansible-devops/files/14763256/itconsol-install-j7l7n-pre-install-check-pod-step-ocp-verify.log)

**Comment by andrercm** [comment]
From your logs it does not seems you're running the latest `7.18.0-pre.manage-additional-settings` version... i added some logs to that... can you go to your openshift and find namespace `mas-$MAS_INSTANCE_ID-pipelines` and then Workload > Deployments > mas-cli > YAML tab and set `imagePullPolicy: Always` then save... It should force the `7.18.0-pre.manage-additional-settings` image to be pulled as a new image then hopefully it will pick the latest... then rerun the pipeline again.

**Comment by GuilhermeFAC** [comment]
I did that and now it's gone lol... I don't know what happened.
![image](https://github.com/ibm-mas/ansible-devops/assets/105025248/25509e59-027a-4964-8b09-2471324e51d3)
![image](https://github.com/ibm-mas/ansible-devops/assets/105025248/dcc470ac-d83d-4705-addc-e53126800731)

**Comment by andrercm** [comment]
ok... so i added a potential fix to that in a hope that it fixes it... so cool it did fix it :)

**Comment by GuilhermeFAC** [comment]
Finally, I see if the installation occurred as defined in the parameters

**Comment by andrercm** [comment]
can you go to Parameters tab and see if you can find some parameters for the following:

- `mas_app_settings_base_lang`
- `mas_app_settings_secondary_langs`
- `mas_app_settings_server_bundle_size`
- `mas_app_setting_default_jms`
- `mas_app_setting_server_timezone`
- `db2_type`
- `db2_timezone`

**Comment by GuilhermeFAC** [comment]
@andrercm  about the timezone in the db2u pod, he defined the property but the server continues with UTC time:

![image](https://github.com/ibm-mas/ansible-devops/assets/105025248/0d7005cb-3221-40f2-8459-d0acfb4881be)

![image](https://github.com/ibm-mas/ansible-devops/assets/105025248/80162331-51f0-433b-a87a-d91f2ca4732e)

For the server to stay in the chosen zone, it is necessary to add a variable in StatefulSets -> db2u -> Environment

TZ - <timezone>

![image](https://github.com/ibm-mas/ansible-devops/assets/105025248/b7e8fb41-78b5-43e5-9203-50ecbca7a77f)

This will create a new pod of the db2u instance and the server will have the timezone applied correctly.

![image](https://github.com/ibm-mas/ansible-devops/assets/105025248/c4539a7a-c038-4a71-95ed-6d7ea88de8e8)

**Comment by andrercm** [comment]
Oh... so the `timezone` property in the `DB2UCluster` server for nothing?

**Comment by GuilhermeFAC** [comment]
I believe that in addition to the property in Db2cluster there must also be this "TZ", but I can't say if only the TZ would solve it, because if you look at the jvm pod or the maxinst pod there is also this TZ in the environment, when We define the timezone through the manage workspace and it adds it to maxinst. I believe there is something missing when we define it in Db2ucluster that should also add this TZ. 

Fallow link : https://www.datagenx.net/2020/03/set-timezone-for-containers-in-openshift.html#:~:text=There%20is%20a%20very%20simple,containers%20to%20the%20timezone%20specified.&text=As%20soon%20as%20this%20command,with%20the%20new%20environment%20variable.

**Comment by GuilhermeFAC** [comment]
Just to update, I installed the maximum with db2oltp database, jms (continuous queue enabled) + pod all, added base language EN + PR-BR and the manage Brazil/East timezone. It went up without any problems and with everything configured. Very good thank you.

This is the only detail left from TZ to db2 in environment

**Comment by andrercm** [comment]
So it seems setting the `advsOpt.timezone` is really the only thing needed to set it during DB2 instantiation... 
https://www.ibm.com/docs/en/cloud-paks/cp-data/4.8.x?topic=administering-setting-timezone-new-existing-deployments

Can you test the two approaches described in this doc and let me know if any works for you? Ideally we would need to have an option that could be set in both ManageWorkspace and DB2 using the same parameter value. i.e both `db2_timezone` and `mas_app_settings_server_timezone` set to the same value to simplify the process.

**Comment by andrercm** [comment]
Does it work it i set `TZ=GMT` (using timezone code instead of city) for example?

**Comment by GuilhermeFAC** [comment]
In TZ if you enter a valid value it works, In Mascli I defined Brazil/East.

The same timezone values in ManageWorkspace can be used to define the db2u TZ. For example, the list has Brazil/East, America/Sao Paulo, so whatever is defined in ManageWorkspace can also be defined in the TZ of the db2u pod.

**Comment by GuilhermeFAC** [comment]
A tip is to see how it is done for Manage, as it has already defined this 'TZ' variable in the environment in the JVM pods and in maxinst when we choose a timezone in the manageworkspace

**Comment by wangqymro** [comment]
@andrercm the tz on the Manageworkspace CR only controls the timezone of the application server, not the database's timezone as database creation and maintenance is not part of Manage operator's responsibility at this point. The cli/ansible will need to populate db2ucluter's timezone when taking the same timezone in manage installation. Also, the db2u timezone functionality only  works after the one coming with CPD 4.7.3, or 11.5.8.0-cn5.

**Comment by andrercm** [comment]
Thanks for clarifying this @wangqymro ... in our case, mas cli does not use DB2 on top of CPD... it uses DB2 standalone currently at s11.5.9.0-cn1 version.

**Comment by andrercm** [comment]
@GuilhermeFAC 

Coming back to this, I have made changes that sets the TN variable in DB2 statefulset as described [here](https://www.datagenx.net/2020/03/set-timezone-for-containers-in-openshift.html#:~:text=There%20is%20a%20very%20simple,containers%20to%20the%20timezone%20specified.&text=As%20soon%20as%20this%20command,with%20the%20new%20environment%20variable)

So db2u pod now can be set:

<img width="739" alt="image" src="https://github.com/ibm-mas/ansible-devops/assets/31037381/353467b4-8ed3-41a2-8db3-e555211bb6b5">

<img width="617" alt="image" src="https://github.com/ibm-mas/ansible-devops/assets/31037381/8e4e0037-a5c0-4157-a333-b08ad652f143">

The changes are included in this cli version `8.1.0-pre.manage-additional-settings`

Can you check if this version contains everything you are expecting? I'll be waiting your feedback to promote these changes.

**Comment by GuilhermeFAC** [comment]
Ok @andrercm , I'll do a new installation to test this change!

**Comment by andrercm** [comment]
@GuilhermeFAC thanks! let me know how that goes and if any adjustments are needed.

**Comment by GuilhermeFAC** [comment]
@andrercm Good afternoon, I instaled using 8.1.0-pre.manage-additional-settings but the varible TZ was not placed in the db2 statefulset

![image](https://github.com/ibm-mas/ansible-devops/assets/105025248/d3ba1378-5c86-4486-b87a-b28bddea0887)

**Comment by GuilhermeFAC** [comment]
and received this error in pipelines

![image](https://github.com/ibm-mas/ansible-devops/assets/105025248/4083a97f-0f95-44bd-910a-9e95842f58e7)

![image](https://github.com/ibm-mas/ansible-devops/assets/105025248/235b8664-3a92-49e2-9d31-fc32f0fe913b)

**Comment by andrercm** [comment]
@GuilhermeFAC can you provide me logs from the `db2` task?
Also make sure you're running the latest version of `8.1.0-pre.manage-additional-settings`

Can you go to your openshift and find namespace mas-$MAS_INSTANCE_ID-pipelines and then Workload > Deployments > mas-cli > YAML tab and set imagePullPolicy: Always then save... It should force the `8.1.0-pre.manage-additional-settings` image to be pulled as a new image then hopefully it will pick the latest... then rerun the pipeline again.

**Comment by GuilhermeFAC** [comment]
[install-egv6q7-db2-manage-pod-step-db2.log](https://github.com/ibm-mas/ansible-devops/files/14962108/install-egv6q7-db2-manage-pod-step-db2.log)

Allrigth , I am going to try

**Comment by andrercm** [comment]
@GuilhermeFAC i found the problem... the code was not finding the right db2 pod to add the timezone var... it was finding the db2-etcd pod...

```
TASK [ibm.mas_devops.db2 : Set timezone variable in db2u statefulset] **********
changed: [localhost] => changed=true 
  cmd: oc set env sts c-mas-cp4upgrade-main-manage-etcd TZ=UTC -n db2u
  delta: '0:00:00.388820'
  end: '2024-04-12 21:47:56.030679'
  msg: ''
  rc: 0
  start: '2024-04-12 21:47:55.641859'
  stderr: ''
  stderr_lines: <omitted>
  stdout: statefulset.apps/c-mas-cp4upgrade-main-manage-etcd updated
  stdout_lines: <omitted>

TASK [ibm.mas_devops.db2 : debug] **********************************************
ok: [localhost] => 
  db2_set_timezone_output.stdout_lines:
  - statefulset.apps/c-mas-cp4upgrade-main-manage-etcd updated

TASK [ibm.mas_devops.db2 : debug] **********************************************
```

I fixed the problem, it should be available now in `8.1.0-pre.manage-additional-settings`

**Comment by andrercm** [comment]
Great news @GuilhermeFAC ... is there any other feedback you want to highlight? Or are all the implementations you expected contained at this point?

**Comment by GuilhermeFAC** [comment]
At the moment the most necessary ones are implemented, it looks very good, Thank you.

I have a suggestion but it is for the storage issue, being able to select the type of storage per project, for example, in db2 select file and block gold(10 iops), for prometheus select bronze(2 iops), pvc for doclinks bronze(2iops) ), being able to choose a project that uses separate PVC, as not everything needs 10 Iops. but this point must be more complicated for you. But if possible it would be cool.

**Comment by andrercm** [comment]
Those are good feedbacks @GuilhermeFAC 

I think some of that might be accomplished currently using the ansible-devops collection directly, but they might but be backported/supported in MAS cli yet. In MAS CLI, the current approach is to defined one specific type for file and another type for block storage and reuse that across the install pipeline where needed.

Feel free to open an issue for this customization in the CLI repo to a future enhancement: https://github.com/ibm-mas/cli

As to the scope of improvements that we have worked together, I'll close the current issue as everything has been validated on your side! Thanks a lot for your help, hopefully pretty soon these changes will be merged and released in the MAS CLI. In meanwhile you can keep using the beta version provided.
