### ISSUE TITLE
Error in mascli when selecting install cognos, I did not define the cpd version variable

### ISSUE THREAD

**Issue by GuilhermeFAC** [ibm-mas/ansible-devops#1251]
@andrercm 
Here is a correction for the error

path mascli/functions/internal/install_config_applications
    ---if prompt_for_confirm "Install Cognos Analytics"; then
        CPD_INSTALL_COGNOS=true
        export CP4D_VERSION="4.6.3"    <--I added this line-->
        DEPLOY_CP4D=run

**Comment by andrercm** [comment]
@GuilhermeFAC can you test with this cli `7.18.0-pre.manage-additional-settings` version and see if that falls in the same error?

```
docker run -v $HOME:/tmp -ti --rm --pull always quay.io/ibmmas/cli:7.18.0-pre.manage-additional-settings
```
