### ISSUE TITLE
Unsupported version of strimzi kafka

### ISSUE THREAD

**Issue by alequint** [ibm-mas/ansible-devops#1273]
Version 3.5.1 of `strimzi` kafka is no longer supported. It must install 3.6.0, 3.6.1 or 3.7.0.

This is a condition of maskafka `Kafka` instance under `strimzi` project:

<img width="738" alt="image" src="https://github.com/ibm-mas/ansible-devops/assets/15021471/1a7e2dc0-ca5f-41c0-960f-9a072cd78fb1">

**Comment by andrercm** [comment]
@alequint this will be fixed by this PR: https://github.com/ibm-mas/ansible-devops/pull/1240

**Comment by andrercm** [comment]
Fix PR has been merged already. Closing this.
