### ISSUE TITLE
Role AppConnect Issue with OCP version 4.11 or later

### ISSUE THREAD

**Issue by nasirchouhan** [ibm-mas/ansible-devops#1278]
I have OCP 4.12.55 Cluster for HPU.

While Deploying app connect, I face the following issues.

Dashboard operand 12.0.6.0-r1 has been installed, but OCP 4.11 or later does not match the supported environment for this release.
 
And Dashboard pod status keep showing as 1/2 and 2/2.
 
Logs:
2024-04-22 19:52:08.627Z: Using application name app
22024-04-22 19:52:08.631Z: METRICS_TRANSPORT is not set, so not sending metrics
32024-04-22 19:52:19.843Z: Using cluster env vars for kube config
42024-04-22 19:52:19.861Z: Using cluster env vars for kube config
5[HPM] Proxy created: / -> https://icp4i-services-integration.integration.svc:3000/
6[HPM] Proxy rewrite rule created: "^/icp4i" ~> "/v1"
7[HPM] Subscribed to http-proxy events: [ 'proxyReq', 'error', 'close' ]
 
Please do the needful or advise, how to resolve this issue.

Regards,

Nasir Ahmad

**Comment by nasirchouhan** [comment]
Any update on above ...???

Regards,

Nasir Ahmad

**Comment by nasirchouhan** [comment]
When we get this issue resolved ... It is more than a week now and and didn't here anything on this.

**Comment by whitfiea** [comment]
@nasirchouhan this appears to be a problem with the level of appconnect you installed and the OCP level. Did you resolve this? You would need to talk to AppConnect support on this issue.
