### ISSUE TITLE
SLS role does not verify SLS bootstrap success

### ISSUE THREAD

**Issue by durera** [ibm-mas/ansible-devops#130]
When using `ibm.mas_devops.sls` to bootstrap a license ID and or key the role should assert that the bootstrap was successful.  Currently it does not, allowing the role to report success when the bootstrap failed.

e.g.  after running the role the LicenseService was left in this state, but the role reported back success.  This caused the deployment pipeline to fail much later than it should have.

````
oc -n ibm-sls get licenseservice
NAME   VERSION   STATUS   INITIALIZED            LICENSEID      REGISTRATIONKEY               AGE
sls    3.2.4     Ready    MissingConfiguration   <redacted>     <redacted>                    8h
```

In this scenario (easily reproduced by using any invalid licence file content) the role should fail because the initialized status condition is indicating that the bootstrap did not succeed.

**Comment by alequint** [comment]
@caroazad can you take a look at this issue?
