### ISSUE TITLE
Issue with latest pipeline setup of MAS 8.11, MAS CLI: 9.0.1

### ISSUE THREAD

**Issue by SatishSNIBM** [ibm-mas/ansible-devops#1316]
@Hi Team,

we just started MAS 8.11 installation, getting the below error. Need urgent help

[User error] PipelineRun mas-watsonx-pipelines/watsonx-install-khnjz doesn't bind Pipeline mas-watsonx-pipelines/mas-install's Workspaces correctly: pipeline requires workspace with name "shared-certificates" be provided by pipelinerun

<img width="1406" alt="Screenshot 2024-05-21 at 4 20 57 PM" src="https://github.com/ibm-mas/ansible-devops/assets/101411336/7540b572-c608-4454-bd12-d33fdfd9f1c9">
<img width="1409" alt="Screenshot 2024-05-21 at 4 20 41 PM" src="https://github.com/ibm-mas/ansible-devops/assets/101411336/e63ec95d-b3f2-4298-86c6-1feeb6feeb22">

@sanjayprab  @whitfiea 

thanks
Satish / Ruthu

**Comment by whitfiea** [comment]
@SatishSNIBM this is now fixed in https://github.com/ibm-mas/cli/releases/tag/9.1.0
