### ISSUE TITLE
Issue running upgrade to MAS 9.x from MAS 8.11.12

### ISSUE THREAD

**Issue by SatishSNIBM** [ibm-mas/ansible-devops#1352]
Getting below errror upon running upgrade steps after pointing the CATALOG to _**`v9-240625-amd64`**_

POD Name --> "ALL" Server bundle pod. it is always showing 1/2 status

ERROR
********
Launching defaultServer (WebSphere Application Server 24.0.0.4/wlp-1.0.88.cl240420240408-2000) on Eclipse OpenJ9 VM, version 11.0.22+7 (en_US)
[AUDIT   ] CWWKE0001I: The server defaultServer has been launched.
[AUDIT   ] CWWKE0100I: This product is licensed for development, and limited production use. The full license terms can be viewed here: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/license/base_ilan/ilan/24.0.0.4/lafiles/en.html
[AUDIT   ] CWWKG0093A: Processing configuration drop-ins resource: /opt/ibm/wlp/usr/servers/defaultServer/configDropins/defaults/keystore.xml
[AUDIT   ] CWWKG0028A: Processing included configuration resource: /config/manage/serverxml/server-custom.xml
[AUDIT   ] CWWKZ0058I: Monitoring dropins for applications.
[WARNING ] CWOWB1009W: Implicit bean archives are disabled.
[WARNING ] CWWKT0033W: An attempt was made to configure deflate|gzip|x-gzip|zlib|identity|none as the server-preferred algorithm. The supported values are gzip, x-gzip, zlib, deflate, identity, and none. The default configuration none is used instead.
[WARNING ] CWWKT0033W: An attempt was made to configure deflate|gzip|x-gzip|zlib|identity|none as the server-preferred algorithm. The supported values are gzip, x-gzip, zlib, deflate, identity, and none. The default configuration none is used instead.
[WARNING ] CWWKT0033W: An attempt was made to configure deflate|gzip|x-gzip|zlib|identity|none as the server-preferred algorithm. The supported values are gzip, x-gzip, zlib, deflate, identity, and none. The default configuration none is used instead.
[AUDIT   ] CWWKI0001I: The CORBA name server is now available at corbaloc:iiop:localhost:2809/NameService.
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://masgsi-masgsi-all-65fcd6d9d4-l8swb:9080/jwt/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://masgsi-masgsi-all-65fcd6d9d4-l8swb:9080/oidcclient/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://masgsi-masgsi-all-65fcd6d9d4-l8swb:9080/oauth2/
[WARNING ] SRVE9967W: The manifest class path pdq.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/lib/db2jcc.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path oraclepki.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/lib/oraclethin.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path ibmorbtools.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/lib/tools.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path pdq.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/lib/db2jcc.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path oraclepki.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/lib/oraclethin.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/jmespath-java-1.12.54.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/businessobjects.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/commons-httpclient.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/businessobjects.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/mas-data-dictionary-lib-1.0.0 can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/businessobjects.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/axis.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/mboejb.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/junit-4.4.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/mboejb.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path pdq.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/lib/db2jcc.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path oraclepki.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/lib/oraclethin.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/jmespath-java-1.12.54.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/businessobjects.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/commons-httpclient.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/businessobjects.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/mas-data-dictionary-lib-1.0.0 can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/businessobjects.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/axis.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/mboweb.war or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/junit-4.4.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/mboweb.war or its parent.
[WARNING ] SRVE9967W: The manifest class path pdq.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/lib/db2jcc.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path oraclepki.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/lib/oraclethin.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/jmespath-java-1.12.54.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/businessobjects.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/commons-httpclient.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/businessobjects.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/mas-data-dictionary-lib-1.0.0 can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/businessobjects.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/axis.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/meaweb.war or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/junit-4.4.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/meaweb.war or its parent.
[WARNING ] SRVE9967W: The manifest class path pdq.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/lib/db2jcc.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path oraclepki.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/lib/oraclethin.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/jmespath-java-1.12.54.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/businessobjects.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/commons-httpclient.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/businessobjects.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/mas-data-dictionary-lib-1.0.0 can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/businessobjects.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/axis.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/maxrestweb.war or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/junit-4.4.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/maxrestweb.war or its parent.
[WARNING ] SRVE9967W: The manifest class path pdq.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/lib/db2jcc.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path oraclepki.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/lib/oraclethin.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/jmespath-java-1.12.54.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/businessobjects.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/commons-httpclient.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/businessobjects.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/mas-data-dictionary-lib-1.0.0 can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/businessobjects.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/axis.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/mboejb.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/junit-4.4.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/mboejb.jar or its parent.
[WARNING ] CWWKZ0126W:  The maximo context root value that is specified on the maximo-all application has no effect.
[WARNING ] SRVE9967W: The manifest class path pdq.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/lib/db2jcc.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path oraclepki.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/lib/oraclethin.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/jmespath-java-1.12.54.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/businessobjects.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/commons-httpclient.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/businessobjects.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/mas-data-dictionary-lib-1.0.0 can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/businessobjects.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/axis.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/mboejb.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/junit-4.4.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/mboejb.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path pdq.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/lib/db2jcc.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path oraclepki.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/lib/oraclethin.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/jmespath-java-1.12.54.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/businessobjects.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/commons-httpclient.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/businessobjects.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/mas-data-dictionary-lib-1.0.0 can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/businessobjects.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/axis.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/mboweb.war or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/junit-4.4.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/mboweb.war or its parent.
[WARNING ] SRVE9967W: The manifest class path pdq.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/lib/db2jcc.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path oraclepki.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/lib/oraclethin.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/jmespath-java-1.12.54.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/businessobjects.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/commons-httpclient.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/businessobjects.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/mas-data-dictionary-lib-1.0.0 can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/businessobjects.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/axis.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/meaweb.war or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/junit-4.4.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/meaweb.war or its parent.
[WARNING ] SRVE9967W: The manifest class path pdq.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/lib/db2jcc.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path oraclepki.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/lib/oraclethin.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/jmespath-java-1.12.54.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/businessobjects.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/commons-httpclient.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/businessobjects.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/mas-data-dictionary-lib-1.0.0 can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/businessobjects.jar or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/axis.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/maxrestweb.war or its parent.
[WARNING ] SRVE9967W: The manifest class path lib/junit-4.4.jar can not be found in jar file wsjar:file:/opt/ibm/wlp/usr/servers/defaultServer/apps/maximo-all.ear!/maxrestweb.war or its parent.
[ERROR   ] CNTR9269W: The mboejb.jar Enterprise JavaBeans (EJB) module does not have any enterprise beans configured.
[ERROR   ] CNTR4002E: The mboejb.jar EJB module in the maximoui application failed to start. Exception: com.ibm.ws.exception.RuntimeError: com.ibm.ejs.container.EJBConfigurationException: The mboejb.jar Enterprise JavaBeans (EJB) module does not have any enterprise beans configured.
	at com.ibm.ws.ejbcontainer.runtime.AbstractEJBRuntime.startModule(AbstractEJBRuntime.java:583)
	at [internal classes]
Caused by: com.ibm.ejs.container.EJBConfigurationException: The mboejb.jar Enterprise JavaBeans (EJB) module does not have any enterprise beans configured.
	at com.ibm.ws.ejbcontainer.runtime.AbstractEJBRuntime.startModule(AbstractEJBRuntime.java:480)
	... 1 more

ERROR IN MONITOR AGENT POD
*****************
06:48:42.440 [Default Executor-thread-11] ERROR com.ibm.monitoring.agent.utils.AgentUtils - The server has not started yet. Please wait for it to start.
ERROR AgentUtils - The server has not started yet. Please wait for it to start.

cc: @sanjayprab @whitfiea

**Comment by whitfiea** [comment]
@SatishSNIBM this would be a product issue. Can you raise a IBM Support issue for this?
