### ISSUE TITLE
Installing MAS in a cluster installed with IBM-

### ISSUE THREAD

**Issue by ekambaraml** [ibm-mas/ansible-devops#1363]
MAS 9 install is failing with error 

```
Error: IBM Maximo Operator Catalog  is already installed on this cluster.
If you wish to install a new MAS instance using the v9-240625-amd64 catalog please first run "mas update" to switch to this catalog, this will ensure the appropriate actions are performed as part of the catalog update.
```

![image](https://github.com/ibm-mas/ansible-devops/assets/26153008/c9f242d5-e330-4845-82cd-7e0dace01428)

IBM Spectrum Fusion storage installed in this cluster with ibm-catelog-operator already.
![image](https://github.com/ibm-mas/ansible-devops/assets/26153008/b9af491a-c5b5-4b13-b265-9bca7f3a64db)

![image](https://github.com/ibm-mas/ansible-devops/assets/26153008/61b04102-3b6c-4b58-8c89-805c54e128c2)

Have we tested with Fustion storage and any additional configuration needed ?

**Comment by whitfiea** [comment]
For installing Fusion please follow https://www.ibm.com/docs/en/mas-cd/continuous-delivery?topic=cli-prerequisites-installing#c_airgap_prerequisites__fdf__title__1 to ensure that the ibm-operator-catalog is the MAS catalog. The MAS Catalog has what the Fusion operator needs.
