### ISSUE TITLE
Suite_DNS Cloudflare 

### ISSUE THREAD

**Issue by zoltanpesko** [ibm-mas/ansible-devops#1373]
In **suite_dns role** there is a **potential bug** for the Cloudflare DNS Integration
[](https://ibm-mas.github.io/ansible-devops/roles/suite_dns/#role-variables-cloudflare-dns-integration)

The script creates the 
**apps.cluster.cloud** but should be **router-default.apps.cluster.cloud**

Could you please check it?

**Comment by JonahLuckett** [comment]
Looking into this for you - will report back when I have an answer

**Comment by zoltanpesko** [comment]
Hi Jonah, is there any update on it?

**Comment by zoltanpesko** [comment]
HI all,

In addition to that can we add to the script the following?

As a possible workaround, you can remove the entry that contains the old domain name, for example if the entry for CLIENTID: "manage" still has the old domain name, run the following command:
To connect to the mongo database, refer to:
[](https://www.ibm.com/support/pages/node/7011393
)execute the following commands to verify the content of the collection, in this example, the mas instance id is "test"

```
show dbs
use mas_test_core
show collections
db.OauthClient.find()
```
`db.OauthClient.deleteOne({CLIENTID: "manage"})`
then delete the following pods:
in mas core namespace: internalapi
in manage namespace: entitymgr-ws

**Comment by sanjayprab** [comment]
@zoltanpesko Apologies for the delay in response. Could you please provide more specific or logs. and what cloudflare_zone and/or cloudflare_subdomain you are passing.
