### ISSUE TITLE
AI Broker playbook

### ISSUE THREAD

**Issue by amkanjil** [ibm-mas/ansible-devops#1375]
How can we install the AI Broker available in MAS 9. Is there a playbook available today?

**Comment by JonahLuckett** [comment]
Looking into this now - will update here when I have an answer

**Comment by JonahLuckett** [comment]
There is a pull request open for such a playbook here: https://github.com/ibm-mas/ansible-devops/pull/1345 - while close to being done it is not currently ready to be merged in. Will update here when that PR is merged in and is ready to use.

**Comment by JonahLuckett** [comment]
Playbook is documented at: https://github.com/ibm-mas/ansible-devops/blob/master/docs/playbooks/oneclick-aibroker.md
