### ISSUE TITLE
Can't pull predefined version of NVIDIA GPU driver (nvidia_gpu role)

### ISSUE THREAD

**Issue by SalaryTheft** [ibm-mas/ansible-devops#1384]
https://github.com/ibm-mas/ansible-devops/blob/a4c2c3b04e4967bdc5da62b00bec2b0923aa7b33/ibm/mas_devops/roles/nvidia_gpu/defaults/main.yml#L10

![스크린샷 2024-07-12 163442](https://github.com/user-attachments/assets/7188e67e-5da0-4e6e-b4b9-b62cd02a18aa)

I updated `gpu-cluster-policy` (`ClusterPolicy`  kind) to use latest driver and it helped.

**Comment by SalaryTheft** [comment]
Just noticed RHOCS 4.14 is based on RHEL 9.2
https://access.redhat.com/articles/6907891

**Comment by JonahLuckett** [comment]
Looking into this now for you

**Comment by durera** [comment]
https://jsw.ibm.com/browse/MASCORE-4342
