### ISSUE TITLE
Documentation issue: hexdumping an SLS License ID

### ISSUE THREAD

**Issue by faangbait** [ibm-mas/ansible-devops#1395]
Throughout the IBM MAS documentation, there's a lot of tricky one-liners to generate the value for SLS_LICENSE_ID, a 12-character hexadecimal string. Most of them are actually three-liners. For example:

- https://www.ibm.com/docs/en/mas-cd/continuous-delivery?topic=services-prerequisites-installing
- https://www.ibm.com/docs/en/mas87/8.7.0?topic=installation-requirements
- https://www.ibm.com/docs/en/mas-cd/continuous-delivery?topic=azure-prerequisites-installing

This is the line I've settled on, which is cleaner than the existing options:

`hexdump -n 6 -e '8/8 "%08X" 1 "\n"' /dev/urandom | tr '[:upper:]' '[:lower:]'`

I wasn't sure which repo the documentation lived in, so I'm hoping the team here can forward this to the appropriate repository.

**Comment by harsh42774** [comment]
Completed and changes are reflected on the site now. 
Issue tracked by the below story:
https://jsw.ibm.com/browse/MASDESIGN-2771
