### ISSUE TITLE
Review operatorgroup naming convention in suite-install

### ISSUE THREAD

**Issue by alequint** [ibm-mas/ansible-devops#141]
Define convention for OperatorGroup naming in suite-install. It must match the standard used by coreapi.

Today: https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/suite_app_install/templates/operator-group.yml.j2#L4

Standard used in corepai: `ibm-{self.applicationId}-operatorgroup` (as per chat [here](https://ibm-watson-iot.slack.com/archives/CNDB5GZ3P/p1641830697087000?thread_ts=1641830369.083700&cid=CNDB5GZ3P))

**Comment by alequint** [comment]
Covered by PR https://github.com/ibm-mas/ansible-devops/pull/317 - work in progress

**Comment by andrercm** [comment]
As mentioned in the associating PR, closing this due to old age/lack of activity
