### ISSUE TITLE
mas mirror-redhat failure, ImageSetConfiguration error from mirror_ocp role

### ISSUE THREAD

**Issue by rene-oromtz** [ibm-mas/ansible-devops#1416]
### Collection version

22.3.1

### Environment information

```console
ibmmas/cli:10.7.3
```

### What happened?

mas mirror-redhat is failing to complete. This problem is  not related to the MAS CLI but to the [mirror_ocp](https://github.com/ibm-mas/ansible-devops/tree/master/ibm/mas_devops/roles/mirror_ocp) role. 

From the template, I can see that for the GPU operators there is a note:
```
# We don't use the v24.3 channel, but oc-mirror fails when the default channel is not included
            # - https://access.redhat.com/solutions/7013461
            # - https://issues.redhat.com/browse/OCPBUGS-385
            - name: v24.3
```

I locally edited the default channel from `v24.3` to `v24.6` and is currently progressing. Looks like an easy fix, however, not sure if its best to add another line with:
`- name: v24.6`
Or modify as what I did to replace `v24.3` to `v24.6`
Right now mirror is progressing, in case something fails, I'll update this issue. 

### Relevant log output

```shell
Error:
error: error generating diff: the current default channel "v24.6" for package "gpu-operator-certified" could not be determined... ensure that your ImageSetConfiguration filtering criteria results in a package version that exists in the current default channel or use the 'defaultChannel' field 

Command used:
mas mirror-redhat -m to-filesystem -d /mascli/mas-images/redhat --mirror-operators --pullsecret /mascli/pull-secret.json --release 4.12
```

**Comment by durera** [comment]
Fixed in https://github.com/ibm-mas/ansible-devops/pull/1422
