### ISSUE TITLE
DRO installation has possible race condition

### ISSUE THREAD

**Issue by benbakowski** [ibm-mas/ansible-devops#1449]
### Collection version

22.5.2

### Environment information

```console
TBC
```

### What happened?

We have a suspected timing window in the DRO role. 

The symptoms are that the ibm-data-reporter-operator-api-token was not automatically available as expected (despite being created via https://github.com/ibm-mas/ansible-devops/blob/1e377b92aec5733e495849055a34e8ea2cfb958a/ibm/mas_devops/roles/dro/tasks/gencfg/main.yml#L39. The suspicion is that this task was run before the service account was ready, meaning that kube garbage collected the secret.

The fix is to add extra checks to ensure the service accounts are ready prior to generating the config.

### Relevant log output

```shell
TBC
```

**Comment by durera** [comment]
Customer is not using our automation for this install, the timing window is due to problems in the bespoke automation.
