### ISSUE TITLE
MAS MVI install ansible playbook does not check existing "Node Feature Discovery" Operator

### ISSUE THREAD

**Issue by kalyan-nookala** [ibm-mas/ansible-devops#1453]
### Collection version

ibm.mas_devops 22.5.2

### Environment information

```console
quay.io/ibmmas/cli:10.9.2
```

### What happened?

Node Feature Discovery: The ansible script is installing this operator, even when the there is an instance of the operator is already installed in the OCP and makes healthy working operator to go into error

### Relevant log output

```shell
N/A
```

**Comment by durera** [comment]
https://jsw.ibm.com/browse/MASCORE-4342
