### ISSUE TITLE
MAS MVI install ansible playbook does not check existing "NVDIA GPU Operator"

### ISSUE THREAD

**Issue by kalyan-nookala** [ibm-mas/ansible-devops#1454]
### Collection version

ibm.mas_devops 22.5.2

### Environment information

```console
quay.io/ibmmas/cli:10.9.2
```

### What happened?

NVIDI GPU Operator: Same as above, the ansible script overwrites “cluster policy” on a healthy and working operator with another version of GPU driver and makes it to go to “not ready” status.

### Relevant log output

```shell
n/a
```

**Comment by durera** [comment]
https://jsw.ibm.com/browse/MASCORE-4342
