### ISSUE TITLE
Backup-Restore Missing Environment Variables

### ISSUE THREAD

**Issue by faangbait** [ibm-mas/ansible-devops#1483]
### Collection version

22.3.2

### Environment information

```console
ansible             8.7.0
ansible-core        2.15.12
```

### What happened?

This ticket is reopening #1430 -- more variables are missing in the scheduled job. 

I suspect the line in [ansible-devops/ibm/mas_devops/common_tasks/backup_restore/create_run_tasks_job.yml](https://github.com/ibm-mas/ansible-devops/blob/e957e0146716f744cdd9eb56675efe5e3023dc1d/ibm/mas_devops/common_tasks/backup_restore/create_run_tasks_job.yml#L62) which is responsible for populating the `MASBR_` variables is not working as intended.

### Relevant log output

```shell
Pods Statuses:    0 Active (0 Ready) / 0 Succeeded / 2 Failed
Pod Template:
  Labels:           batch.kubernetes.io/controller-uid=9d3d2328-e245-4fba-89d8-74b20263b849
                    batch.kubernetes.io/job-name=schedule-full-20240821230439-28739765
                    controller-uid=9d3d2328-e245-4fba-89d8-74b20263b849
                    job-name=schedule-full-20240821230439-28739765
                    mas.ibm.com/masbr=
                    masbr-type=schedule
  Service Account:  masbr-sa
  Containers:
   main:
    Image:      quay.io/ibmmas/cli:latest
    Port:       <none>
    Host Port:  <none>
    Command:
      sh
      -c
      ROLE_NAME=suite_backup_restore ansible-playbook ibm.mas_devops.run_role
    Environment:
      ANSIBLE_LOG_PATH:                 /tmp/ansible.log
      MASBR_CONFIRM_CLUSTER:            false
      MASBR_CREATE_TASK_JOB:            false
      MASBR_RUNNING_IN_TASK_JOB:        true
      MASBR_TASK_JOB_NAMESPACE:         mas-max-core
      MASBR_TASK_JOB_NAME:              schedule-full-20240821230439
      MASBR_JOB_VERSION:                20240821230438
      MAS_INSTANCE_ID:                  max
      MASBR_STORAGE_CLOUD_RCLONE_FILE:  /mnt/configmap/rclone.conf
    Mounts:
      /mnt/configmap from cm-volume (ro)
```

**Comment by durera** [comment]
As part of https://github.com/ibm-mas/ansible-devops/pull/1557 we are removing the capability to run the roles as a job (scheduled or not) controlled by the ``, to focus on a more containable scope of just focusing on performing backup locally to local storage.  This does not prevent someone scheduling a backup to happen using the role, or indeed creating a deployment or job to run this on a Kubernetes cluster, but we don't have the bandwidth to maintain so many different operating modes (hence bugs like this in the first place).
