### ISSUE TITLE
MAS Devops Ansible Collection has no option to provide our own Monodb/DocumentDB Detail

### ISSUE THREAD

**Issue by daemondude** [ibm-mas/ansible-devops#1485]
### Feature and motivation

If we want MAS cli to use Documentdb on AWS cloud or Mongodb on IBM cloud, there is no option to provide as a argument.
We have checked on ibm.mas_devops 23.0.0 version.
How can we provide parameters for MongoDB running outside cluster ?

### Usage example

https://ibm-mas.github.io/cli/commands/install/#step-11-additional-configurations

**Comment by durera** [comment]
This feature was added to the MAS CLI as part of this PR: https://github.com/ibm-mas/cli/pull/1326

It is not released yet, but will be available in the next release.

The CLI will prompt the user if they want to install MongoDB in cluster using the MongoCE operator, and if not will ask for the details of the cluster that they want to use instead - which can be anywhere.

More details here: https://github.com/ibm-mas/cli/blob/master/python/src/mas/cli/install/settings/mongodbSettings.py

We expect this to be available in a new release of the CLI sometime next week once we complete final testing.
