### ISSUE TITLE
cert-manager needs to be installed prior to sls and other issues

### ISSUE THREAD

**Issue by mjdavisibm** [ibm-mas/ansible-devops#150]
I have been installing the dependencies (mongodb, sls, bas) using the collection. I have mongodb installed but in trying to install and configure the SLS I am getting several problems. 

1. In the latest version of the SLS operator (V 3.2.4) you need to have pre-installed the cert-manager (I install the latest community edition operator to do this (V1.6.1) prior to creating the SLS instance `kind: LicenseService` called `sls`
2. `sls-verify.yml` in the `sls_install` role does not seem to accurately follow how the SLS initializes itself and so fails. Unfortunately I have not managed to find any docs that describes the process so I can not offer any actual help here, expect to say that it times out on the second `Wait for LicenseService to be ready (60s delay)` task.
3. There is a part about bootstraping the sls. I have struggled to find any documentation on this to set it up properly. It seems it is licensing information but my understanding of the MAS docs is that you can not add that to the SLS **UNTIL** MAS is installed to get the right info for the license center. The whole area of app point s etc is not at all clear

Just wanted to pas this on

**Comment by durera** [comment]
1. We should document this, the intent within the collection is that `ocp_setup_mas_deps` role is used to lay down all the dependencies in the cluster before progressing (or it's done manually if the user prefers), but we do need to make sure our docs indicate where requirements/dependencies like this exist in the roles, which we don't today.
2. Sady this is a known issue, more details in #130 
3. Could you point me at the doc you found that info, around MAS 8.0 SLS was an internal component inside MAS, so what you picked up from the doc was accurate at some point, but that has not been the case for a long time now, that doc may have been missed.  #3 exists to address the doc in the context of this collection, and when we get to the SLS role documentation I'll make sure we have sufficient info in there to help on this front.  For now hopefully this helps .. when you use the SLS bootstrap capability you can control what the license ID is that will be needed when you generate your license file from license center .. thus if you want to bootstrap SLS and don't already have a license file already you have two options:

- Don't.  Install SLS without bootstrap, an ID will be generated, which you can pick up from APIs and/or the MAS UI if you proceed to install MAS connected to an SLS that hasn't been initialised with a license file yet (which will work, you just won't be able to get past a certain point in the process).
- Make up a license ID (a 12 character hex string), use that to generate your license file, then use the license file and the ID when you bootstrap SLS.

The bootstrap process we have today is far from ideal, but forced on us by the underlying technologies we use.  In the next release of SLS we are greatly simplifying the process of setting up and managing the license inside SLS :+1:

**Comment by whitfiea** [comment]
I added some text in the sls role to indicate that cert-manager is needed before this role is run. The other points are covered by other issues/PRs that are being worked on or have already been fixed, so I think we can close this issue now.
