### ISSUE TITLE
Backup and Restore for Manage

### ISSUE THREAD

**Issue by TalanMMA** [ibm-mas/ansible-devops#1509]
### Feature and motivation

Currently, this playbook ibm.mas_devops.br_manage requires this environment variable DB2_INSTANCE_NAME
but how use this playbook in an environment without DB2 database.

Is it possible to have the same playbook with environment variable DB2_INSTANCE_NAME optional ?

### Usage example

Same usage that the current playbook with environment variable DB2_INSTANCE_NAME optional

**Comment by lu4t** [comment]
Case TS017776770 is related with this. 
Anyone trying to use this playbook when db2 (or any other supported db deployed outside RHOCP) wont be able to use it. 

Is there any workaround, or ETA for the enhancement @durera?

**Comment by witekwww** [comment]
The workaround is to comment out the DB2 role from br_manage playbook.
Inside MAS CLI container run
nano -c /mascli/ansible-devops/playbooks/br_manage.yml
and comment out lines from 89 till 93
![image](https://github.com/user-attachments/assets/29b6a485-3649-4ab3-98d7-874f9da9a020)

You still have to set environment variable DB2_INSTANCE_NAME but You can set whatever You want there - it does not matter.
