### ISSUE TITLE
CP4D should not be the pre-requisite for Cognos used by MAS

### ISSUE THREAD

**Issue by zerospeedzero** [ibm-mas/ansible-devops#1534]
### Feature and motivation

We are working on MAS 8.11 and MAS manage 8.7. We found CP4D is so complex and huge resource (CPU, memory and disk) requirements for the deployment. Our customers is just looking for Cognos reports and we would suggest to deploy Cognos without CP4D in MAS deployment.

### Usage example

Reduce the complexity of both deployment and support to MAS customers.

**Comment by whitfiea** [comment]
@zerospeedzero Could you raise this in the ideas portal https://ibm-ai-apps.ideas.ibm.com/?project=MASM as this is really an enhancement for the product to not rely on CP4D in this scenerio.
