### ISSUE TITLE
Scheduled mongodb backup example

### ISSUE THREAD

**Issue by mudspringhiker** [ibm-mas/ansible-devops#1570]
Please check the example for creating a scheduled back up for mongodb in https://ibm-mas.github.io/ansible-devops/playbooks/backup-restore/#examples:

```
# Create a scheduled backup Job for the dev1 instance
export MASBR_ACTION=backup
export MASBR_BACKUP_SCHEDULE="50 0 * * *"
export MASBR_JOB_TIMEZONE="Asia/Shanghai"
export MASBR_STORAGE_TYPE=local
export MASBR_STORAGE_LOCAL_FOLDER=/tmp/backup
export MAS_INSTANCE_ID=dev1
ansible-playbook ibm.mas_devops.br_mongodb
```

It seems that the environment variable, MASBR_CREATE_TASK_JOB is needed and must be set to `true` to enable a scheduled backup of mongodb. This environment variable is "only valid when using cloud object storage (MASBR_STORAGE_TYPE=cloud)". Therefore, MASBR_STORAGE_TYPE must be set to cloud, and a scheduled backup cannot be done when the storage is local.

Running the example above (using different timezone and schedule, etc.) does not work (no scheduled back up jobs were created, only one tar file was generated).

**Comment by durera** [comment]
We are removing the scheduling function from the role to focus on delivering functioning backup and restore.  The ansible role (inside the CLI image) can easily be used in a kubernetes cronjob if desired, but it's not sustainable for us to maintain this with so many different options as were originally put into the roles (as can be seen from the number of bugs in it sadly).
