### ISSUE TITLE
mas-messages configmap is not part of the Core backup

### ISSUE THREAD

**Issue by sanjayprab** [ibm-mas/ansible-devops#1596]
A customer customized the "Access Denial Message" property in the License Consumption section
this custom message is stored in a configmap, mas-messages, in the mas core namespace.

he performed a backup using the ansible colections, however when he restored the backup, the message was the original one (not the custom one)

this configmap is not included in the list of resources to be backed up, in :
https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/suite_backup_restore/tasks/backup-vars.yml 

Ticket - TS018045570

**Comment by durera** [comment]
Consolidating into a single issue per application with a tasklist (otherwise we will have hundreds of these)
