### ISSUE TITLE
Enable DDoS Protection in IBM CIS

### ISSUE THREAD

**Issue by CAIOFCP** [ibm-mas/ansible-devops#207]
For SRE environments we are looking for automation within the CIS service in IBM Cloud that we can have CNAMES without using wildcard, so the proxy could be enabled and also DDoS protection.

**Comment by andrercm** [comment]
@CAIOFCP @JonahLuckett  I think this is done right? 
I can see this was added as part of the SRE merge work:
https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/suite_dns/defaults/main.yaml#L50

However we are still creating also wildcard entries (as originally the role was designed to do):
https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/suite_dns/tasks/providers/cis/cis_suitedns_basic.yml#L31-L73


and then after SRE merge we also added a step to create the non-wildcard entries:
https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/suite_dns/tasks/providers/cis/cis_dns_mgmt.yml#L32

I would think if `cis_proxy: True` then we can't create the wildcard entries?

**Comment by andrercm** [comment]
@CAIOFCP closing this as we reviewed together the code and this has been recently merged in master:
https://github.com/ibm-mas/ansible-devops/pull/730
