### ISSUE TITLE
Allow GitHub Actions on PullRequests from forks

### ISSUE THREAD

**Issue by whitfiea** [ibm-mas/ansible-devops#247]
At the moment the GitHub Actions are only executed on "push" to a branch in this repo. As all actions are needed to be executed before merging a PR to master it means that a branch on this repo is needed. Only members of the repo can create a branch and non-members need to create a fork. When a PR from a fork is created the Actions are not executed.

It would help external members of the team submit PRs for changes if we got this work.

You can add an action trigger of pull_request https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request but it would mean actions are duplicated when pushing to a branch and creating a PR. It seems it is not that easy to have an "push or pullrequest" as seen here https://github.community/t/how-to-trigger-an-action-on-push-or-pull-request-but-not-both/16662/11

One possible solution is to remove the "push" and replace with:

```
on:
  workflow_dispatch:
  pull_request:
```

This will call the actions on all pull requests (from branch or fork) but would require each user to manually execute the actions on they own branches if needed (you only need the actions to be completed on master branch).

**Comment by durera** [comment]
I don't think we'll likely do this tbh.  We don't have a high rate of contributions from people outside the team currently; if that changes we can revisit this.
