### ISSUE TITLE
community.kubernetes or kubernetes.core modules

### ISSUE THREAD

**Issue by aroute** [ibm-mas/ansible-devops#250]
Some of these are using community module. Is this by design?
https://github.com/ibm-mas/ansible-devops/search?q=community.kubernetes.k8s_info

Ansible tells me it has been [depreciated](https://docs.ansible.com/ansible/latest/collections/community/kubernetes/k8s_info_module.html). I got errors running some of the tasks. I searched to discover this solution (which worked).

Please check. Thanks.

**Comment by whitfiea** [comment]
It should be `kubernetes.core` and those places you found with the old deprecated module should be updated.
