### ISSUE TITLE
Rename playbooks so these can be called via the collection

### ISSUE THREAD

**Issue by whitfiea** [ibm-mas/ansible-devops#261]
In ansible 2.11 you can now call the playbooks using the collection syntax similar to how you call roles. See https://docs.ansible.com/ansible/latest/user_guide/collections_using.html#using-a-playbook-from-a-collection for more details. The problem with our playbooks is all of them have a dash (-) in the filename and as per that link that is not supported.

If we rename the playbooks to use underscore rather than dash then users (assuming those users have ansible 2.11 or above) will be able to call the playbooks like this:
```
ansible-playbook ibm.mas_devops.lite_core_quickburn 
```

**Comment by durera** [comment]
Updates merged into master branch
