### ISSUE TITLE
b3c.16x64.300gb is a better default ROKS flavor

### ISSUE THREAD

**Issue by cuddlyporcupine** [ibm-mas/ansible-devops#279]
https://github.com/ibm-mas/ansible-devops/blob/0f94bf3e9f9c702a1e14df2ecc4ec5447573b2e0/ibm/mas_devops/roles/ocp_provision/defaults/main.yml#L32

A lot folks have disk pressure issues the the 100gb ROKS flavors, so we should change the default ROKS flavor to `b3c.16x64.300gb`

**Comment by whitfiea** [comment]
@cuddlyporcupine Do we know what is taking up all the space on the disk? Just want to cover the chance that this is just a rogue application that is just writing endlessly to local disk vs actual requirement for more local disk storage.
