### ISSUE TITLE
Optimizer is likely redundant?

### ISSUE THREAD

**Issue by aroute** [ibm-mas/ansible-devops#337]
This optimizer playbook does not run. It doesn't move beyond the InstallPlan approval.

https://github.com/ibm-mas/ansible-devops/blob/master/docs/playbooks/oneclick-optimizer.md

I think this component is likely redundant and should be deleted? There is no corresponding "Optimizer" application tile in MAS.

**Comment by alequint** [comment]
@aroute Optimizer is coming now in MAS 8.8 to replace MSO... in fact, the playbook is a bit ahead of time; trying to install that in MAS 8.7 and before, will not work. Starting in 8.8, will be only Optimizer.

**Comment by durera** [comment]
Neither playbook should have been released, addressing this in next update to the collection:

- MSO is EOL after MAS 8.7, and we are not encouraging it's use.
- Optimizer isn't available for MAS 8.7 and the one-click playbooks target a MAS 8.7 deployment
