### ISSUE TITLE
Add auto-detect storage class support to appconnect role

### ISSUE THREAD

**Issue by durera** [ibm-mas/ansible-devops#354]
See the implementations in every other role as a guide (e.g. mongodb, kafka, db2 to name but three) ... providing a storage class should be optional, and when not provided we will try to use one of the "known good options".

**Comment by alequint** [comment]
This is already covered in my PR: https://github.com/ibm-mas/ansible-devops/pull/351/files#diff-2a97dd3c613317c791b0928568e5feb59eb638be66852968b7c662a00d7a724cR35

**Comment by durera** [comment]
Work has already been completed, closing the issue.
