### ISSUE TITLE
Ansible installation failed with error "Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-y5je6vvp/cryptography/"

### ISSUE THREAD

**Issue by jjiraud** [ibm-mas/ansible-devops#368]
After installing python 3.9, attempting installing ansible using comand the following command line failed:  

python3 -m pip install ansible junit_xml pymongo xmljson kubernetes==12.0.1 openshift==0.12.1

Error: 

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-y5je6vvp/cryptography/

Any idea what causes the error?

Regards,
Jean

**Comment by jjiraud** [comment]
I have solved the issue by uninstalling python-3.9.10 and installed python-3.9.6.

Thanks,
Jean E.

**Comment by durera** [comment]
Sorry, no idea what would have caused that ... going beyond my knowledge of Python internals on that one.  Glad you got to the bottom of it though :)
