### ISSUE TITLE
Error msg: "grafana_instance_storage_class must be defined

### ISSUE THREAD

**Issue by jjiraud** [ibm-mas/ansible-devops#370]
Hello,

I have attempted deploying MAS core using"ansible-playbook ibm.mas_devops.oneclick_core" on an OCP cluster provisioned on AWS pub. cloud. Deployment failed with 3 main errors: 1) ....prometheus_storage_class must be defined, 2) prometheus_storage_class must be defined, and 3) ...grafana_instance_storage_class must be defined. I have set the env variable(...=gp2-csi) for error 1 and 2 and 3, however it keeps failing and returned the same grafana error: grafana_instance_storage_class must be defined

fatal: [localhost]: FAILED! => {
    "assertion": "grafana_instance_storage_class is defined and grafana_instance_storage_class != \"\"",
    "changed": false,
    "evaluated_to": false,
    "msg": "grafana_instance_storage_class must be defined

Any idea?

Thanks,
Jean

**Comment by WebDeveloper02** [comment]
Hello @jjiraud 

I was able to move forward at this stage. The logs for oneclick_core shows - 

TASK [ibm.mas_devops.cluster_monitoring : Default Grafana Instance Storage if not set by user] ********************************************************************************************************************************
task path: /home/samvid/.ansible/collections/ansible_collections/ibm/mas_devops/roles/cluster_monitoring/tasks/determine-storage-classes.yml:64
ok: [localhost] => {
    "ansible_facts": {
        "grafana_instance_storage_class": "ibmc-block-gold"
    },
    "changed": false
}

**Comment by durera** [comment]
I'm going to tidy up the documentation for the one-click playbook to make it clearer what needs to be done when using non-standard storage classes.
