### ISSUE TITLE
Check if catalogs are ready before finish ibm_catalogs role

### ISSUE THREAD

**Issue by alequint** [ibm-mas/ansible-devops#380]
`ibm_catalogs` role does not guarantee catalogs are ready before finishes, which may cause problems in tasks depending on it that run right after that in a pipeline, such as `appconnect`.

Internal discussion about it and associated problem: https://ibm-watson-iot.slack.com/archives/C031Q7W21FZ/p1656607694409549

**Comment by durera** [comment]
This has already been done, but the work was not linked back to this issue :(
