### ISSUE TITLE
list of requirements

### ISSUE THREAD

**Issue by aroute** [ibm-mas/ansible-devops#382]
Please add this to the list of requirements (here: https://ibm-mas.github.io/ansible-devops/#install-python-ansible).

```
python -m pip install jmespath
```

Otherwise, we are getting this error.

```
TASK [ibm.mas_devops.db2 : Lookup db2 instance Pod in db2u namespace] *******************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The conditional check 'db2_manage_pod.resources | json_query('[*].status.conditions[?type==`ContainersReady`][].status') | select ('match','True') | list | length == 1' failed. The error was: You need to install \"jmespath\" prior to running json_query filter"}
```

In addition, the storage size is in `Gi` and not `Gb` (here: https://ibm-mas.github.io/ansible-devops/roles/db2/). 

Thanks.

**Comment by durera** [comment]
This was fixed in #393 but the work wasn't linked back to this issue so this didn't get automatically close :(
