### ISSUE TITLE
Make tablespace sizings configurable via environment variables

### ISSUE THREAD

**Issue by alequint** [ibm-mas/ansible-devops#387]
Working in SNO (Single Node cluster) or in a cluter with limited storage, we need to be able to define the tablespace sizing used in `suite_db1_setup_for_manage`. As example, it should replace the `5000 M` used before:

```
db2 CREATE REGULAR TABLESPACE MAXINDEX PAGESIZE 32 K MANAGED BY AUTOMATIC STORAGE INITIALSIZE 5000 M BUFFERPOOL MAXBUFPOOL
```

**Comment by caroazad** [comment]
@alequint Should there be a default value? if so, what is the value to use?

**Comment by alequint** [comment]
@caroazad the default is what we use today... the goal is that those vars (for this and other issues created today) are all optional and when not informed the pipeline should work exactly as it works today
