### ISSUE TITLE
Make MongoDB number of members configurable

### ISSUE THREAD

**Issue by alequint** [ibm-mas/ansible-devops#389]
In SNO clusters, mongodb deployment must be modified to have just one member. So number of members must be configurable via enviornment variables to simplify that.

**Comment by caroazad** [comment]
@alequint Is this the replica members? If it is it already has an environment variable MONGODB_REPLICAS

**Comment by durera** [comment]
This was delivered in #384 but the work was not linked to this issue, but this is done now.
