### ISSUE TITLE
Role cluster_monitoring gives error during execution of oneclick_core playbook.

### ISSUE THREAD

**Issue by WebDeveloper02** [ibm-mas/ansible-devops#392]
Hello,

Here is the stack trace. I am using Ubuntu 20.04 linux subsytem and python3.10.

TASK [ibm.mas_devops.cluster_monitoring : Set storage class and retention period for Prometheus logs and turn on user workload monitoring] ************************************************************************************
task path: /home/installuser/.ansible/collections/ansible_collections/ibm/mas_devops/roles/cluster_monitoring/tasks/main.yml:11
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: installuser
<127.0.0.1> EXEC /bin/sh -c 'echo ~installuser && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/installuser/.ansible/tmp `"&& mkdir "` echo /home/installuser/.ansible/tmp/ansible-tmp-1657389232.257914-18879-127911780998570 `" && echo ansible-tmp-1657389232.257914-18879-127911780998570="` echo /home/installuser/.ansible/tmp/ansible-tmp-1657389232.257914-18879-127911780998570 `" ) && sleep 0'
Using module file /home/installuser/.ansible/collections/ansible_collections/kubernetes/core/plugins/modules/k8s.py
<127.0.0.1> PUT /home/installuser/.ansible/tmp/ansible-local-18202w49rlv85/tmpg0edcxlt TO /home/installuser/.ansible/tmp/ansible-tmp-1657389232.257914-18879-127911780998570/AnsiballZ_k8s.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/installuser/.ansible/tmp/ansible-tmp-1657389232.257914-18879-127911780998570/ /home/installuser/.ansible/tmp/ansible-tmp-1657389232.257914-18879-127911780998570/AnsiballZ_k8s.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /home/installuser/.ansible/tmp/ansible-tmp-1657389232.257914-18879-127911780998570/AnsiballZ_k8s.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/installuser/.ansible/tmp/ansible-tmp-1657389232.257914-18879-127911780998570/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/installuser/.ansible/tmp/ansible-tmp-1657389232.257914-18879-127911780998570/AnsiballZ_k8s.py", line 107, in <module>
    _ansiballz_main()
  File "/home/installuser/.ansible/tmp/ansible-tmp-1657389232.257914-18879-127911780998570/AnsiballZ_k8s.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/installuser/.ansible/tmp/ansible-tmp-1657389232.257914-18879-127911780998570/AnsiballZ_k8s.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.kubernetes.core.plugins.modules.k8s', init_globals=dict(_module_fqn='ansible_collections.kubernetes.core.plugins.modules.k8s', _modlib_path=modlib_path),
  File "/usr/lib/python3.10/runpy.py", line 224, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_kubernetes.core.k8s_payload_38_sr2kf/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s.py", line 486, in <module>
  File "/tmp/ansible_kubernetes.core.k8s_payload_38_sr2kf/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s.py", line 482, in main
  File "/tmp/ansible_kubernetes.core.k8s_payload_38_sr2kf/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s.py", line 458, in execute_module
  File "/tmp/ansible_kubernetes.core.k8s_payload_38_sr2kf/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/common.py", line 741, in set_resource_definitions
  File "/tmp/ansible_kubernetes.core.k8s_payload_38_sr2kf/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/common.py", line 741, in <listcomp>
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 130, in load_all
    yield loader.get_data()
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 45, in get_data
    return self.construct_document(self.get_node())
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 27, in get_node
    return self.compose_document()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 115, in check_token
    while self.need_more_tokens():
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 291, in stale_possible_simple_keys
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
  in "<unicode string>", line 16, column 1:
    "
    ^
could not find expected ':'
  in "<unicode string>", line 19, column 25:
                  storage: "300Gi"
                            ^
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "definition": "---\napiVersion: v1\nkind: ConfigMap\ndata:\n  config.yaml: |\n    prometheusOperator:\n      baseImage: quay.io/coreos/prometheus-operator\n      prometheusConfigReloaderBaseImage: quay.io/coreos/prometheus-config-reloader\n      configReloaderBaseImage: quay.io/coreos/configmap-reload\n    prometheusK8s:\n      retention: \"15d\"\n      baseImage: openshift/prometheus\n      volumeClaimTemplate:\n        spec:\n          storageClassName: \"ibmc-block-gold\r\"\n          resources:\n            requests:\n              storage: \"300Gi\"\n    alertmanagerMain:\n      baseImage: openshift/prometheus-alertmanager\n      volumeClaimTemplate:\n        spec:\n          storageClassName: \"ibmc-file-gold-gid\r\"\n          resources:\n            requests:\n              storage: \"20Gi\"\n    enableUserWorkload: true\n    nodeExporter:\n      baseImage: openshift/prometheus-node-exporter\n    kubeRbacProxy:\n      baseImage: quay.io/coreos/kube-rbac-proxy\n    kubeStateMetrics:\n      baseImage: quay.io/coreos/kube-state-metrics\n    grafana:\n      baseImage: grafana/grafana\n    auth:\n      baseImage: openshift/oauth-proxy\nmetadata:\n  name: cluster-monitoring-config\n  namespace: openshift-monitoring\n---\napiVersion: v1\nkind: ConfigMap\ndata:\n  config.yaml: |\n    prometheus:\n      retention: \"15d\"\n      volumeClaimTemplate:\n        spec:\n          storageClassName: \"ibmc-block-gold\r\"\n          resources:\n            requests:\n              storage: \"300Gi\"\nmetadata:\n  name: user-workload-monitoring-config\n  namespace: openshift-user-workload-monitoring",
        "module_args": {
            "definition": "---\napiVersion: v1\nkind: ConfigMap\ndata:\n  config.yaml: |\n    prometheusOperator:\n      baseImage: quay.io/coreos/prometheus-operator\n      prometheusConfigReloaderBaseImage: quay.io/coreos/prometheus-config-reloader\n      configReloaderBaseImage: quay.io/coreos/configmap-reload\n    prometheusK8s:\n      retention: \"15d\"\n      baseImage: openshift/prometheus\n      volumeClaimTemplate:\n        spec:\n          storageClassName: \"ibmc-block-gold\r\"\n          resources:\n            requests:\n              storage: \"300Gi\"\n    alertmanagerMain:\n      baseImage: openshift/prometheus-alertmanager\n      volumeClaimTemplate:\n        spec:\n          storageClassName: \"ibmc-file-gold-gid\r\"\n          resources:\n            requests:\n              storage: \"20Gi\"\n    enableUserWorkload: true\n    nodeExporter:\n      baseImage: openshift/prometheus-node-exporter\n    kubeRbacProxy:\n      baseImage: quay.io/coreos/kube-rbac-proxy\n    kubeStateMetrics:\n      baseImage: quay.io/coreos/kube-state-metrics\n    grafana:\n      baseImage: grafana/grafana\n    auth:\n      baseImage: openshift/oauth-proxy\nmetadata:\n  name: cluster-monitoring-config\n  namespace: openshift-monitoring\n---\napiVersion: v1\nkind: ConfigMap\ndata:\n  config.yaml: |\n    prometheus:\n      retention: \"15d\"\n      volumeClaimTemplate:\n        spec:\n          storageClassName: \"ibmc-block-gold\r\"\n          resources:\n            requests:\n              storage: \"300Gi\"\nmetadata:\n  name: user-workload-monitoring-config\n  namespace: openshift-user-workload-monitoring",
            "wait": true,
            "wait_timeout": 120
        },
        "wait": true,
        "wait_timeout": 120
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/installuser/.ansible/tmp/ansible-tmp-1657389232.257914-18879-127911780998570/AnsiballZ_k8s.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/installuser/.ansible/tmp/ansible-tmp-1657389232.257914-18879-127911780998570/AnsiballZ_k8s.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/installuser/.ansible/tmp/ansible-tmp-1657389232.257914-18879-127911780998570/AnsiballZ_k8s.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.kubernetes.core.plugins.modules.k8s', init_globals=dict(_module_fqn='ansible_collections.kubernetes.core.plugins.modules.k8s', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.10/runpy.py\", line 224, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.10/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_kubernetes.core.k8s_payload_38_sr2kf/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s.py\", line 486, in <module>\n  File \"/tmp/ansible_kubernetes.core.k8s_payload_38_sr2kf/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s.py\", line 482, in main\n  File \"/tmp/ansible_kubernetes.core.k8s_payload_38_sr2kf/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s.py\", line 458, in execute_module\n  File \"/tmp/ansible_kubernetes.core.k8s_payload_38_sr2kf/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/common.py\", line 741, in set_resource_definitions\n  File \"/tmp/ansible_kubernetes.core.k8s_payload_38_sr2kf/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/common.py\", line 741, in <listcomp>\n  File \"/usr/lib/python3/dist-packages/yaml/__init__.py\", line 130, in load_all\n    yield loader.get_data()\n  File \"/usr/lib/python3/dist-packages/yaml/constructor.py\", line 45, in get_data\n    return self.construct_document(self.get_node())\n  File \"/usr/lib/python3/dist-packages/yaml/composer.py\", line 27, in get_node\n    return self.compose_document()\n  File \"/usr/lib/python3/dist-packages/yaml/composer.py\", line 55, in compose_document\n    node = self.compose_node(None, None)\n  File \"/usr/lib/python3/dist-packages/yaml/composer.py\", line 84, in compose_node\n    node = self.compose_mapping_node(anchor)\n  File \"/usr/lib/python3/dist-packages/yaml/composer.py\", line 133, in compose_mapping_node\n    item_value = self.compose_node(node, item_key)\n  File \"/usr/lib/python3/dist-packages/yaml/composer.py\", line 84, in compose_node\n    node = self.compose_mapping_node(anchor)\n  File \"/usr/lib/python3/dist-packages/yaml/composer.py\", line 127, in compose_mapping_node\n    while not self.check_event(MappingEndEvent):\n  File \"/usr/lib/python3/dist-packages/yaml/parser.py\", line 98, in check_event\n    self.current_event = self.state()\n  File \"/usr/lib/python3/dist-packages/yaml/parser.py\", line 428, in parse_block_mapping_key\n    if self.check_token(KeyToken):\n  File \"/usr/lib/python3/dist-packages/yaml/scanner.py\", line 115, in check_token\n    while self.need_more_tokens():\n  File \"/usr/lib/python3/dist-packages/yaml/scanner.py\", line 152, in need_more_tokens\n    self.stale_possible_simple_keys()\n  File \"/usr/lib/python3/dist-packages/yaml/scanner.py\", line 291, in stale_possible_simple_keys\n    raise ScannerError(\"while scanning a simple key\", key.mark,\nyaml.scanner.ScannerError: while scanning a simple key\n  in \"<unicode string>\", line 16, column 1:\n    \"\n    ^\ncould not find expected ':'\n  in \"<unicode string>\", line 19, column 25:\n                  storage: \"300Gi\"\n                            ^\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

NO MORE HOSTS LEFT ************************************************************************************************************************************************************************************************************

PLAY RECAP ********************************************************************************************************************************************************************************************************************
localhost                  : ok=41   changed=0    unreachable=0    failed=1    skipped=11   rescued=0    ignored=0

**Comment by durera** [comment]
We don't have any testing/official support for Python 3.10.  I'm surprised the bump from Python 3.9 to 3.10 could cause such a problem, but I'm unable to reproduce this on Python 3.9 either on WSL on my own box or inside the container image we make available.

Suggest using the afore-mentioned image we supply as a convenient way to get it running under supported environment without needing to mess around with the local Python 3.10 install

`docker run -ti -v /home/you:/home/you quay.io/ibmmas/ansible-devops:10.6.1 bash`

**Comment by durera** [comment]
To me, it looks like that YAML scanner library is defective ... I've ran the template through various YAML parsers and none of them complain, and I can't see a problem with the template myself either: https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/cluster_monitoring/templates/cluster-monitoring.yml.j2 .. Unless I'm misreading the trace, the point at which it's complaining is a simple embedded YAML string so it shouldn't even really be trying to parse that as YAML; as far as it's concerned it should just be a multi-line string that could be any content.

```
File "/usr/lib/python3/dist-packages/yaml/parser.py", line 98, in check_event
self.current_event = self.state()
File "/usr/lib/python3/dist-packages/yaml/parser.py", line 428, in parse_block_mapping_key
if self.check_token(KeyToken):
File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 115, in check_token
while self.need_more_tokens():
File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 152, in need_more_tokens
self.stale_possible_simple_keys()
File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 291, in stale_possible_simple_keys
raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
in "", line 16, column 1:
"
^
could not find expected ':'
in "", line 19, column 25:
storage: "300Gi"
^
```

The template is pretty straightforward YAML wise:

```
---
apiVersion: v1
kind: ConfigMap
data:
  config.yaml: |
    <long multi-line string>
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
---
apiVersion: v1
kind: ConfigMap
data:
  config.yaml: |
    <long multi-line string>
metadata:
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
```

**Comment by WebDeveloper02** [comment]
Hi,
Many thanks for the reply and suggestions. I will try to run via docker and update the case.

**Comment by WebDeveloper02** [comment]
Hi @durera 
The playbook ran fine until this stage - 

TASK [ibm.mas_devops.suite_verify : Wait for Suite to be ready (60s delay)]
Wednesday 13 July 2022  08:06:45 +0000 (0:00:00.037)       0:02:05.933 ********
FAILED - RETRYING: [localhost]: Wait for Suite to be ready (60s delay) (30 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite to be ready (60s delay) (29 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite to be ready (60s delay) (28 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite to be ready (60s delay) (27 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite to be ready (60s delay) (26 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite to be ready (60s delay) (25 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite to be ready (60s delay) (24 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite to be ready (60s delay) (23 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite to be ready (60s delay) (22 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite to be ready (60s delay) (21 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite to be ready (60s delay) (20 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite to be ready (60s delay) (19 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite to be ready (60s delay) (18 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite to be ready (60s delay) (17 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite to be ready (60s delay) (16 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite to be ready (60s delay) (15 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite to be ready (60s delay) (14 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite to be ready (60s delay) (13 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite to be ready (60s delay) (12 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite to be ready (60s delay) (11 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite to be ready (60s delay) (10 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite to be ready (60s delay) (9 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite to be ready (60s delay) (8 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite to be ready (60s delay) (7 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite to be ready (60s delay) (6 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite to be ready (60s delay) (5 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite to be ready (60s delay) (4 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite to be ready (60s delay) (3 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite to be ready (60s delay) (2 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite to be ready (60s delay) (1 retries left).
fatal: [localhost]: FAILED! => {"api_found": true, "attempts": 30, "changed": false, "resources": [{"apiVersion": "core.mas.ibm.com/v1", "kind": "Suite", "metadata": {"creationTimestamp": "2022-07-13T06:51:08Z", "finalizers": ["core.mas.ibm.com/finalizer"], "generation": 1, "labels": {"mas.ibm.com/instanceId": "mas8"}, "managedFields": [{"apiVersion": "core.mas.ibm.com/v1", "fieldsType": "FieldsV1", "fieldsV1": {"f:metadata": {"f:finalizers": {".": {}, "v:\"core.mas.ibm.com/finalizer\"": {}}}, "f:status": {".": {}, "f:conditions": {}}}, "manager": "ansible-operator", "operation": "Update", "time": "2022-07-13T06:52:24Z"}, {"apiVersion": "core.mas.ibm.com/v1", "fieldsType": "FieldsV1", "fieldsV1": {"f:metadata": {"f:labels": {".": {}, "f:mas.ibm.com/instanceId": {}}}, "f:spec": {".": {}, "f:certManagerNamespace": {}, "f:domain": {}, "f:license": {".": {}, "f:accept": {}}, "f:settings": {".": {}, "f:icr": {".": {}, "f:cp": {}, "f:cpopen": {}}}}, "f:status": {"f:cert-manager": {}}}, "manager": "OpenAPI-Generator", "operation": "Update", "time": "2022-07-13T06:52:59Z"}], "name": "mas8", "namespace": "mas-mas8-core", "resourceVersion": "9041286", "uid": "494eba61-dcf7-42ed-af71-d4132c4b4b4d"}, "spec": {"certManagerNamespace": "ibm-common-services", "domain": "sandbox.nexmas.com", "license": {"accept": true}, "settings": {"icr": {"cp": "cp.icr.io/cp", "cpopen": "icr.io/cpopen"}}}, "status": {"cert-manager": {"external": {"duration": "8760h0m0s", "name": "mas-mas8-core-public-issuer", "renewBefore": "720h0m0s"}, "internal": {"duration": "175200h0m0s", "name": "mas-mas8-core-internal-issuer", "renewBefore": "2160h0m0s"}}, "conditions": [{"lastTransitionTime": "2022-07-13T06:53:33Z", "message": "", "reason": "", "status": "False", "type": "Successful"}, {"lastTransitionTime": "2022-07-13T08:28:17Z", "message": "Running reconciliation", "reason": "Running", "status": "False", "type": "Running"}, {"ansibleResult": {"changed": 0, "completion": "2022-07-13T08:29:25.675583", "failures": 1, "ok": 18, "skipped": 7}, "lastTransitionTime": "2022-07-13T08:29:25Z", "message": "Failed to apply object: b'Unable to determine if virtual resource\\n'", "reason": "Failed", "status": "True", "type": "Failure"}]}}]}

NO MORE HOSTS LEFT ******************************************************************************************************************************************************************

PLAY RECAP **************************************************************************************************************************************************************************
localhost                  : ok=193  changed=2    unreachable=0    failed=1    skipped=36   rescued=0    ignored=0

So, I will create a new issue. Thank you.
