### ISSUE TITLE
Support separate CIS_APIKEY variable

### ISSUE THREAD

**Issue by durera** [ibm-mas/ansible-devops#4]
See https://ibm-mas.github.io/ansible-devops/roles/suite_dns/

> We need to support a seperate cis_apikey property, because the API key provided will be stored in a secret in the cluster used by the webhook to create challenge request files in your DNS. We should support the ability to set the API key used here seperate from the main IBMCloud API key used elsewhere so that it can be restricted to only the permissions required by CIS.

Update (@alequint )

### Detailed Overview

- `suite_dns` role, today, uses IBM Cloud API Key as we can see [here](https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/suite_dns/tasks/main.yml#L8), which is the same API Key used for different purposes (the same one set in the correspondent playbook that uses the role previously referred, [here](https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/playbooks/mas/install-suite.yml#L39))
- This apikey, as stated above, is stored in a secret and will be used by the webhook (external code adapted by us), to interact with CIS (Cloud Internet Services, a service that lives in our IBM Cloud responsible by our Domain and DNS).
- Having said that, for security reasons, we do not want to use a powerful/admin Api Key, we need to use another one wit much less permissions (i.e. capable to interact with CIS and only that). Therefore, instead of `suite_dns` role uses the ibmcloud_apikey, it should use another property, which will contain a more restricted api key.

### How to test
- Create a new api key with restricted permissions and use it in the new playbook attribute `cis_apikey`
- API Keys are created in IBM Cloud account in Manage > Access (IAM)
- Restriction to work only with CIS service can be made through Service Ids (we need to have one for the CIS, associated with api key previously created)

**Comment by bwbudak** [comment]
Did a little investigation on this since this is a very high level description.   Not being familiar with the MAS installation trying to understand this better.   It appears that this is related to playbook changes which would utilize this new environment variable:   CIS_APIKEY    ??

**Comment by bwbudak** [comment]
Additional information needed:

- How to test changes?  
- Is there an environment to test against?  
- How do I set up the Environment variables?  If testing via CLI then can I utilize the **export** command?
- Is this specifically associated to suite_dns ?
- Looks like there are multiple locations where the code needs to be modified to the new API Key:
  * ibm/mas_devops/plugins/modules/cis_dns_entries.py
  * ibm/mas_devops/roles/suite_dns/tasks/providers/cis/dns_mgmt.yml
- How to confirm that the new API key if set in a secret is extracted?

**Comment by durera** [comment]
There's some basic info here to help get people started: https://github.com/ibm-mas/ansible-devops/blob/master/CONTRIBUTING.md

- How to test: Run whatever roles/playbooks you change to verify the changes you made
- Environments: There's no specific environment available for this project, will need to provision one, or hop on an existing OCP cluster comewhere if you are not working on ocp provision/deprovision logic
- Env vars.  Yeah, use `export VAR_NAME=whatever` per the docs (e.g. https://ibm-mas.github.io/ansible-devops/playbooks/dependencies/#install-amq-streams)

Yes, this is specific to suite_dns ... we want to create a completely seperate variable (cis_apikey) and env var (CIS_APIKEY) that can hold an API key with only the reduced permission needed by the CIS webhook.

- no files inside roles/suite_dns should reference a variable named `ibmcloud_apikey` .. only `cis_apikey`
- playbooks should set cis_apikey (CIS_APIKEY env) seperate from ibmcloud_apikey (IBMCLOUD_APIKEY env)
- if a user really wants to use the full power ibmcloud admin key for CIS, they can set IBMCLOUD_APIKEY  and CIS_APIKEY  to the same thing, but we wouldn't recommend this

This would should include all the doc updates for this role as well.
