### ISSUE TITLE
Need assistance for MAS and Manage deployment - OCP storage class requirements for AWS

### ISSUE THREAD

**Issue by jjiraud** [ibm-mas/ansible-devops#405]
Hello Ansible-Devops team,

Hope all of you are well, safe, and enjoying the beautiful weather !

I have my OCP cluster provisioned on AWS public cloud, I noticed the cluster only has 2 storage classes(gp2 default and gp2-csi), I had successfully deployed  MAS using ansible, however managed failed. I believe the failure is due to the fact that gp2-csi storage class is not compatible with db2 warehouse or CP4D(please correct me if I am wrong). I will post the failure logs later(....).

I had created an EFS file system on AWS and tried to mount it unsuccessfully, which makes sense to me since OCP is provisioned on RHCOS.

Please guide me to understand how to bring the required storage class(es) to the cluster.

Best regards,
Jean

**Comment by durera** [comment]
MAS (and it's dependencies) require both a RWO and RWX storage class, out of the box ROSA on AWS only provides the former.  

@prasanthgelli1 is working on built-in support for ROSA (issue #361) that will include setup of the necessary EFS-based storageclasses.  You can follow that issue for updates.

Ultimately it boils down to needing to work through the steps documented here: https://docs.openshift.com/rosa/storage/persistent_storage/osd-persistent-storage-aws.html

**Comment by jjiraud** [comment]
Hi David,

Thanks for your feedback.

I'd like to point out that my OCP cluster was provisioned using IPI ( not ROSA), will the procedure (#361<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fibm-mas%2Fansible-devops%2Fissues%2F361&data=05%7C01%7Cjean.jiraud%40createch.ca%7Cd6769bab8cb14db70f9308da663ee6c1%7C739204c58634413b9bc965a78fa9c5d0%7C0%7C0%7C637934717594841243%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=k3xtfreqwMPvcG93orInaYV%2FIm0%2FHzc4DFGHKUzNutw%3D&reserved=0>, once it's available) be used to set up the required storage classes for non ROSA cluster as well?


Same question for the Red Hat procedure (https://docs.openshift.com/rosa/storage/persistent_storage/osd-persistent-storage-aws.html<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.openshift.com%2Frosa%2Fstorage%2Fpersistent_storage%2Fosd-persistent-storage-aws.html&data=05%7C01%7Cjean.jiraud%40createch.ca%7Cd6769bab8cb14db70f9308da663ee6c1%7C739204c58634413b9bc965a78fa9c5d0%7C0%7C0%7C637934717594841243%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=440ogjHY%2FsLTpA3%2FEVCboyiWZcyKPTaRyx8dbZRobkE%3D&reserved=0>); Can I use this procedure to  set up the storage class for non ROSA cluster, like mine?
Regards,
Jean






[Une image contenant texte, signe  Description g?n?r?e automatiquement]Jean Erold Jiraud
Maximo Support Consultant |Consultant Soutien Maximo
Enterprise Asset Management | Gestion des Actifs de l'Entreprise
           T.: 905-777-5735 | C.: 905-975-3603
           ***@***.******@***.***>  / ***@***.******@***.***>

**Comment by jjiraud** [comment]
Thanks David,

I have configured the required storage classes successfully.

Regards,
Jean
