### ISSUE TITLE
Attachments(doclinks) configuration in MAS

### ISSUE THREAD

**Issue by jjiraud** [ibm-mas/ansible-devops#416]
Hello team,

Does any one has experience in configuring doclinks(attachments) in MAS? Every time I attempt the configuration manage activation failed, I can see in OCP dashboard maxinst created a pvc which remains in a pending state. 

I am using AWS efs volume with storage class read write many access mode. 

Question: should the PV be created manually and pass it to MAS or maxinst pod will create the pvc and bound it to a pv automatically?

Regards,
Jean

**Comment by aroute** [comment]
This [documentation](https://www.ibm.com/docs/en/SSLPL8_8.3.0/pdf/maximo-manage-8.3.0-documentation.pdf) should help. It has a section on how to configure doclinks for MAS.
