### ISSUE TITLE
Can UDS be installed in a separate namespace than ibm-common-services? what about multiple instances?

### ISSUE THREAD

**Issue by jperera-interloc** [ibm-mas/ansible-devops#419]
With BAS apparently it supports running in different namespaces in case we want to have more than one instance running in the same cluster. 

However, looking at the scripts I could not find provisions to run UDS in a namespace other than ibm-common-services. 

Is installing UDS in another namespace possible? I would like to avoid using ibm-common-services if possible and even when installing a single copy in the RHOS cluster I would like it to be installed in a segregated namespace.

Thanks in advance,

**Comment by durera** [comment]
I spoke with the UDS team, this is a limitation of UDS I'm afraid; they do not support install of UDS in multiple namespaces, or indeed any namespace other than `ibm-common-services`.

**Comment by jperera-interloc** [comment]
Thanks, acknowledged.
