### ISSUE TITLE
Uninstall MAS

### ISSUE THREAD

**Issue by jjiraud** [ibm-mas/ansible-devops#422]
Hello,

Is there a script to uninstall MAS from OCP (no matter where it's provisioned)?

Thanks,
Jean

**Comment by vincent-pli** [comment]
Same question, any comments?

**Comment by johnnykp** [comment]
Not yet, as I know its on the roadmap, actually Im uninstalling by deleting the project at all on openshift, sometimes the project stays under terminating status and you have to force delete

**Comment by durera** [comment]
Refer to https://github.com/ibm-mas/ansible-devops/issues/429, which has some information on the proposed uninstall pipeline & playbook which will eventually provide the ability to completely reset a cluster to it's starting start (assuming the install was performed with this collection)
