### ISSUE TITLE
Manage activation failed due to ManageWorkspace failure

### ISSUE THREAD

**Issue by jjiraud** [ibm-mas/ansible-devops#424]
I have an OCP cluster on AWS with OCS storage classes, MAS core deployment is succeed while manage activation failed. maxinst pod will never get created even after more than 4 hours.

When I checked the status of "ManageWorkspace" instance(Installed Operators → IBM Maximo Manage → All instances) I can could see status condition: Failure...with the following error details:

" The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'dbSchema'
The error appears to be in '/opt/ansible/roles/workspace/tasks/deploy-cr.yml': line 11, column 3, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
... "

My concern is which pod contains this path displayed in the error message: 
"/opt/ansible/roles/workspace/tasks/deploy-cr.yml"

Regards,
Jean

**Comment by jroldj** [comment]
Issue fixed my updated the mentioned file in pod: ....entitymgr-ws....


Regards,
Jean

**Comment by durera** [comment]
What version of Manage were you deploying?  Will pass this on the application team to ensure they fix this defect in their operator.

**Comment by jjiraud** [comment]
MAS 8.7

**Comment by andrercm** [comment]
This issue was identified as product issue in MAS 8.7 rather than something to be done in the automation, will close this issue.
