### ISSUE TITLE
MAS deployment with cloudflare dns - CWOAU0062E: The OAuth service provider could not redirect the request because the redirect URI was not valid

### ISSUE THREAD

**Issue by jroldj** [ibm-mas/ansible-devops#425]
I have deployed MAS with a cloudflare dns, the browser returned the following error while accessing the Admin Dashboard:

CWOAU0062E: The OAuth service provider could not redirect the request because the redirect URI was not valid. Contact your system administrator to resolve the problem.

Any idea?

Regards,
Jean

**Comment by whitfiea** [comment]
@jroldj Did you resolve this issue? Sounds like it could be a DNS issue with the redirect URI not being invalid at the time?

**Comment by andrercm** [comment]
No response since August, 2022. Will close it.
