### ISSUE TITLE
Problem running cp4d role

### ISSUE THREAD

**Issue by sagar-nexer** [ibm-mas/ansible-devops#426]
reference to below devops library we are installing cp4d instance and all pre-requisite are fulfilled. 

**https://ibm-mas.github.io/ansible-devops/roles/cp4d/**

nexer@DESKTOP-8A0T8M5:~$ oc -n ibm-cpd-operators get deployments
NAME                            READY   UP-TO-DATE   AVAILABLE   AGE
cpd-platform-operator-manager   1/1     1            1           11m
ibm-common-service-operator     1/1     1            1           11m
ibm-namespace-scope-operator    1/1     1            1           11m

nexer@DESKTOP-8A0T8M5:~$ oc -n ibm-common-services get deployments
NAME                                         READY   UP-TO-DATE   AVAILABLE   AGE
cert-manager-cainjector                      1/1     1            1           64d
cert-manager-controller                      1/1     1            1           64d
cert-manager-webhook                         1/1     1            1           64d
db2u-operator-manager                        1/1     1            1           47d
ibm-cert-manager-operator                    1/1     1            1           64d
ibm-common-service-operator                  1/1     1            1           16m
ibm-common-service-webhook                   1/1     1            1           70d
ibm-cpd-scheduling-operator                  1/1     1            1           67d
ibm-cpd-wml-operator                         1/1     1            1           67d
ibm-cpd-ws-operator                          1/1     1            1           67d
ibm-db2wh-cp4d-operator-controller-manager   1/1     1            1           67d
ibm-dmc-controller-manager                   1/1     1            1           67d
ibm-namespace-scope-operator                 1/1     1            1           70d
ibm-zen-operator                             1/1     1            1           62d
meta-api-deploy                              1/1     1            1           67d
operand-deployment-lifecycle-manager         1/1     1            1           70d
secretshare                                  1/1     1            1           70d
zen-database-core                            0/1     1            0           47d
zen-databases                                0/2     0            0           47d
zen-watcher                                  0/1     0            0           62d 

TASK [ibm.mas_devops.cp4d : install-cp4d : Wait for controlPlaneStatus to be 'Completed' (2m delay)] **************************************************************************************************************
task path: /opt/app-root/lib64/python3.9/site-packages/ansible_collections/ibm/mas_devops/roles/cp4d/tasks/install-cp4d.yml:69
Wednesday 03 August 2022  09:26:16 +0000 (0:00:01.600)       0:02:27.170 ******
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1659518776.7388113-4039-186997473928453 `" && echo ansible-tmp-1659518776.7388113-4039-186997473928453="` echo /root/.ansible/tmp/ansible-tmp-1659518776.7388113-4039-186997473928453 `" ) && sleep 0'
Using module file /opt/app-root/lib64/python3.9/site-packages/ansible_collections/kubernetes/core/plugins/modules/k8s_info.py
<127.0.0.1> PUT /opt/app-root/src/.ansible/tmp/ansible-local-371635dch_c5/tmpc5tzj9rs TO /root/.ansible/tmp/ansible-tmp-1659518776.7388113-4039-186997473928453/AnsiballZ_k8s_info.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1659518776.7388113-4039-186997473928453/ /root/.ansible/tmp/ansible-tmp-1659518776.7388113-4039-186997473928453/AnsiballZ_k8s_info.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/opt/app-root/bin/python3 /root/.ansible/tmp/ansible-tmp-1659518776.7388113-4039-186997473928453/AnsiballZ_k8s_info.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1659518776.7388113-4039-186997473928453/ > /dev/null 2>&1 && sleep 0'
FAILED - RETRYING: [localhost]: install-cp4d : Wait for controlPlaneStatus to be 'Completed' (2m delay) (60 retries left).Result was: {
    "api_found": true,
    "attempts": 1,
    "changed": false,
    "invocation": {
        "module_args": {
            "api_key": null,
            "api_version": "cpd.ibm.com/v1",
            "ca_cert": null,
            "client_cert": null,
            "client_key": null,
            "context": null,
            "field_selectors": [],
            "host": null,
            "kind": "Ibmcpd",
            "kubeconfig": null,
            "label_selectors": [],
            "name": "ibmcpd",
            "namespace": "ibm-cpd",
            "password": null,
            "persist_config": null,
            "proxy": null,
            "proxy_headers": null,
            "username": null,
            "validate_certs": null,
            "wait": false,
            "wait_condition": null,
            "wait_sleep": 5,
            "wait_timeout": 120
        }
    },
    "resources": [
        {
            "apiVersion": "cpd.ibm.com/v1",
            "kind": "Ibmcpd",
            "metadata": {
                "annotations": {
                    "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"cpd.ibm.com/v1\",\"kind\":\"Ibmcpd\",\"metadata\":{\"csNamespace\":\"ibm-common-services\",\"name\":\"ibmcpd\",\"namespace\":\"ibm-cpd\"},\"spec\":{\"license\":{\"accept\":true,\"license\":\"Standard\"},\"storageClass\":\"ibmc-block-gold\",\"zenCoreMetadbStorageClass\":\"ibmc-block-gold\"}}"
                },
                "creationTimestamp": "2022-08-02T10:42:39Z",
                "generation": 1,
                "managedFields": [
                    {
                        "apiVersion": "cpd.ibm.com/v1",
                        "fieldsType": "FieldsV1",
                        "fieldsV1": {
                            "f:status": {
                                ".": {},
                                "f:conditions": {}
                            }
                        },
                        "manager": "ansible-operator",
                        "operation": "Update",
                        "time": "2022-08-02T10:42:39Z"
                    },
                    {
                        "apiVersion": "cpd.ibm.com/v1",
                        "fieldsType": "FieldsV1",
                        "fieldsV1": {
                            "f:metadata": {
                                "f:annotations": {
                                    ".": {},
                                    "f:kubectl.kubernetes.io/last-applied-configuration": {}
                                }
                            },
                            "f:spec": {
                                ".": {},
                                "f:license": {
                                    ".": {},
                                    "f:accept": {},
                                    "f:license": {}
                                },
                                "f:storageClass": {},
                                "f:zenCoreMetadbStorageClass": {}
                            },
                            "f:status": {
                                "f:controlPlaneStatus": {},
                                "f:lastReconcileEnd": {},
                                "f:lastReconcileStart": {}
                            }
                        },
                        "manager": "OpenAPI-Generator",
                        "operation": "Update",
                        "time": "2022-08-02T11:25:44Z"
                    }
                ],
                "name": "ibmcpd",
                "namespace": "ibm-cpd",
                "resourceVersion": "199442923",
                "uid": "469e2cb5-5b17-4dba-a54e-03c54e33d666"
            },
            "spec": {
                "license": {
                    "accept": true,
                    "license": "Standard"
                },
                "storageClass": "ibmc-block-gold",
                "zenCoreMetadbStorageClass": "ibmc-block-gold"
            },
            "status": {
                "conditions": [
                    {
                        "lastTransitionTime": "2022-08-02T11:25:46Z",
                        "message": "",
                        "reason": "",
                        "status": "False",
                        "type": "Successful"
                    },
                    {
                        "ansibleResult": {
                            "changed": 2,
                            "completion": "2022-08-03T08:41:14.996016",
                            "failures": 1,
                            "ok": 22,
                            "skipped": 6
                        },
                        "lastTransitionTime": "2022-08-03T08:41:15Z",
                        "message": "zen has failed\nzen service installation has failed",
                        "reason": "Failed",
                        "status": "False",
                        "type": "Failure"
                    },
                    {
                        "lastTransitionTime": "2022-08-03T08:41:15Z",
                        "message": "Running reconciliation",
                        "reason": "Running",
                        "status": "True",
                        "type": "Running"
                    }
                ],
                "controlPlaneStatus": "InProgress",
                "lastReconcileEnd": "2022-08-03_08:41:12",
                "lastReconcileStart": "2022-08-03_09:25:47"
            }
        }
    ],
    "retries": 61
}

**Comment by durera** [comment]
> zen service installation has failed

Need to look at why the zenservice failed to install, there could be any number of reasons.  The install is performed by the appropriate operators. There will be a zen service operator in your ibm-common-services namespace that will (presumably) have errors indicating why it could not install Zen in the cluster.

**Comment by andrercm** [comment]
Issue flagged as product defect, will close as it's not related to ansible-devops automation.
