### ISSUE TITLE
Support cleanup roles & playbook

### ISSUE THREAD

**Issue by durera** [ibm-mas/ansible-devops#429]
We need roles and a playbook, and a new pipeline (in ibmmas/cli) to basically revert everything the install pipeline does and leave the cluster back in the same state that it started in.

- [ ] Remove MAS application workspaces 
- [ ] Remove MAS applicatons
- [ ] Remove MAS configurations
- [ ] Remove MAS workspaces
- [x] Remove MAS core
- [ ] Remove CP4D (instance and operators)
- [ ] Remove MAS dependencies
- [ ] Remove Cloud Pak Foundation services
- [ ] Remove IBM Catalog

Each step should be useable in isolation, each step should be capable of actually verifying the removal via numerous `assert` tasks.  We will not worry about backup/accidental data loss in the initial version, but eventually there should be the option to backup before running this (and be able to restore the backup obviously).

**Comment by alequint** [comment]
@andrercm assigned this to you as you start doing some generic roles capable to clean up some resources. Please leave a comment in this issue as you progress, so we keep everybody on the same page.

**Comment by andrercm** [comment]
@durera @alequint this will take considerable effort to accomplish, do we plan or need to have it done within the next few months? If
