### ISSUE TITLE
Support - After Health Install the Health App is not Active

### ISSUE THREAD

**Issue by Hans-J-Klose** [ibm-mas/ansible-devops#431]
Hi Team,
After using the Manage Application with Health... it seems that Health is installed but not Activated.  Is this expected or did something go wrong with ansbile automation?

<img width="1646" alt="image" src="https://user-images.githubusercontent.com/36713471/183473420-beaa84f4-1254-4b55-9ef1-2a75b5195670.png">

We ran the playbook with MAS_APP_ID set to `manage` first.  Then `health` second.

Our relevant MAS environment variables:
```
export MAS_APP_ID=health
export MAS_APPWS_COMPONENTS="base=latest,health=latest"
export MANAGE_AIO_FLAG=false
export MAS_APP_SETTINGS_AIO_FLAG=false
```

When we try to activate, it is missing the dependency integrations:
<img width="1656" alt="image" src="https://user-images.githubusercontent.com/36713471/183484806-e6f8415b-66c9-436e-a816-364c29e59702.png">

**Comment by andrercm** [comment]
@Hans-J-Klose I'm triaging issues in our tracker to prioritize then.
Do you still need any help with the above issue?

**Comment by Hans-J-Klose** [comment]
No longer needed.
