### ISSUE TITLE
Airgap issue with customer, need to add a waiting condition for the OperatorCondition

### ISSUE THREAD

**Issue by andrercm** [ibm-mas/ansible-devops#443]
We got an issue with a customer where this `OperatorCondition` resource takes time to show up and the overall suite-install fails in airgap env. After a while the resource gets created and we needed to rerun the pipeline which was not a good ux for customer:

https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/suite_install/tasks/install_digest_cm.yml#L12

**Comment by durera** [comment]
Fixed in https://github.com/ibm-mas/ansible-devops/pull/502
