### ISSUE TITLE
bludb should not be hardcoded

### ISSUE THREAD

**Issue by aroute** [ibm-mas/ansible-devops#460]
https://github.com/ibm-mas/ansible-devops/blob/e616ee5e678b5201390e8b1fe8466112da606add/ibm/mas_devops/roles/db2/tasks/create_ldap_user.yml#L53

The word `bludb` should be `{{ db2_dbname }}` otherwise, it does not pass when config scope is wsapp.

**Comment by andrercm** [comment]
@aroute will prioritize it so we can fix it in the upcoming releases of ansible devops
