### ISSUE TITLE
Support Safety deployment and dependencies

### ISSUE THREAD

**Issue by alequint** [ibm-mas/ansible-devops#47]
- [x] Make sure mas/install-app.yml playbook can install Safety successfully
- [ ] Make sure all dependencies of Safety are covered in this playbook (e.g. DB2 Space Extender)

**Comment by alequint** [comment]
Partially done with PR https://github.com/ibm-mas/ansible-devops/pull/51

Missing `Space Extender` - work in progress

**Comment by durera** [comment]
Merging this into #295 and closing this issue
