### ISSUE TITLE
SBO is still needed for MAS Channel 8.8.x

### ISSUE THREAD

**Issue by ekleinso** [ibm-mas/ansible-devops#472]
In the main.yml for the SBO role this states that SBO is no longer needed for MAS Channel = 8.8.x. This is not correct. 

I have been installing MAS with visualinspection and the mvi operator will fail if SBO is not installed.

# 1. Install Service Binding Operator
# -----------------------------------------------------------------------------
# Install stable channel with automatic updates if MAS 8.7+, otherwise, install preview channel locked to v0.8
# Unless MAS Channel = 8.8.x, in which case we don't need SBO anymore
- name: Define which SBO to install
  when: mas_channel != "8.8.x"
  set_fact:
    sbo_channel: "{{ 'stable' if (mas_channel not in mas_channels_old_releases and ocp_install_release != '4.6') else 'preview' }}"

- name: "Launch SBO install"
  when: mas_channel != "8.8.x"
  include_tasks: "tasks/install/{{ sbo_channel }}.yml"

**Comment by durera** [comment]
The need for SBO in Visual Inspection when using MAS 8.8 is a bug.  It has been addressed in the Visual Inspection v8.6.1 update (August 2022).  If you install MAS 8.8 you should now be able to pick up the fixed 8.6.1 release that correctly removes the dependency from Visual Inspection :+1:
