### ISSUE TITLE
A lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters

### ISSUE THREAD

**Issue by jjiraud** [ibm-mas/ansible-devops#473]
I have encountered the following issue while testing Route53 DNS integration with MAS 8.8, there is no upper case character (other than the Db2 DB name) in the mentioned "jdbc-masdev-db2u-manage-db2u.yml" yaml file, not sure what to correct in this file to make it works. Any idea?

_____________________________________________________________________________________________
failed: [localhost] (item={'path': '/home/Msuite1/ocp410/ocp410-aws-mas88/masdevconfig/jdbc-masdev-db2u-manage-db2u.yml', 'mode': '0664', 'isdir': False, 'ischr': False, 'isblk': False, 'isreg': True, 'isfifo': False, 'islnk': False, 'issock': False, 'uid': 1000, 'gid': 1000, 'size': 2348, 'inode': 67602414, 'dev': 64770, 'nlink': 1, 'atime': 1663805607.3533068, 'mtime': 1663804688.1053627, 'ctime': 1663804688.4933627, 'gr_name': 'Msuite1', 'pw_name': 'Msuite1', 'wusr': True, 'rusr': True, 'xusr': False, 'wgrp': True, 'rgrp': True, 'xgrp': False, 'woth': False, 'roth': True, 'xoth': False, 'isuid': False, 'isgid': False}) => {"ansible_loop_var": "item", "changed": false, "error": 422, "item": {"atime": 1663805607.3533068, "ctime": 1663804688.4933627, "dev": 64770, "gid": 1000, "gr_name": "Msuite1", "inode": 67602414, "isblk": false, "ischr": false, "isdir": false, "isfifo": false, "isgid": false, "islnk": false, "isreg": true, "issock": false, "isuid": false, "mode": "0664", "mtime": 1663804688.1053627, "nlink": 1, "path": "/home/Msuite1/ocp410/ocp410-aws-mas88/masdevconfig/jdbc-masdev-db2u-manage-db2u.yml", "pw_name": "Msuite1", "rgrp": true, "roth": true, "rusr": true, "size": 2348, "uid": 1000, "wgrp": true, "woth": false, "wusr": true, "xgrp": false, "xoth": false, "xusr": false}, "msg": "JdbcCfg masdev-jdbc-wsapp-masmanage-: Failed to create object: b'{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"JdbcCfg.config.mas.ibm.com \\\\\"masdev-jdbc-wsapp-masmanage-\\\\\" is invalid: metadata.name: Invalid value: \\\\\"masdev-jdbc-wsapp-masmanage-\\\\\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, \\'-\\' or \\'.\\', and must start and end with an alphanumeric character (e.g. \\'example.com\\', regex used for validation is \\'[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\\\\\\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*\\')\",\"reason\":\"Invalid\",\"details\":{\"name\":\"masdev-jdbc-wsapp-masmanage-\",\"group\":\"config.mas.ibm.com\",\"kind\":\"JdbcCfg\",\"causes\":[{\"reason\":\"FieldValueInvalid\",\"message\":\"Invalid value: \\\\\"masdev-jdbc-wsapp-masmanage-\\\\\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, \\'-\\' or \\'.\\', and must start and end with an alphanumeric character (e.g. \\'example.com\\', regex used for validation is \\'[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\\\\\\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*\\')\",\"field\":\"metadata.name\"}]},\"code\":422}\\n'", "reason": "Unprocessable Entity", "status": 422}

PLAY RECAP *************************************************************************************************************************
localhost                  : ok=184  changed=4    unreachable=0    failed=1    skipped=28   rescued=0    ignored=0   
------------------------------------------------------------------------------------------------------
Thanks,
Jean

**Comment by durera** [comment]
Closing as stale due to no follow up to @whitfiea comment above last December.
