### ISSUE TITLE
Must gather is not air gap friendly

### ISSUE THREAD

**Issue by durera** [ibm-mas/ansible-devops#478]
https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/suite_mustgather/tasks/main.yml#L36

We do not reference the mustgather image by digest, we always use the latest version, which is fine for a connected cluster, but in an airgap environment this will not work when we are trying to launch the mustgather process from inside the cluster in a tekton pipeline.

We need to reference the mustgather image by a digest, and update the ansible-airgap collection to additionally mirror the mustgather image.

**Comment by andrercm** [comment]
@durera @caroazad is that still not done? Should we work on it for the next few months? otherwise I'll set it to low priority

**Comment by durera** [comment]
I've fixed this indirectly with some work in the CLI by completely changing how must-gather works to use the CLI itself.  The must-gather roles in this collection are mostly redundant now, and will be removed in a future major version bump.
