### ISSUE TITLE
ROKS Provisioning VLAN Lookup error

### ISSUE THREAD

**Issue by hpniitty** [ibm-mas/ansible-devops#481]
Tried to run: 

[ibmmas/cli:2.3.8]~$ ansible-playbook ibm.mas_devops.ocp_roks_provision

but got the following error message, which is quite self explanatory, but more specific instructions are needed:

TASK [ibm.mas_devops.ocp_provision : roks : Lookup VLANs automatically (ibmcloud ks vlan ls --zone dal10 --output json)] *************************************
Monday 17 October 2022  12:21:19 +0000 (0:00:00.034)       0:00:14.931 ******** 
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "ibmcloud ks vlan ls --zone dal10 --output json\n", "delta": "0:00:02.118452", "end": "2022-10-17 12:21:22.208847", "msg": "non-zero return code", "rc": 1, "start": "2022-10-17 12:21:20.090395", "stderr": "FAILED\nYou do not have the correct permissions to perform this action, or the context based rules prevent the action from being completed in your current location. Ask your account administrator to give you the Viewer platform role for the cluster in IBM Cloud Identity and Access Management (IAM) and to ensure that your current IP address is permitted. Then, try again. (A0007)\n\nIncident ID: 324d82fb-f545-43da-a288-e6b36a61b953", "stderr_lines": ["FAILED", "You do not have the correct permissions to perform this action, or the context based rules prevent the action from being completed in your current location. Ask your account administrator to give you the Viewer platform role for the cluster in IBM Cloud Identity and Access Management (IAM) and to ensure that your current IP address is permitted. Then, try again. (A0007)", "", "Incident ID: 324d82fb-f545-43da-a288-e6b36a61b953"], "stdout": "", "stdout_lines": []}

NO MORE HOSTS LEFT *******************************************************************************************************************************************

PLAY RECAP ***************************************************************************************************************************************************
localhost                  : ok=14   changed=5    unreachable=0    failed=1    skipped=3    rescued=0    ignored=0   

Monday 17 October 2022  12:21:22 +0000 (0:00:02.315)       0:00:17.247 ******** 
=============================================================================== 
ibm.mas_devops.ocp_provision : roks : Login to IBM Cloud ---------------------------------------------------------------------------------------------- 5.27s
ibm.mas_devops.ocp_provision : roks : Check if cluster already exists --------------------------------------------------------------------------------- 3.61s
ibm.mas_devops.ocp_provision : roks : Lookup VLANs automatically (ibmcloud ks vlan ls --zone dal10 --output json) ------------------------------------- 2.32s
ibm.mas_devops.ocp_provision : roks : Switch to chosen resource group --------------------------------------------------------------------------------- 1.67s
ibm.mas_devops.ocp_provision : roks : Create resource group if it does not exist ---------------------------------------------------------------------- 1.66s
ibm.mas_devops.ocp_provision : roks : Check resource group exists ------------------------------------------------------------------------------------- 1.52s
Gathering Facts --------------------------------------------------------------------------------------------------------------------------------------- 0.71s
ibm.mas_devops.ocp_provision : roks : Debug information ----------------------------------------------------------------------------------------------- 0.08s
Check for required environment variables -------------------------------------------------------------------------------------------------------------- 0.05s
ibm.mas_devops.ansible_version_check : Verify minimum Ansible version is 2.10.3 ----------------------------------------------------------------------- 0.05s
ibm.mas_devops.ocp_provision : include_tasks ---------------------------------------------------------------------------------------------------------- 0.05s
ibm.mas_devops.ocp_provision : Fail if no OCP version is provided ------------------------------------------------------------------------------------- 0.04s
ibm.mas_devops.ocp_provision : roks : Debug current resource group status ----------------------------------------------------------------------------- 0.04s
ibm.mas_devops.ocp_provision : Fail if cluster name & type is not provided ---------------------------------------------------------------------------- 0.04s
ibm.mas_devops.ocp_provision : roks : Fail if ibmcloud_apikey is not provided ------------------------------------------------------------------------- 0.04s
ibm.mas_devops.ocp_provision : Fail if cluster type is not supported ---------------------------------------------------------------------------------- 0.03s
ibm.mas_devops.ocp_provision : roks : Debug current cluster status ------------------------------------------------------------------------------------ 0.03s
ibm.mas_devops.ocp_provision : Backwards compatability for 'quickburn' cluster type ------------------------------------------------------------------- 0.02s
[ibmmas/cli:2.3.8]~$

**Comment by durera** [comment]
The error back from the API call states:

> You do not have the correct permissions to perform this action, or the context based rules prevent the action from being completed in your current location. Ask your account administrator to give you the Viewer platform role for the cluster in IBM Cloud Identity and Access Management (IAM) and to ensure that your current IP address is permitted. Then, try again

It states what the problem is and what to do (this information comes directly from IBM Cloud rather than the Ansible code).  I don't think there's anything more we can do here when the user is using an API key with insufficient permissions.
