### ISSUE TITLE
Add Request size section to the MongoDB CR in ansible-devops.

### ISSUE THREAD

**Issue by sbudhira** [ibm-mas/ansible-devops#484]
We are missing request size for MongoDB CR. It is required for SNO deployment.

For example:
resources:
                limits:
                  cpu: '1'
                  memory: 1Gi
                **requests:
                  cpu: 500m
                  memory: 1Gi**

Environment variables are needed for:
requests.cpu 
requests.memory

**Comment by alequint** [comment]
@caroazad @pseemung  I have discussed that with @sbudhira yesterday and it is a pretty straightforward change. Basically we need to include the `requests` in our template here: https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/mongodb/templates/community/cr.yml#L51 and make the values configurable via environment variables

Could you take care of that change? Added both of you for a pair programming if possible
