### ISSUE TITLE
set appl heap size in setupdb.sh

### ISSUE THREAD

**Issue by tcskill** [ibm-mas/ansible-devops#497]
@durera been running into issues with manage on the application heap size.  increasing the application heap size with the following solved it, would recommend setting this in the setupdb.sh 

APPLHEAPSZ 2048 AUTOMATIC DEFERRED

**Comment by andrercm** [comment]
@tcskill we do have now support to specify heap size for DB2 instances provisioned by our automation:
https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/db2/defaults/main.yml#L30

Please refer to our db2 role readme for more details on how to use it properly:
https://github.com/ibm-mas/ansible-devops/tree/master/ibm/mas_devops/roles/db2
