### ISSUE TITLE
Database name harcoded in create_ldap_user.yml

### ISSUE THREAD

**Issue by evilADevil** [ibm-mas/ansible-devops#517]
The BLUDB database name is hardcoded to BLUDB at line 53 of the mentioned yml file.
I believe it should be instead referring to the db2_dbname variable

**Comment by aroute** [comment]
Similar https://github.com/ibm-mas/ansible-devops/issues/460

**Comment by whitfiea** [comment]
dup of https://github.com/ibm-mas/ansible-devops/issues/460
