### ISSUE TITLE
the device path of the ocs role should be customizable

### ISSUE THREAD

**Issue by hughjfchen** [ibm-mas/ansible-devops#522]
Currently, the `DevicePath` of the `ocs` role is hard coded as `/dev/vdb`, however in some situation this is not the case
(for example, it may be `/dev/sdb` in a mearmetal machine) so it should be customizable. Suggest add a variable in the 
template for this.

**Comment by andrercm** [comment]
This seems like a quick winner for our list of backlogs, i'll include it in the backlog for the next upcoming work
