### ISSUE TITLE
add support of AWS Route53 to suite_dns roles

### ISSUE THREAD

**Issue by swallacertp** [ibm-mas/ansible-devops#530]
Currently suite_dns supports CIS and Cloudflare including integration with Let's Encrypt, we need to add support for AWS Route53 as well since this is the default DNS on AWS cloud.

**Comment by jroldj** [comment]
While waiting, you might be able to use Route53 DNS to build SSL if you follow Brian Zhu's blog below:

https://community.ibm.com/community/user/asset-facilities/blogs/brian-zhu/2022/10/08/using-lets-encrypt-ssl-certificates-with-maximo-ap?CommunityKey=3d7261ae-48f7-481d-b675-a40eb407e0fd

Also, you might need to first install Cert-Manager (either manually or by using the ansible role) before proceeding with the article, etc.

Good luck!

**Comment by swallacertp** [comment]
Thanks for that info. I am looking for this to be added to the suite_dns so that is can then be used by the MAS BYOL deployments on AWS and use Let's Encrypt certificates as part of the install process.

**Comment by maulik-modi22** [comment]
@swallacertp , Is this planned for MAS 8.10 cloudformation release timeframe?

**Comment by swallacertp** [comment]
@maulik-modi22 I do not have a confirmation on this being added in the 8.10 timeframe.

**Comment by andrercm** [comment]
that was added in [ansible-devops:13.10.0](https://github.com/ibm-mas/ansible-devops/releases/tag/13.10.0)

**Comment by maulik-modi22** [comment]
@swallacertp, @NatarajBTI , @amitmangalvedkar , Does AWS BYOL Automation use this role to generate CA signed certificate so that it does not require trusting certificate or manual workaround like https://www.ibm.com/docs/en/masv-and-l/continuous-delivery?topic=installing-configuring-lets-encrypt?
