### ISSUE TITLE
Predict playbook - small change - replace the word MAS with the word IBM

### ISSUE THREAD

**Issue by aroute** [ibm-mas/ansible-devops#537]
This should be `IBM_ENTITLEMENT_KEY`.  The `MAS` has been replaced by `IBM` for the rest of the other playbooks. Please consider updating so we don't have to duplicate the same var.

https://github.com/ibm-mas/ansible-devops/blob/e0cb06e972b6745973eec5779cb7ce9a9e0d2bee/ibm/mas_devops/playbooks/oneclick_add_predict.yml#L70

**Comment by whitfiea** [comment]
Looks like it has also creeping back in via some of the other oneclick playbooks (optimiser, vi, assist)
