### ISSUE TITLE
Error in admin-build-config when trying to install Manage 

### ISSUE THREAD

**Issue by neilpatt** [ibm-mas/ansible-devops#540]
using the 12.2.1 version of the code I am encountering an error when trying to install manage

#environment variables needed for one of more components

export CLUSTER_DOMAIN=<your openshift cluster domain>  
export IBM_ENTITLEMENT_KEY=<IBM Entitlement Key> 
export MAS_INSTANCE_ID=masinst1
export MAS_CONFIG_DIR=~/mas
export SLS_LICENSE_ID=IBM EMEA 2022
export SLS_LICENSE_FILE=~/mas/entitlement.lic
export UDS_CONTACT_EMAIL=neil.patterson@nl.ibm.com
export UDS_CONTACT_FIRSTNAME=Neil
export UDS_CONTACT_LASTNAME=Patterson
export PROMETHEUS_ALERTMGR_STORAGE_CLASS=portworx-rwx-gp3-sc
export PROMETHEUS_STORAGE_CLASS=portworx-gp3-sc
export PROMETHEUS_USERWORKLOAD_STORAGE_CLASS=portworx-gp3-sc
export GRAFANA_INSTANCE_STORAGE_CLASS=portworx-gp3-sc
export MONGODB_STORAGE_CLASS=portworx-gp3-sc
export UDS_STORAGE_CLASS=portworx-gp3-sc

#environment varibles needed for manage and health

export MAS_APP_ID=manage
export MAS_APPWS_COMPONENTS="base=latest,health=latest"
export MAS_ENTITLEMENT_KEY=<IBM Entitlement Key>
export DB2_DATA_STORAGE_CLASS=portworx-db2-rwo-sc
export DB2_META_STORAGE_CLASS=portworx-db2-rwx-sc

#environment variables needed for IoT

export MAS_APP_SETTINGS_IOT_FPL_PVC_STORAGE_CLASS=portworx-gp3-sc
export MAS_APP_SETTINGS_IOT_DEPLOYMENT_SIZE=small
export KAFKA_STORAGE_CLASS=portworx-kafka-sc
export ZOOKEEPER_STORAGE_CLASS=portworx-gp3-sc

#environment variables needed for Predict

export WML_INSTANCE_ID="openshift"
export WML_URL Set Default="https://internal-nginx-svc.ibm-cpd.svc:12443" 
export WML_VERSION="4.5"
export PREDICT_DEPLOYMENT_SIZE="small"
export CP4D_INSTALL_PLATFORM="true"
export CP4D_INSTALL_WSL="true"
export CP4D_INSTALL_WM="true"
export CP4D_INSTALL_SPARK="true"
export CP4D_INSTALL_OPENSCALE="true"
export CPD_PRIMARY_STORAGE_CLASS=portworx-rwx-gp3-sc
export CPD_METADATA_STORAGE_CLASS=portworx-gp3-sc
export CPD_SERVICE_STORAGE_CLASS=portworx-gp3-sc

#environment variables needed for visual inspection
export MAS_ENTITLEMENT_USERNAME=masadmin
export MAS_APP_SETTINGS_VISUALINSPECTION_STORAGE_CLASS=portworx-sc

# Install core

oc login --token=${OAUTH_TOKEN} --server=https://api.${CLUSTER_DOMAIN}:6443
ansible-playbook ibm.mas_devops.oneclick_core

# Install IoT

ansible-playbook ibm.mas_devops.oneclick_add_iot

# Install Manage

ansible-playbook ibm.mas_devops.oneclick_add_manage

The pod admin-build-config-216-build is in error (repeatedly) error in the pod logs for the docker build container is

time="2022-12-05T09:31:54Z" level=info msg="Not using native diff for overlay, this may cause degraded performance for building images: kernel has CONFIG_OVERLAY_FS_REDIRECT_DIR enabled"
I1205 09:31:54.023914 1 defaults.go:102] Defaulting to storage driver "overlay" with options [mountopt=metacopy=on].
Caching blobs under "/var/cache/blobs".
Pulling image cp.icr.io/cp/manage/extension-health:8.7.0 ...
Trying to pull cp.icr.io/cp/manage/extension-health:8.7.0...
Warning: Pull failed, retrying in 5s ...
Trying to pull cp.icr.io/cp/manage/extension-health:8.7.0...
Warning: Pull failed, retrying in 5s ...
Trying to pull cp.icr.io/cp/manage/extension-health:8.7.0...
Warning: Pull failed, retrying in 5s ...
error: build error: failed to pull image: After retrying 2 times, Pull image still failed due to error: initializing source docker://cp.icr.io/cp/manage/extension-health:8.7.0: Requesting bear token: invalid status code from registry 400 (Bad Request)

**Comment by neilpatt** [comment]
adding the following environment variable fixed the problem - they should be added to the docs

**Comment by whitfiea** [comment]
@neilpatt those vars would default to the values you entered and I don't see how it would cause the failure you mention (the 400 error). This could have been just a point in time issue with the registry that happened to resolve when you set those other variables?

**Comment by andrercm** [comment]
Issue seems resolved, closing it.
