### ISSUE TITLE
Openshift Installation - rebuild.sh is missing in the container image

### ISSUE THREAD

**Issue by dirkhuppertz** [ibm-mas/ansible-devops#550]
I tried to install a MAS on SNO following the instructions on https://github.com/ibm-mas-manage/sno/blob/master/docs/index.md#openshift-installation

```
mkdir ~/sno
cd ~/sno
git clone https://github.com/ibm-mas/ansible-devops
docker run -dit -v ~/sno:/opt/app-root/src/sno --name sno quay.io/ibmmas/ansible-devops:latest bash​
docker exec -it sno bash
cd /opt/app-root/src/sno/ansible-devops/ibm/mas_devops
./rebuild.sh
exit
```

But, there is no rebuild.sh within the container.
Is the file missing or is the step no longer needed?

Best regards
Dirk

**Comment by whitfiea** [comment]
@dirkhuppertz I don't believe there has every been a rebuild.sh. It looks like you have an issue in the repo (https://github.com/ibm-mas-manage/sno/issues/53) that these instructions have been made so that is the best place for it.

FYI:  @sbudhira
