### ISSUE TITLE
AnalyticsProxy hangs in INSTALLING in UDS playbook

### ISSUE THREAD

**Issue by witekwww** [ibm-mas/ansible-devops#554]
I'm running UDS playbook in order to install UDS in OCP cluster, but getting stuck with AnalyticsProxy.
user-data-services-operator and ibm-events-operator installs ok (I can see them in Deployments in Ready state), but the AnalyticsProxy gets stuck in Installing with following message:
`[crcadmin@localhost mas-local]$ oc get analyticsproxy analyticsproxy -n ibm-common-services -o jsonpath='{.status}' | jq -r .
{
  "conditions": [
    {
      "ansibleResult": {
        "changed": 3,
        "completion": "2022-12-09T15:49:41.13156",
        "failures": 1,
        "ok": 76,
        "skipped": 43
      },
      "lastTransitionTime": "2022-12-09T15:49:41Z",
      "message": "The task includes an option with an undefined variable. The error was: 'secret_name' is undefined\n\nThe error appears to be in '/opt/ansible/roles/common/tasks/data-exchange-service.yaml': line 197, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create data exchange deployment\n  ^ here\n",
      "reason": "Failed",
      "status": "False",
      "type": "Failure"
    },
    {
      "lastTransitionTime": "2022-12-09T15:49:42Z",
      "message": "Running reconciliation",
      "reason": "Running",
      "status": "True",
      "type": "Running"
    }
  ],
  "phase": "Installing"
}
`

openShift version 4.11.13 and ansible-devops version 12.3.0

**Comment by whitfiea** [comment]
@witekwww This is an issue with the UDS operator rather than the ansible-devops collection, you would need to contact that team to investigate. I noticed that it looks like you are trying to install using a Openshift Local install, it might not be possible to install UDS on openshift-local.
