### ISSUE TITLE
cos module creating certificate incorrectly for objectstorage cfg CR

### ISSUE THREAD

**Issue by tcskill** [ibm-mas/ansible-devops#570]
the COS module is incorrectly creating the objectstorage cfg CR.  If you look at the line below, when costype is set to "ocs" it is only using the first two certificates in the chain.  The full certificate chain needs to be listed so need to add the 3rd cert in the chain to this objectstoragecfg.yml template

https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/cos/templates/ocs/objectstoragecfg.yml.j2#L29

**Comment by rawa-resul** [comment]
Discussion in here https://ibm-watson-iot.slack.com/archives/CNDB5GZ3P/p1671585881246769

**Comment by tcskill** [comment]
without having the full chain, the result is:

ObjectStorage configuration was unable to be verified. Err: Object
        Storage configuration could not be verified. Exception : SSL validation
        failed for
        https://rgw-openshift-storage.mas-op-dev-0ed2b1307d0ce0e0627ae949f443cd72-0000.us-east.containers.appdomain.cloud/
        [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to
        get issuer certificate (_ssl.c:1131)

**Comment by andrercm** [comment]
Closing this issue as it was fixed by the attached pull request.
