### ISSUE TITLE
Support to increase image-registry storage for roks and support for prometheus custom storage class

### ISSUE THREAD

**Issue by andrercm** [ibm-mas/ansible-devops#58]
Need a new role to support enhancing roks clusters to configure:
- [x] Increase cluster image-registry from 100Gi (default) to 400Gi - that's needed specially when we are planning to install many CP4D services.
- [x] Change openshift-monitoring config map to specify custom storage class for Prometheus service, as this monitoring tools can eat up lot of cluster internal storage

**Comment by andrercm** [comment]
https://github.com/ibm-mas/ansible-devops/pull/59

**Comment by durera** [comment]
This issue appears to be have been completed, closing the issue.
