### ISSUE TITLE
IBM MAS Ansible OneClick error with TASK [ibm.mas_devops.uds : Create UDS AnalyticsProxy] 

### ISSUE THREAD

**Issue by slxjcorrea** [ibm-mas/ansible-devops#589]
Hi

  When I try to install IBM MAS 8.8 using Ansible (playbook), I get the error.  I find in logfile, and 

ansible-playbook ibm.mas_devops.oneclick_core

  The problem is here:  crunchy-postgres-operator

TASK [ibm.mas_devops.uds : Create UDS AnalyticsProxy] *************************************************************************************************************************************************************************************
Tuesday 20 December 2022  17:42:57 +0000 (0:00:02.146)       0:03:28.935 ****** 
ok: [localhost] => {"changed": false, "method": "patch", "result": {"apiVersion": "uds.ibm.com/v1", "kind": "AnalyticsProxy", "metadata": {"creationTimestamp": "2022-12-20T12:23:51Z", "generation": 1, "managedFields": [{"apiVersion": "uds.ibm.com/v1", "fieldsType": "FieldsV1", "fieldsV1": {"f:status": {".": {}, "f:conditions": {}}}, "manager": "ansible-operator", "operation": "Update", "time": "2022-12-20T12:23:51Z"}, {"apiVersion": "uds.ibm.com/v1", "fieldsType": "FieldsV1", "fieldsV1": {"f:spec": {".": {}, "f:airgappeddeployment": {".": {}, "f:enabled": {}}, "f:allowed_domains": {}, "f:db_archive": {".": {}, "f:frequency": {}, "f:persistent_storage": {".": {}, "f:storage_size": {}}, "f:retention_age": {}}, "f:db_type": {}, "f:env_type": {}, "f:event_scheduler_frequency": {}, "f:ibmproxyurl": {}, "f:image_pull_secret": {}, "f:kafka": {".": {}, "f:storage_size": {}, "f:zookeeper_storage_size": {}}, "f:license": {".": {}, "f:accept": {}}, "f:postgres": {".": {}, "f:backup_frequency": {}, "f:backup_type": {}, "f:storage_size": {}}, "f:proxy_settings": {".": {}, "f:http_proxy": {}, "f:https_proxy": {}, "f:no_proxy": {}}, "f:storage_class": {}, "f:tls": {".": {}, "f:airgap_host": {}, "f:uds_host": {}}}, "f:status": {"f:phase": {}}}, "manager": "OpenAPI-Generator", "operation": "Update", "time": "2022-12-20T12:24:01Z"}], "name": "analyticsproxy", "namespace": "ibm-common-services", "resourceVersion": "377225", "uid": "fc8a1326-6e22-4ea1-8bb7-eb53a46bff35"}, "spec": {"airgappeddeployment": {"enabled": false}, "allowed_domains": "*", "db_archive": {"frequency": "@monthly", "persistent_storage": {"storage_size": "10G"}, "retention_age": 6}, "db_type": "internal", "env_type": "lite", "event_scheduler_frequency": "@daily", "ibmproxyurl": "https://iaps.ibm.com", "image_pull_secret": "uds-images-pull-secret", "kafka": {"storage_size": "5G", "zookeeper_storage_size": "5G"}, "license": {"accept": true}, "postgres": {"backup_frequency": "@daily", "backup_type": "incremental", "storage_size": "10G"}, "proxy_settings": {"http_proxy": "", "https_proxy": "", "no_proxy": ""}, "storage_class": "ibmc-block-gold", "tls": {"airgap_host": "", "uds_host": ""}}, "status": {"conditions": [{"ansibleResult": {"changed": 0, "completion": "2022-12-20T17:41:59.655618", "failures": 1, "ok": 24, "skipped": 26}, "lastTransitionTime": "2022-12-20T17:41:59Z", "message": "unknown playbook failure", "reason": "Failed", "status": "False", "type": "Failure"}, {"lastTransitionTime": "2022-12-20T17:41:59Z", "message": "Running reconciliation", "reason": "Running", "status": "True", "type": "Running"}], "phase": "Installing"}}}

TASK [ibm.mas_devops.uds : Wait for the AnalyticsProxy to be ready] ***********************************************************************************************************************************************************************
Tuesday 20 December 2022  17:43:00 +0000 (0:00:03.117)       0:03:32.052 ****** 
FAILED - RETRYING: [localhost]: Wait for the AnalyticsProxy to be ready (30 retries left).
FAILED - RETRYING: [localhost]: Wait for the AnalyticsProxy to be ready (29 retries left).
 

  Like a workaround, we apply this.  We installed Crunchy PostGresSQL v4.7.5 and worked ok but when install IBM MAS with Ansible, he try to install Crunchy PostGress v5.2.0 and that fail with error. Is the same error. New versión 5.2.0 fail and say that Calalog not available:

 Then, start again from scratch, I installed Crunchy PostGresSQL v4.7.5  again and make the upgrade manually and get the same error. 

Failed to pull image "[registry.connect.redhat.com/crunchydata/postgres-operator@sha256:4ad944f4f01a85249aa7678521e61fe48ed150ac43f3c38f33b42f7a32eb9961](https://registry.connect.redhat.com/crunchydata/postgres-operator@sha256:4ad944f4f01a85249aa7678521e61fe48ed150ac43f3c38f33b42f7a32eb9961)": rpc error: code = Unknown desc = Error reading manifest sha256:4ad944f4f01a85249aa7678521e61fe48ed150ac43f3c38f33b42f7a32eb9961 in [registry.connect.redhat.com/crunchydata/postgres-operator](https://registry.connect.redhat.com/crunchydata/postgres-operator): manifest unknown: manifest unknown

  Thanks

**Comment by durera** [comment]
This is a problem with IBM user data services and crunchy postgres.  IBM UDS installs the operator using startingCSV, forcing the operator to be at an older version, which then upgrades to the bad version of postgres and fails.

This is addressed here:
- https://github.com/ibm-mas/ansible-devops/pull/577

This is the underlying issue: https://github.com/CrunchyData/postgres-operator/issues/3506

**You need to update your operator catalog so that the fixed version of Postgres (v5.3.0) is available**.  if you do this and you install UDS using the latest version of this collection, it will ensure that v5.3.0 is installed before installing UDS, which will prevent UDS installing v5.1, which will automatically upgrade to v5.2 and hit this problem, preventing the subsequent upgrade to v5.3.

**Comment by slxjcorrea** [comment]
Hi David

   Thanks for the reply. Could you please help me by giving us the details of the step by step to be able to update the Operator catalog to make version 5.3.0 operational and that the UDS process recognize this version previously.

   I tell you that I tried to install the Operator manually (https://access.crunchydata.com/documentation/postgres-operator/v5/quickstart/ ) using version 5.3.0 and we installed it but then our installation process is not able to recognize that this version already exists and apply the StarCSV process as described,

   Please help us with the necessary steps to apply this workaround. Regards.

**Comment by durera** [comment]
The redhat certified operator catelog where postgres comes from is updated automatically by default, no action required.

No special steps are required to bypass the problems with UDS, the updates in this collection already implement the required workaround.
