### ISSUE TITLE
Investigate oneclick_add_visualinspection for deploying to hyperscaler such as AWS?

### ISSUE THREAD

**Issue by maulik-modi22** [ibm-mas/ansible-devops#596]
[MAS Core playbook](https://ibm-mas.github.io/ansible-devops/playbooks/oneclick-core/) clearly documents required storage class related environment variables (RWX/RWO).

> PROMETHEUS_ALERTMGR_STORAGE_CLASS
> PROMETHEUS_STORAGE_CLASS
> PROMETHEUS_USERWORKLOAD_STORAGE_CLASS
> GRAFANA_INSTANCE_STORAGE_CLASS
> MONGODB_STORAGE_CLASS
> UDS_STORAGE_CLASS

@pseemung, @durera, @alequint
Is it possible to document necessary storage related environment variables for [Maximo Visual Inspection](https://ibm-mas.github.io/ansible-devops/playbooks/oneclick-visualinspection/
) playbook?

At present, oneclick-visualinspection playbook deploys using **idmc-file-gold** storage class which is not available on AWS cloud, please refer screenshot below..
<img width="600" alt="ibm-pvc" src="https://user-images.githubusercontent.com/108735641/211540420-92a04bc2-863f-4da7-b438-a1d6d830f561.png">

Here's my storage classes on OCP 4.10 running on AWS using IPI i.e. RHCOS
<img width="732" alt="storage-classes" src="https://user-images.githubusercontent.com/108735641/211542897-347e5aba-3786-49ea-9da9-e9b2d5cfefe5.png">

**Comment by maulik-modi22** [comment]
I have set 
```
export MAS_APP_SETTINGS_VISUALINSPECTION_STORAGE_CLASS="efs"
export MAS_APP_SETTINGS_VISUALINSPECTION_STORAGE_SIZE="5Gi"
```
Now, I can see Ansible playbook logs with storage class: **efs**, refer this screenshot

<img width="1500" alt="mvi-playbook-logs" src="https://user-images.githubusercontent.com/108735641/212714753-c4a76546-4fba-42e2-b9d9-d503a05fb1a7.png">

However, still this deploys PVC looking for **ibmc-file-gold** under VisualInspection namespace, refer this screenshot
<img width="1509" alt="Screenshot 2023-01-16 at 8 58 27 PM" src="https://user-images.githubusercontent.com/108735641/212714156-f8edfa43-ea9b-44a4-90da-b1fb92af3aed.png">

**Comment by maulik-modi22** [comment]
@pseemung , could you provide some hint as @durera seems to be on vacation?  https://github.com/ibm-mas/ansible-devops/pull/434/commits/c745e7b48998c1f3699b1bc7f8ebf779015a67e1 is the original PR

**Comment by pseemung** [comment]
@maulik-modi22. I will investigate this issue.  Can you provide the cluster details so I can access and validate my changes for the AWS storage classes?

**Comment by maulik-modi22** [comment]
@pseemung , That cluster got deleted, I have a new cluster at the moment with only MAS Core+RWX storage class where I want to try executing MVI Playbook.

Can you suggest how do I find the right GPU version for given Openshift version, previously it used to create some issues?

from [Pull request for MVI](https://github.com/ibm-mas/ansible-devops/commit/d8ced960c1bac9cc0d2b465f525659ea0529eeee), I can see that to be explicit, it requires setting these variables

```
export MAS_APP_SETTINGS_VISUALINSPECTION_STORAGE_CLASS="efs"
export MAS_APP_SETTINGS_VISUALINSPECTION_STORAGE_SIZE="5Gi"
export GPU_CHANNEL=stable
export MAS_ENTITLEMENT_USERNAME=<<TBD>>
export MAS_ENTITLEMENT_KEY=<<TBD>>
export MAS_INSTANCE_ID=<<TBD>>
export MAS_APP_CHANNEL=8.9
export MAS_WORKSPACE_ID=masdev
export GPU_DRIVER_VERSION=
```

**Comment by maulik-modi22** [comment]
@caroazad , What is the effect of specifying GPU_DRIVER_VERSION while specifying GPU_CHANNEL? https://ibm-mas.github.io/ansible-devops/roles/nvidia_gpu/

**Comment by caroazad** [comment]
@maulik-modi22 I don't think we use that environment variable (GPU_DRIVER_VERSION) any more. There was a requirement for ocp versions that made MVI team to decide not to use that anymore. Now we set the value based on if it is using an ocp 4.11 version or 4.10 and below. Here is what we have:

 # GPU driver version
# for ocp version 4.11
ocp_411_driver_version: 470.103.01
# for ocp version <= 4.10
ocp_410_driver_version: 450.80.02

**Comment by maulik-modi22** [comment]
@caroazad, thanks for explanation. I will go with this setting to install GPU Operator

```
export NFD_CHANNEL=stable
export GPU_CHANNEL=v22.9
```

@caroazad, @pseemung , do I need to create ClusterPolicyInstance or it will be taken care by [https://ibm-mas.github.io/ansible-devops/playbooks/oneclick-visualinspection/](MVI Playbook)?

**Comment by caroazad** [comment]
@maulik-modi22 I haven't looked at MVI for a while now but I can help you take a look and investigate what is going on.

**Comment by maulik-modi22** [comment]
Issues identified
1. Nvidia GPU cluster policy keeps on running until failing with N number of retries
2. `MAS_APP_SETTINGS_VISUALINSPECTION_STORAGE_CLASS` variable is not respected

**Comment by andrercm** [comment]
@caroazad do you have plans to fix that soon? Let me know if you need any help with this. This seems an important fix so I'm labeling it as `High Priority`

**Comment by pseemung** [comment]
I validated the Cluster Policy installs properly on Maulik's aws environment pointing to a custom storage class.  Below are the variables used to install mvi playbook.

MAS_INSTANCE_ID=massso
MAS_CONFIG_DIR=dir
IBM_ENTITLEMENT_KEY=key
MAS_APP_SETTINGS_VISUALINSPECTION_STORAGE_CLASS=mvi-efs-patrick

**Comment by andrercm** [comment]
@pseemung any further help needed ?

**Comment by pseemung** [comment]
@andrercm, I think we should have @maulik-modi22  run the playbook to see if he reproduces the issue.  He did have different variables so that could have been an issue.

**Comment by maulik-modi22** [comment]
@pseemung , I ran it today after taking [mvi_storage_aws](https://github.com/ibm-mas/ansible-devops/tree/mvi_storage_aws) branch and variables below:

```
export MAS_APP_SETTINGS_VISUALINSPECTION_STORAGE_CLASS="mvi-efs-patrick"
export MAS_APP_SETTINGS_VISUALINSPECTION_STORAGE_SIZE="5Gi"
export MAS_APP_CHANNEL=\"8.7.x\"
export MAS_APP_ID="visualinspection"
export MAS_WORKSPACE_ID=masdev
export MAS_INSTANCE_ID=massso
```

What worked?
- [x] Nvidia GPU operator and cluster policy installed
- [x] Effect of MAS_APP_SETTINGS_VISUALINSPECTION_STORAGE_CLASS was correctly respected

What is pending?
- [ ] Verify MAS_APP_SETTINGS_VISUALINSPECTION_STORAGE_SIZE is respected correctly, I saw PVC getting bound with 100 Gb despite I specified 5Gb you can see above
- [ ] May be I did not uninstall correctly previous installed MVI by you, hence application was not up, what are the steps for clean uninstall?

```
TASK [ibm.mas_devops.suite_app_install : Wait until the Application's CRD is available] ****************************************************************************
FAILED - RETRYING: [localhost]: Wait until the Application's CRD is available (120 retries left).
FAILED - RETRYING: [localhost]: Wait until the Application's CRD is available (119 retries left).
```

**Comment by maulik-modi22** [comment]
#700

**Comment by andrercm** [comment]
Thanks @caroazad i'll remove you from the assignee list, just wanted to make sure we have someone working on that! :)

**Comment by caroazad** [comment]
@andrercm I can help but I didn't know that I was assigned. If you need me, I am around @pseemung

**Comment by maulik-modi22** [comment]
@pseemung , could you please abandon the pull request (Patch) if latest MAS Devops ansible can be used to successfully install MVI without this patch?

once you confirm, I will try 
`ansible-galaxy collection install ibm.mas_devops --force
`

Set
```
export MAS_APP_SETTINGS_VISUALINSPECTION_STORAGE_CLASS="mvi-efs-patrick"
export MAS_APP_SETTINGS_VISUALINSPECTION_STORAGE_SIZE="5Gi"
export MAS_APP_CHANNEL=\"8.7.x\"
export MAS_APP_ID="visualinspection"
export MAS_WORKSPACE_ID=masdev
export MAS_INSTANCE_ID=massso

```

and hit the command
`ansible-playbook ibm.mas_devops.oneclick_add_visualinspection
`

**Comment by pseemung** [comment]
@maulik-modi22 I validated that exporting the following works properly when set.

export MAS_APP_SETTINGS_VISUALINSPECTION_STORAGE_SIZE="5Gi"

![image](https://user-images.githubusercontent.com/47637676/228295022-abf0e7f0-c70d-40cf-98c9-3d532066314c.png)

**Comment by maulik-modi22** [comment]
@andrercm , I can see @pseemung has successfully installed MVI in my AWS cluster, good to merge this patch

**Comment by maulik-modi22** [comment]
@andrercm, @durera , I tried installation by checking out https://github.com/ibm-mas/ansible-devops/pull/712 and it appears to be working well - first time I was able to install MVI with one click....can't wait for this to get merged

![Screenshot 2023-03-29 at 7 28 37 PM](https://user-images.githubusercontent.com/108735641/228563996-3c03f055-bb26-42d9-9d7a-80eeaf616d1b.png)
![Screenshot 2023-03-29 at 7 28 22 PM](https://user-images.githubusercontent.com/108735641/228564017-8795d844-e634-4f31-bbba-ae280a1978ec.png)

![Screenshot 2023-03-29 at 7 36 35 PM](https://user-images.githubusercontent.com/108735641/228564438-218fd285-3f69-4a76-9514-3c2de628123a.png)

![Screenshot 2023-03-29 at 7 38 54 PM](https://user-images.githubusercontent.com/108735641/228565123-2b61133e-aebc-4f79-8717-64498df01107.png)
