### ISSUE TITLE
DB2 error while attempting to install Monitor using one-click-iot playbook

### ISSUE THREAD

**Issue by jcarrillo-powersolution** [ibm-mas/ansible-devops#604]
The error occurred installing Maximo Monitor on IBM Cloud:

```+ db2start
01/12/2023 17:07:20     0   0   SQL1042C  An unexpected system error occurred.
SQL1032N  No start database manager command was issued.  SQLSTATE=57019
+ sleep 5
++ db2gcf -s
++ awk -F : '{print $2}'
++ sed 's/^ *//; s/ *$//; /^$/d'
+ db2state=Operable
+ [[ Operable == \A\v\a\i\l\a\b\l\e ]]
+ echo '* ERROR: Failed to start Db2 successfully'
+ db2_kill -all
* ERROR: Failed to start Db2 successfully
db2nkill: DB2 member 0 with PID 4294967295 does not exist.
+ rah ipclean -a
 
Warning: Permanently added '[c-db2w-shared-db2u-0.c-db2w-shared-db2u-internal]:50022,[172.30.82.115]:50022' (ECDSA) to the list of known hosts.
Application ipclean: Removing all IPC resources for db2inst1(500)
c-db2w-shared-db2u-0.c-db2w-shared-db2u-internal: ipclean -a completed ok
+ RC=1
+ (( n++ ))
+ [[ 2 -le 1 ]]
Failed to start Db2 and restore morph job will fail
+ return 1
+ echo 'Failed to start Db2 and restore morph job will fail'
+ exit 1
command terminated with exit code 1
+ exit 1
```

Please see the attached file for more details.
[db2_error.log](https://github.com/ibm-mas/ansible-devops/files/10406023/db2_error.log)

**Comment by miles-canton** [comment]
Cause:
By default, the playbook that installs db2 uses the INSTANCE_MEMORY=AUTOMATIC parameter in the configuration to automatically configure the memory for the instance according to the memory of the OCP worker node.
When the memory of the worker node is greater than 64G, such as 128G, the calculated memory will exceed the limit value of the db2 pod, which is 16Gi by default, causing the db to fail to start.

Solution:
Before running the playbook,
export DB2_MEMORY_LIMITS=64Gi to increase the limit.
or
export DB2_INSTANCE_DBM_CONFIG='INSTANCE_MEMORY=10' reduces the ratio to 10% or whatever is suitable.

**Comment by miles-canton** [comment]
Cause:
By default, the playbook that installs db2 uses the **INSTANCE_MEMORY=AUTOMATIC** parameter in the configuration to automatically configure the memory for the instance according to the memory of the OCP worker node.
**https://www.ibm.com/docs/en/db2/11.5?topic=parameters-instance-memory-instance-memory**
When the memory of the worker node is greater than 64G, such as 128G, the calculated memory will exceed the limit value of the db2 pod, which is 16Gi by default, causing the db to fail to start.

Solution:
Before running the playbook,
**export DB2_MEMORY_LIMITS=128Gi** to increase the limit.
or
export **DB2_INSTANCE_DBM_CONFIG='INSTANCE_MEMORY=10'** reduces the ratio to 10% or whatever is suitable.
or use above method both

**Comment by durera** [comment]
I'm not familiar with this bit of the Db2 config previously.  My assumption would be that the `INSTANCE_MEMORY` setting - in the context of Db2 on OpenShift - would factor in the resources available in the pod, rather than the resources available on the worker node.

If I set up Db2 pod on a worker node with 128Gb memory, and set the pod with a limit of 16Gb memory I would hope that `instance_memory` is working on the basis of 16Gb memory being available to Db2.  I would consider it a bug in containerized Db2 if it did not.

I'm going to follow up with the Db2 team to confirm one way or another; if `INSTANCE_MEMORY` really is ignorant of the resources available to pod and is accounting for the resources available on the worker node then that's a) not great design and b) definitely something we are going to need to factor in and adjust how we manage Db2 installations.

**Comment by durera** [comment]
Response from the team:

> The engine does not know Db2 is running inside a container.. automatic will read the cgroups of the node and potentially go beyond the pod memory limit.
> Db2U has logic built in to use a normalized percentage that takes into account the memory limit and free memory of the node. No instance_memory is needed to be specified under dbmConfig.

Basically .. don't use this setting in containerized Db2 :) 

I'm not sure of the history behind this being added, but I'll get this option removed now.

**Comment by durera** [comment]
Fix available in https://github.com/ibm-mas/ansible-devops/releases/tag/12.10.3, thanks for reporting this @jcarrillo-powersolution, and also to @miles-canton for pointing me in the right direction :+1:
