### ISSUE TITLE
default version for kafka is unsupported for MAS 8.9

### ISSUE THREAD

**Issue by mattlrx** [ibm-mas/ansible-devops#658]
in the ansible devops documentation for kafka, https://ibm-mas.github.io/ansible-devops/roles/kafka/, the default value for kafka_version is 2.7.0, where the software product Compatibility Report for MAS 8.9 states that kafka should 2.8.0 or above (https://www.ibm.com/software/reports/compatibility/clarity/softwareReqsForProduct.html)

in addition, this role will install AMQ-Streams 1.8.4 which is not supported on openshift 4.9 and above

**Comment by andrercm** [comment]
@mattlrx thanks for the feedback, we're in the process of reviewing our backlog of opened issues for the upcoming releases of our collection and will take into consideration your item. Once again, thanks for contributing with our collection.

**Comment by pohlkamp** [comment]
@andrercm 
I have a similar issue, got Kafka deployed with AMQ-Streams 1.8.4 on MAS 8.9 / OCP 4.10, then tried to do an update of the cluster and cluster update fails at exactly this point.

It has killed the whole cluster upgrade in the middle:
"Cluster operator operator-lifecycle-manager should not be upgraded between minor versions: ClusterServiceVersions blocking cluster upgrade: amq-streams/amqstreams.v1.8.4 is incompatible with OpenShift minor versions greater than 4.9"


Affected file has hard coded version in it, not a variable ->
https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/kafka/templates/redhat/subscription.yml.j2
