### ISSUE TITLE
Documentation not updated for BAS automation

### ISSUE THREAD

**Issue by durera** [ibm-mas/ansible-devops#66]
please deliver fixes to this branch: https://github.com/ibm-mas/ansible-devops/tree/bugfixes2411

https://ibm-mas.github.io/ansible-devops/playbooks/lite-core-roks/

This page needs various updates to reflect the addition of automated BAS deployment to the playbook.

Address this after the issues raised in #65 have been addressed, as the fixes there will impact the documentation (we only want to fix this once)

The same issues are present on these pages as well:
- https://ibm-mas.github.io/ansible-devops/playbooks/lite-health-roks/
- https://ibm-mas.github.io/ansible-devops/playbooks/lite-manage-roks/

**Comment by andrercm** [comment]
@durera this should be fixed in https://github.com/ibm-mas/ansible-devops/pull/71

**Comment by andrercm** [comment]
@durera thanks for confirming, I'll close this issue then.
