### ISSUE TITLE
Support Manual Upgrade Strategy for Suite and Application

### ISSUE THREAD

**Issue by CAIOFCP** [ibm-mas/ansible-devops#67]
The collection should provide support to install MAS and any application using `Manual` upgrade strategy. So anyone that uses this collection to setup their environment won't get any upgrade without their consent. I would suggest make it the default behavior and only install with Automatic approval in case its specified by the executor.

When working on this issue its important to ensure that all the operators in the `ibm-common-services` is installed properly, if deployed my MAS csv, it will inherit the `Manual` upgrade strategy from MAS and in this case we shuld be also handling the approval for each of operator there, otherwise OLDM and Licensing operators wont get installed and MAS installation will fail.

**Comment by CAIOFCP** [comment]
@durera any thought on that ? I've started the code changes since we need this for Managed MAS, will open the PR once its done.

**Comment by durera** [comment]
I thought we had already locked everything to manual upgrade strategy by default tbh.  Yes it makes sense.  Can you take a look at & close out https://github.com/ibm-mas/ansible-devops/pull/37 before raising PR for this one though so we can try to clear the backlog of PRs we have starting to pile up

**Comment by durera** [comment]
This is already supported by mas_upgrade_strategy` & `mas_app_upgrade_strategy` parameters
