### ISSUE TITLE
Allow specifying NVidia GPU Driver version in Environment Variables

### ISSUE THREAD

**Issue by fyeh** [ibm-mas/ansible-devops#700]
Right now the `nvidia_gpu` role [hard codes the driver version](https://github.com/ibm-mas/ansible-devops/blob/ef51ede748e391ba444842b14d18f4622453b0b5/ibm/mas_devops/roles/nvidia_gpu/defaults/main.yml#L10) for ocp 4.11 and 4.10. 

This is not always going to be correct as the actual driver image that needs to be pulled will also depend on whether the worker is running RHEL or RHCOS, and which version of them it is running. The available driver to match the OS and version then needs to be looked up in the NVidia [NGC | CATALOG](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/driver/tags). 

Once that is done, the playbooks should allow for the defaults to be overridden in an environment variable.

**Comment by andrercm** [comment]
@caroazad what's your thoughts around that? can you simply add a lookup from env var and just add the suggested version as defaulted in case nothing is set?

**Comment by caroazad** [comment]
@fyeh @andrercm I just did what the MVI team asked me to do. We used to have an environment variable but they said it was going to cause issues and this would be best. Do you want me to make the changes to support both? I can do that asap

**Comment by andrercm** [comment]
You can make a comment in readme docs saying what's the recommended driver based on MVI team's suggestion but I think having the lookup gives us enough flexibility. tks!

**Comment by caroazad** [comment]
Yes, I made the changes to add the environment variable but I also need to make sure of some other stuff if @fyeh could help me understand how to determine the os. I think for now the 4.11 is using version 8.6 rhel. Do all 4.11 use this or do they use others too. I really want to make this robust as possible so that it can work on all the platforms we have such as aws, roks, etc. I cannot do this if I am don't know what is expected or what we need.

**Comment by maulik-modi22** [comment]
@caroazad , 
IPI clusters on AWS use RH COS for workers 
`Red Hat Enterprise Linux CoreOS 410.84.202302080019-0`

**Comment by maulik-modi22** [comment]
@fyeh , What about GPU channel? 
When I set `GPU_CHANNEL = stable`, it fails with cluster policy error?

When I select `stable` channel on OCP 4.10 on AWS, I see v22 of Nvidia operator getting installed refer - https://github.com/ibm-mas/ansible-devops/issues/596 but fails with cluster policy error.

**Comment by fyeh** [comment]
@maulik-modi22 The GPU Channel should only determine the version of the GPU Operator. The Driver version can be set in the Cluster Policy but I believe if a version is not set explicitly, it will select something. I don't know how it does this selection.

**Comment by maulik-modi22** [comment]
@fyeh , I came across [Nvidia GPU Operator Matrix](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/platform-support.html#gpu-operator-component-matrix) that shows correlation between `GPU Channel` and recommended `GPU Driver version`.  Do you mean any combination of `GPU operator` and `Driver version` would be valid?
