### ISSUE TITLE
UDS failure after running install oneclick_core playbook on cluster with existing MAS instance

### ISSUE THREAD

**Issue by mudspringhiker** [ibm-mas/ansible-devops#721]
A customer is trying to install a second instance of MAS using the mongo and UDS that are already in the cluster.
Error:

```
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.9/site-packages/ansible/plugins/action/template.py", line 150, in run
    resultant = templar.do_template(template_data, preserve_trailing_newlines=True, escape_backslashes=False)
  File "/opt/app-root/lib64/python3.9/site-packages/ansible/template/__init__.py", line 1199, in do_template
    raise AnsibleUndefinedVariable(e)
ansible.errors.AnsibleUndefinedVariable: list object has no element 1
fatal: [localhost]: FAILED! => {
    "changed": false,
    "msg": "AnsibleUndefinedVariable: list object has no element 1"
```

From this, it was determined (by @durera) that the UDS cert has only 1 part. Customer said theirs has 4 parts, though.

When working on this issue, please also consider this issue and close them both when all done: https://github.com/ibm-mas/ansible-devops/issues/734

**Comment by mudspringhiker** [comment]
internal issue: https://github.ibm.com/wiotp/tracker/issues/11722.

**Comment by mudspringhiker** [comment]
prior to running the oneclick_core playbook, they run the following:
```
export IBM_ENTITLEMENT_KEY=xxxxxxxx
export MAS_INSTANCE_ID=xxx
export MAS_CONFIG_DIR=~/masconfigua 
export SLS_LICENSE_ID=xxxxxxxx
export SLS_LICENSE_FILE=/mascli/license.dat 
export UDS_CONTACT_EMAIL=xxxx
export UDS_CONTACT_FIRSTNAME=xxx 
export UDS_CONTACT_LASTNAME=xxx
export OCP_INGRESS_TLS_SECRET_NAME=router-ca
export PROMETHEUS_STORAGE_CLASS=thin
export PROMETHEUS_USERWORKLOAD_STORAGE_CLASS=thin
export GRAFANA_INSTANCE_STORAGE_CLASS=thin
export MONGODB_STORAGE_CLASS=thin
export UDS_STORAGE_CLASS=thin
export PROMETHEUS_ALERTMGR_STORAGE_CLASS=thin
```

**Comment by andrercm** [comment]
Thank you for your feedback @mudspringhiker.

I'll include this issue to be fixed along our upcoming releases.

We need to be flexible enough to set UDS certs accordingly to the number of certs found in the secret that is passed as argument. Currently it always expects at least two pieces of certs. Most likely the `router-ca` secret in your case has just one certificate rather than two which is what the automation is expecting.

**Comment by p-challa** [comment]
FYI - The router-ca has only one certificate. UDS has 4 parts of certificate.
