### ISSUE TITLE
Add an option to delete only the Mongo databases associated with the MAS instance being uninstalled when running uninstall_core playbook.

### ISSUE THREAD

**Issue by blechner** [ibm-mas/ansible-devops#733]
As of now, according to [the documentation](https://ibm-mas.github.io/ansible-devops/playbooks/uninstall-core/), you can uninstall MAS using the `uninstall_core` playbook and skip the removal of Mongo by setting `MONGODB_ACTION` to `none`. However, when uninstalling a MAS instance that uses a shared Mongo service, it would be useful to add an option (either in this specific `MONGODB_ACTION` env var or a new one, if necessary) to allow for deletion of only the databases associated with the MAS instance being uninstalled (`mas-<instanceid>-core` ,` mas-<instanceid>-catalog` and `mas-<instanceid>-adoptionusage`).

**Comment by andrercm** [comment]
@blechner we have implemented a new flag to allow Mongo clean up while uninstalling suite as part of `uninstall_suite` role, this is yet to be merged:

https://github.com/ibm-mas/ansible-devops/pull/706

It uses this python script located in coreapi to clean it up:
```
      shell: oc exec -it {{ coreapi_pod_name }} -n mas-{{ mas_instance_id }}-core python3 /opt/ibm/coreapi/wipeData.py silent-wipe-data
```

The thing is that this script seems to not be deleting the `mas-<instanceid>-core`, it just deletes the other two dbs `mas-<instanceid>-catalog and mas-<instanceid>-adoptionusage`

@joaopauloksn any idea what might be happening?

**Comment by andrercm** [comment]
Initial implementation of this is done, closing it for now.
