### ISSUE TITLE
suite_dns failing with TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by pmvester** [ibm-mas/ansible-devops#736]
ibmmas/cli:3.17.0 "mas install" failing with:

TASK [ibm.mas_devops.suite_dns : cis : run cis_dns_entries module] *************
Monday 27 March 2023  13:55:46 +0000 (0:00:00.074)       0:00:05.344 ********** 
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: object of type 'NoneType' has no len()
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1679925346.2130256-121-63532093563674/AnsiballZ_cis_dns_entries.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1679925346.2130256-121-63532093563674/AnsiballZ_cis_dns_entries.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1679925346.2130256-121-63532093563674/AnsiballZ_cis_dns_entries.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.ibm.mas_devops.plugins.modules.cis_dns_entries', init_globals=dict(_module_fqn='ansible_collections.ibm.mas_devops.plugins.modules.cis_dns_entries', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.9/runpy.py\", line 225, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_ibm.mas_devops.cis_dns_entries_payload_8dc48icz/ansible_ibm.mas_devops.cis_dns_entries_payload.zip/ansible_collections/ibm/mas_devops/plugins/modules/cis_dns_entries.py\", line 275, in <module>\n  File \"/tmp/ansible_ibm.mas_devops.cis_dns_entries_payload_8dc48icz/ansible_ibm.mas_devops.cis_dns_entries_payload.zip/ansible_collections/ibm/mas_devops/plugins/modules/cis_dns_entries.py\", line 259, in main\nTypeError: object of type 'NoneType' has no len()\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

CIS_APIKEY=1TwD69GN4IYIBTGUYPTyrSTbisUjegYMHBCOln9de3_O
CIS_CRN=crn:v1:bluemix:public:internet-svcs:global:a/1153702d2118844328a680b82517e235:1bdff21f-dc86-4f74-9b6b-0719eff09920::
CIS_EMAIL=mikael.vester@se.ibm.com
CIS_SUBDOMAIN=alice
DNS_PROVIDER=cis
MAS_DOMAIN=alice.imomax.org
MAS_INSTANCE_ID=mas8

**Comment by andrercm** [comment]
@pmvester Thank you for feedback.

We have recently changed this module to support security settings for CIS, and indeed this looks like a bug around these latest changes.

We have a fix for it in the following PR: https://github.com/ibm-mas/ansible-devops/pull/730

This should be merged and made available in the next ansible-devops/cli release.

**Comment by andrercm** [comment]
That's fixed and merged in the recent PR above. Will be available in the next ansible-devops/cli release.
