### ISSUE TITLE
Upgrade DB2 operator/version

### ISSUE THREAD

**Issue by andrercm** [ibm-mas/ansible-devops#743]
Currently we're using `db2_version: 11.5.7.0-cn4` along with our automation by default.
Accordingly to DB2 documentation, this is compatible with OCP 4.0 (yeah!):
https://www.ibm.com/docs/en/db2/11.5?topic=1157-upgrading-updating

We need to bump it to `s11.5.8.0-cn1` which is the latest available version, compatible with OCP 4.10/4.12.
https://www.ibm.com/docs/en/db2-warehouse?topic=db2-warehouse-rhos-k8s

Also we need to make sure that MAS apps using DB2 are compatible with the new version, so mainly two tests needs to be done:
- [ ] clean install MAS apps in `db2_version: s11.5.8.0-cn1`, so need to set it as default in `db2` role.
- [ ] make sure the `db2` role also allows [upgrading](https://www.ibm.com/docs/en/db2/11.5?topic=uu-upgrading-db2cluster-instance#upgrd_db2clstr) `db2_version: 11.5.7.0-cn4` to `db2_version: s11.5.8.0-cn1`, so need to have MAS apps installed in `db2_version: 11.5.7.0-cn4` then running the `db2` to switch db2ucluster to `db2_version: s11.5.8.0-cn1` allows the db2 upgrade and no affect to MAS apps.

**Comment by whitfiea** [comment]
We should move to 11.5.8.0-cn2 which would be available also when 110508.0.2 is available.

**Comment by whitfiea** [comment]
Upgrading from `11.5.7.0-cn4` to `s11.5.8.0` works fine using the 110508.0.0 db2u operator

**Comment by durera** [comment]
Looks like this has already been done: `ibm/mas_devops/roles/db2/defaults/main.yml`

```
db2_version: "{{ lookup('env', 'DB2_VERSION') | default('s11.5.8.0', true) }}"
```
