### ISSUE TITLE
mascli 3.19.0 - create mas core route incorrectly

### ISSUE THREAD

**Issue by liupinyi** [ibm-mas/ansible-devops#758]
I used mascli 8.19.0 to install MAS 8.9.3 and 8.10, it created routes incorrectly as follows:

![ccedaf63b0b6ee91c80c010e075eaac](https://user-images.githubusercontent.com/21214618/230543365-1f5e6561-0d6a-4208-84b3-d9bada6349e5.png)

suite CR's domain is not correct:

![1680843336624](https://user-images.githubusercontent.com/21214618/230543638-c6bc8c86-a315-4b5c-8ee7-41a46e7fa6a6.png)

The ocp ingress domain is correct:

![ccedaf63b0b6ee91c80c010e075eaac](https://user-images.githubusercontent.com/21214618/230543375-d533eb25-6685-4b24-a16a-b3b47df902b1.png)

It will cause that Workspace is not ready.

```
      message: >-
        Unable to process workspace in OpenID: {'[status_code:500] Failed to add
        OIDC URI for x1me12lP6tl89TW3qk44wBYzN1nOGV5J,
        {"exception":{"id":"AIUI1999E","properties":["An unexpected exception
        occured while updating the openId configuration:
        HTTPSConnectionPool(host=\'auth.bjmtr\', port=443): Max retries exceeded
        with url:
        /oidc/endpoint/MaximoAppSuite/registration/x1me12lP6tl89TW3qk44wBYzN1nOGV5J
        (Caused by NewConnectionError(\'<urllib3.connection.HTTPSConnection
        object at 0x7f65dbaa12b0>: Failed to establish a new connection: [Errno
        -2] No address found\'))"]},"message":"AIUI1999E: Internal Server Error:
        An unexpected exception occured while updating the openId configuration:
        HTTPSConnectionPool(host=\'auth.bjmtr\', port=443): Max retries exceeded
        with url:
        /oidc/endpoint/MaximoAppSuite/registration/x1me12lP6tl89TW3qk44wBYzN1nOGV5J
        (Caused by NewConnectionError(\'<urllib3.connection.HTTPSConnection
        object at 0x7f65dbaa12b0>: Failed to establish a new connection: [Errno
        -2] No address found\'))"}\n'}
```
		
		
		############
		
		
```
		        Unable to process workspace in OpenID: {'[status_code:500] Failed to add
        OIDC URI for x1me12lP6tl89TW3qk44wBYzN1nOGV5J,
        {"exception":{"id":"AIUI1999E","properties":["An unexpected exception
        occured while updating the openId configuration: Expecting value: line 1
        column 1 (char 0)"]},"message":"AIUI1999E: Internal Server Error: An
        unexpected exception occured while updating the openId configuration:
        Expecting value: line 1 column 1 (char 0)"}\n'}
```

**Comment by liupinyi** [comment]
I update the Suite cr's domain and it can fix the issue. But please fix it in the mascli. Thank you.

**Comment by liupinyi** [comment]
Or we changed the design?

**Comment by andrercm** [comment]
@liupinyi thanks for your feedback, can you please provide the debug/log the the mas install via cli? we can try to identify the parameters added during the install to see if there was anything added as input that could have caused it.

**Comment by liupinyi** [comment]
I didn't use mascli and pipeline. I just used ansible script within the mascli container to install the MAS core.

**Comment by andrercm** [comment]
Do you have a list of exported environment variables you used to describe while installing MAS via ansible collection?

**Comment by liupinyi** [comment]
> Do you have a list of exported environment variables you used to describe while installing MAS via ansible collection?

```
export MAS_CONFIG_DIR=/masmnt
export MAS_CHANNEL=8.9.x
export MAS_WORKSPACE_NAME='Main Workspace'
export MAS_WORKSPACE_ID=main
export IBM_ENTITLEMENT_KEY=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJJQk0gTWFya2V0cGxhY2UiLCJpYXQiOjE2MjI3OTA2ODUsImp0aSI6IjAxNjUxOGJlMWM0NjRkNTg4OTU1ZjYyYjNiYzgwYjYxIn0.XW7gCwOKHsEJkMmR-gCFZYBX2hzKlzlmq-MYBx0f1RE

export MAS_INSTANCE_ID=bjmtr
export MAS_DOMAIN=bjmtr
```

wow, the change is I added the last ENV  `export MAS_DOMAIN=bjmtr`  than before. Is it the root cause? What is the different between MAS_INSTANCE_ID and MAS_DOMAIN?Thank you.

**Comment by liupinyi** [comment]
I think they are same so I set them for both recently.

**Comment by liupinyi** [comment]
So if I didn't set MAS_DOMAIN, and only set MAS_INSTANCE_ID, it will use MAS_INSTANCE_ID to replace MAS_DOMAIN? Thank you.

https://github.com/ibm-mas/ansible-devops/blob/7d7b5ba5ff73a1950f98f7dbea935a2ea5f0dd34/ibm/mas_devops/roles/suite_dns/templates/edge_certificate_routes.yml.j2

**Comment by andrercm** [comment]
So since you exported `MAS_DOMAIN=bjmtr`, this is what is being used to setup the MAS routes. If you don't have any custom domains configured, you can just not set `MAS_DOMAIN` at all, then the defaulted option will be: 

`mas_domain: <mas_instance_id>.<your_clusters_ingress>`

which is defined here: https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/suite_install/tasks/main.yml#L101

In your case, the domain would then be set to `bjmtr.apps.itzocp...fyre.ibm.com`, if `MAS_DOMAIN` is commented/removed from the list of environment variables.

**Comment by liupinyi** [comment]
> So since you exported `MAS_DOMAIN=bjmtr`, this is what is being used to setup the MAS routes. If you don't have any custom domains to be used, you can just not set `MAS_DOMAIN` at all, then the defaulted option will be:
> 
> `mas_domain: <mas_instance_id>.<your_clusters_ingress>`
> 
> which is defined here: https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/suite_install/tasks/main.yml#L101
> 
> In your case, the domain would then be set to `bjmtr.apps.itzocp...fyre.ibm.com`, if `MAS_DOMAIN` is commented/removed from the list of environment variables.

Thank you so very much. I undertand it now :)

The last question is about this role(in the following playbook):
https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/playbooks/oneclick_core.yml#L63

I reviewed the readme file and still have some confustion, I commented it in the playbook before. But I didn't comment it recently, what is the change will happen?

https://github.com/ibm-mas/ansible-devops/blob/c3cba1134b66bdf96a238f7dfbb3f1727a8bd0cb/ibm/mas_devops/roles/suite_dns/README.md

**Comment by liupinyi** [comment]
That to say, If I didn't set MAS_DOMAIN, I MUST set MAS_INSTANCE_ID

`    mas_domain: "{{ mas_instance_id }}.{{ _cluster_subdomain.resources[0].spec.domain }}"`

**Comment by andrercm** [comment]
The `suite_dns` role is helpful mainly if you want to setup a custom domain for MAS which will most likely require a DNS management system to deal with registered domain, its subdomains, proxy and firewall settings, etc

This role will only do something if `DNS_PROVIDER` role is set to one of the supported DNS providers listed:
https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/suite_dns/tasks/main.yml#L14

So you don't need to worry about leaving that role uncommented, this will be skipped if the expected vars are not set.

**Comment by liupinyi** [comment]
@andrercm Got it. Thank you so very much. Have a good day.  :) 

> The `suite_dns` role is helpful mainly if you want to setup a custom domain for MAS which will most likely require a DNS management system to deal with registered domain, its subdomains, proxy and firewall settings, etc
> 
> This role will only do something if `DNS_PROVIDER` role is set to one of the supported DNS providers listed: https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/suite_dns/tasks/main.yml#L14
> 
> So you don't need to worry about leaving that role uncommented, this will be skipped if the expected vars are not set.

**Comment by andrercm** [comment]
Glad I could help @liupinyi !
Have a nice day you too.
