### ISSUE TITLE
'dict object' has no attribute 'saslmechanism' in IoT due to kafka user error

### ISSUE THREAD

**Issue by whitfiea** [ibm-mas/ansible-devops#781]
The configiration of IoT fails with `'dict object' has no attribute 'saslmechanism' ` due to the kafkacfg not being configured correctly (so the kafka binding fails to create the resource that contains the saslmechanism. 

The kafkacfg can't be validation as the ansible-devops role for kafka has somehow changed the masuser credentials in amq-streams but not updated the masuser crendentials that is given to the kafkacfg. It looks like running the ansible-devops role for kafka mulitple times changes the credentials so the role is not idemptotent.

**Comment by andrercm** [comment]
I have a fix for it in a current branch I'm working on for event streams enhancements,
