### ISSUE TITLE
Replace compute-nodes with replicas

### ISSUE THREAD

**Issue by svelagap** [ibm-mas/ansible-devops#788]
Replace compute-nodes with replicas in ansible-devops/ibm/mas_devops/roles/ocp_provision/tasks/providers/rosa.yml for the following task.

- name: "rosa : Create ROSA cluster"

ROSA provisioning automation failed because of this issue

**Comment by whitfiea** [comment]
the rosa cli deprecated compute-nodes back in October last year https://github.com/openshift/rosa/blob/master/CHANGES.adoc#127-oct-3-2022 and it seems that the latest version (1.2.21 at this time) has removed the deprecated `compute-nodes` and replaced it with `replicas`
