### ISSUE TITLE
suite_dns role: installing in an empty cluster has side effects on common-services install

### ISSUE THREAD

**Issue by jeancrg** [ibm-mas/ansible-devops#795]
When I tried to run the role in an empty cluster that did not have cert-manager installed, the role failed, which is ok. However, later I tried the install of IBM Common services running its specific role and it failed

![image](https://user-images.githubusercontent.com/104657263/236009530-577ef0e6-e70e-4b82-8b60-f4c7254db252.png)

![image](https://user-images.githubusercontent.com/104657263/236009559-4325ef5c-297b-4f19-9e74-6f1ff3ea9fbb.png)

![image](https://user-images.githubusercontent.com/104657263/236009603-308d614e-419e-4d68-b6ac-7c62f29ccedb.png)

This solved the problem: oc delete apiservice [v1alpha1.acme.cis.ibm.com](http://v1alpha1.acme.cis.ibm.com/)

However needs to update the role to avoid this side effect to happen. Some validation or cleaning in case of failure.

**Comment by whitfiea** [comment]
@andrercm maybe something to include when you look at https://github.com/ibm-mas/ansible-devops/issues/530?

**Comment by andrercm** [comment]
I think we need to add an assert to check if cert-manager is installed rather than checking which cert-manager is installed (it's long past due since we dropped support for jetstack cert-manager)

**Comment by andrercm** [comment]
@jeancrg this issue is fixed with the linked PR, will close this issue but we can reopen later if needed.
