### ISSUE TITLE
Grafana is using the wrong storage class/access mode

### ISSUE THREAD

**Issue by durera** [ibm-mas/ansible-devops#801]
Reviewing the monitoring stack we stand up, it appears that it's not been working for a while, depending on where the scheduler deploys the grafana pods.

We are currently using RWO storage class for Grafana: https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/cluster_monitoring/tasks/install/determine-storage-classes.yml#L56-L66 and setting the access mode to `ReadWriteOnce` https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/cluster_monitoring/templates/grafana.yml.j2#L24-L25

Both need to be changed, and we need to make sure that the CLI tekton pipeline is mapping the RWX storage class to the Grafana storage class parameter.

```
Events:
  Type     Reason       Age                    From            Message
  ----     ------       ----                   ----            -------
  Warning  FailedMount  2m14s (x454 over 17h)  kubelet         (combined from similar events): Unable to attach or mount volumes: unmounted volumes=[grafana-data], unattached volumes=[grafana-data grafana-provision-dashboards grafana-datasources kube-api-access-g2l5m grafana-config grafana-logs grafana-plugins grafana-provision-notifiers grafana-provision-plugins]: timed out waiting for the condition
  Warning  FailedMount  107s (x514 over 17h)   ibm/ibmc-block  Error while attaching the device pv pvc-4e01d5d0-a1f8-4e09-ab5a-c12e53f72245 cannot be attached to the node 10.183.59.178. Error: PV pvc-4e01d5d0-a1f8-4e09-ab5a-c12e53f72245 is already attached to another node 10.183.59.133 and there are active pods [grafana-deployment-69cccd89c-xwmx9] using that
```

Additionally the `cluster_monitoring` role should be updated such that it would fail if this happens .. it should be verifying the deployment is healthy and failing if it's not.

**Comment by JonahLuckett** [comment]
Correction - #832 above is not linked to this issue
