### ISSUE TITLE
MAS on-premises SNO - Certificate Issuers

### ISSUE THREAD

**Issue by jroldj** [ibm-mas/ansible-devops#826]
While deploying MAS multiple times on various platforms with different certificate issuers, I recently pondered over the question: Which CA Authorities (issuers) are compatible for configuring a custom SSL certificate with an On-Premise MAS deployment on Single Node OpenShift?

Any idea?
regards,
Jean

**Comment by whitfiea** [comment]
@jroldj Whether it is SNO or non SNO I don't believe would make a difference to what certificate issuer can be used. Are you seeing a particular issue in SNO?

**Comment by andrercm** [comment]
Closing as no further response or feedback.
