### ISSUE TITLE
Enhance ocp_efs to support Multi-AZ

### ISSUE THREAD

**Issue by svelagap** [ibm-mas/ansible-devops#827]
Currently the role ocp_efs creates EFS in a single zone. It would be convenient if the role can detect if a VPC is Multi-AZ and create EFS in Multi-AZ.

It would also be good to have the option to pick a Provisioned EFS.

For now I have to provision EFS manually for Multi-AZ

**Comment by maulik-modi22** [comment]
#651

**Comment by JonahLuckett** [comment]
Closing as duplicate of https://github.com/ibm-mas/ansible-devops/issues/651
