### ISSUE TITLE
Wrong digest for MongoDB in air-gap mirroring

### ISSUE THREAD

**Issue by witekwww** [ibm-mas/ansible-devops#835]
There is wrong digest for MongoDB (quay.io/ibmmas/mongo) using v8-230414-amd64
Digest in the CASE points to version 4.2.23 and not to 4.4.21
This will result in mirroring the wrong image and air-gapped installation will fail due to missing image.

**Comment by whitfiea** [comment]
@witekwww Can you use catalog [v8-230518-amd64](https://ibm-mas.github.io/cli/catalogs/v8-230518-amd64/) as the static catalog from last month won't have the recently updated mongo image like you have found.

**Comment by whitfiea** [comment]
@witekwww After reviewing the digests we have I spotted the issue, and it is just like you say that the digest is incorrect. The reference PR should fix this once it is it in a release of mas_devops.
