### ISSUE TITLE
Support Health and Predict Utilities deployment

### ISSUE THREAD

**Issue by alequint** [ibm-mas/ansible-devops#84]
- [x] Configure AppConnect (see https://github.com/ibm-mas/ansible-devops/issues/83)
- [x] Configure WatsonStudio (using external URL, internal one was not tested)
- [x] Deploy H&P Utilities
- [x] Activate H&P Utilities

**Comment by andrercm** [comment]
Related story: https://github.com/ibm-mas/ansible-devops/issues/192
This should be closed by this PR: https://github.com/ibm-mas/ansible-devops/pull/201
What is pending is to review/merge the above PR and then follow up to include HPU in fvt pipeline @caroazad @bwbudak fyi
