### ISSUE TITLE
add db2wh and dmc to the list of supported cpd services

### ISSUE THREAD

**Issue by texkelly** [ibm-mas/ansible-devops#842]
Please add db2wh and cp4d to the list of services supported by https://ibm-mas.github.io/ansible-devops/roles/cp4d_service

This is required for the DB2 instances to available in DMC and centrally managed as part of the CP4D control plane.

It would also enable us to leverage this devops repo for TAS - so we don't have to re-invent the wheel

**Comment by maulik-modi22** [comment]
DMC allows validating database connection quickly and provides management interface, very important to have

**Comment by texkelly** [comment]
Looks like TAS MS will pivot to use db2wh outside of cp4d, so no urgency on that for us now. We will still need DMC for our DBA team in a select number of clusters.

**Comment by maulik-modi22** [comment]
@texkelly , May I know what are the supported databases for TAS? 
In case of MAS Manage, it supports oracle, sql server and Db2...

**Comment by texkelly** [comment]
TAS supports the same set of DBMs currently. CP4D with DB2WH & DMC in the cluster and DB2 Standard Edition outside the cluster are bundled with the product.

**Comment by durera** [comment]
Closing this.  The Standalone Db2 Universal Operator remains our only focus for providing Db2 in-cluster.
