### ISSUE TITLE
ocp_efs doc/readme not in MAS Devops Ansible Collection Documentation

### ISSUE THREAD

**Issue by mudspringhiker** [ibm-mas/ansible-devops#869]
A customer is using the ocp_efs role. We could not find this role in the docs in https://ibm-mas.github.io/ansible-devops/, but found it in https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/ocp_efs/README.md.

**Comment by maulik-modi22** [comment]
@mudspringhiker , I hope customer is aware limitation of this role outlined in #651
