### ISSUE TITLE
Installing predict/cpd onto a cluster that is using portworx as storage provider fails

### ISSUE THREAD

**Issue by neilpatt** [ibm-mas/ansible-devops#873]
When trying to install the latest version of predict into a cluster that is using portworx as a storage provider the cp4d task fails with the following error message

TASK [ibm.mas_devops.cp4d : determine-storage-classes : Assert that primary storage class has been defined] ***
Tuesday 20 June 2023  10:00:25 +0000 (0:00:00.063)       0:00:05.333 ********** 
fatal: [localhost]: FAILED! => {
    "assertion": "cpd_primary_storage_class is defined and cpd_primary_storage_class != \"\"",
    "changed": false,
    "evaluated_to": false,
    "msg": "cpd_primary_storage_class must be defined"
}

The common_vars/default_storage_classes.yml is as follows (no entry for portworx)
---
default_storage_classes_rwx:
  - ibmc-file-gold-gid
  - ocs-storagecluster-cephfs
  - efs
  - azurefiles-premium

default_storage_classes_rwx_nogid:
  - ibmc-file-gold
  - ocs-storagecluster-cephfs
  - efs
  - azurefiles-premium

default_storage_classes_rwo:
  - ibmc-block-gold
  - ocs-storagecluster-ceph-rbd
  - gp2
  - managed-premium

the default rwo and rwx storage classes for portworx should be added

**Comment by andrercm** [comment]
@neilpatt thanks for the feedback, we will assess your request and determine if that's possible to include it within the upcoming release versions of our collection.

**Comment by andrercm** [comment]
Did some investigations and apparently there's no default storage classes that can be used for file and block storages while using portworx sc. Instead, CPD suggests to configure individual storage classes for specific purposes. 

Please, refer to https://www.ibm.com/docs/en/cloud-paks/cp-data/4.6.x?topic=storage-creating-portworx-classes

Therefore, it would not be possible to define one defaulted storage class to be used across the entire MAS dependencies installation, which is the purpose of having the defaulted storage classes. You would have to export the specific `cpd_primary_storage_class` and `cpd_block_storage_class` as well as specific `cpd_service_storage_class`
`cpd_service_block_storage_class` while using `cp4d_service` role to install a given CPD service.
