### ISSUE TITLE
uninstall UDS fails with error 'postgres_source' is undefined

### ISSUE THREAD

**Issue by mattlrx** [ibm-mas/ansible-devops#879]
when uninstalling uds, using the uninstall playbook, it fails with error:

TASK \[ibm.mas\_devops.uds : uninstall : Delete Crunchy Postgres Subscription\] \*\*\*  
Thursday 22 June 2023  02:39:20 +0000 (0:00:00.070)       0:00:56.360 \*\*\*\*\*\*\*\*\*   
fatal: \[localhost\]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'postgres\_source' is undefined\\n\\nThe error appears to be in '/opt/app-root/lib64/python3.9/site-packages/ansible\_collections/ibm/mas\_devops/roles/uds/tasks/uninstall/main.yml': line 75, column 3, but may\\nbe elsewhere in the file depending on the exact syntax problem.\\n\\nThe offending line appears to be:\\n\\n# -----------------------------------------------------------------------------\\n- name: \\"uninstall : Delete Crunchy Postgres Subscription\\"\\n  ^ here\\nThis one looks easy to fix. It seems that there is a value started\\nwith a quote, and the YAML parser is expecting to see the line ended\\nwith the same kind of quote. For instance:\\n\\n    when: \\"ok\\" in result.stdout\\n\\nCould be written as:\\n\\n   when: '\\"ok\\" in result.stdout'\\n\\nOr equivalently:\\n\\n   when: \\"'ok' in result.stdout\\"\\n"}  
 

a recent change in the uds install introduced some variables in the /roles/uds/templates/crunchy-postgres/subscription.yml  
 

spec:   
 channel: v5   
 installPlanApproval: Automatic   
 name: crunchy-postgres-operator   
 source: "{{ postgres\_source }}"   
 sourceNamespace: "{{ postgres\_source\_namespace }}"  
 

but they are not defined for the uninstall task

they are set in the install task.

**Comment by andrercm** [comment]
@durera fixed the UDS uninstall issue in this PR: https://github.com/ibm-mas/ansible-devops/pull/888
