### ISSUE TITLE
Enhance Install Visual Inspection Application Playbook documentation for AWS and Azure

### ISSUE THREAD

**Issue by maulik-modi22** [ibm-mas/ansible-devops#883]
NFS Storage class variable MUST be set for playbook to succeed

For Azure,
`export MAS_APP_SETTINGS_VISUALINSPECTION_STORAGE_CLASS=azurefiles-premium
`

For AWS,
`export MAS_APP_SETTINGS_VISUALINSPECTION_STORAGE_CLASS=efs`

**Comment by andrercm** [comment]
@maulik-modi22 proposed fix is to include the following statement in https://github.com/ibm-mas/ansible-devops/blob/master/docs/playbooks/oneclick-visualinspection.md

```
## Optional environment variables
- `MAS_APP_SETTINGS_VISUALINSPECTION_STORAGE_CLASS` Defines a custom file storage class for Visual Inspection application. If none provided, then a default storage class will be auto defined accordingly to your cluster's availability i.e `ibmc-file-gold` for IBM Cloud or `azurefiles-premium` for Azure clusters.
```

**Comment by andrercm** [comment]
I confirmed that there is code in place to ensure a defaulted storage class is set in case it's not manually exported by user, and a message it thrown if no default storage class is found in the cluster in this case, so no actual code change needed, just improvement in the doc as you suggested.

**Comment by andrercm** [comment]
Fixed by the PR https://github.com/ibm-mas/ansible-devops/pull/966
