### ISSUE TITLE
AMQ Streams licensing issues

### ISSUE THREAD

**Issue by witekwww** [ibm-mas/ansible-devops#896]
Kafka is required by Monitor and ansible role kafka installs Kafka Cluster using Red Hat AMQ Streams. Are AMQ Streams licenses included in MAS entilements? or do we end up with a situation that installation using MAS Devops Collection results in a deployment which is not covered by MAS licenses ?

**Comment by andrercm** [comment]
The MAS license does not include entitlement for AMQ Streams. The MAS Devops Collection supports this Kafka deployment as an example only. We are working on enhancements to our Devops collection to provide support for other choices of Kafka (it already provides IBM Cloud Event Streams as option)

**Comment by witekwww** [comment]
Thank You for information. It may be helpful to include that information in the Kafka role docs ?

**Comment by andrercm** [comment]
Absolutely, I'll include a statement about it in kafka readme docs.

**Comment by andrercm** [comment]
Fixed by the PR https://github.com/ibm-mas/ansible-devops/pull/966
