### ISSUE TITLE
make mas_app_cfg_delay configurable for Manage/Health

### ISSUE THREAD

**Issue by caolan-ibm** [ibm-mas/ansible-devops#923]
Hi,

Can we use two new envs to make the mas_app_cfg_delay and configurable, currently it is hardcoded for different applications like: https://github.com/ibm-mas/ansible-devops/blob/6d12197a14f1fac98144446ff444233e5b243f9c/ibm/mas_devops/roles/suite_app_config/vars/health.yml

**Comment by andrercm** [comment]
I guess we could make these two vars capable of receiving a value from a var and keep a different suggested defaulted value for each app as in:
```
mas_app_cfg_retries: "{{ lookup('env', 'MAS_APP_CFG_RETRIES') | default(50, true)}}"
mas_app_cfg_delay: "{{ lookup('env', 'MAS_APP_CFG_DELAY') | default(480, true)}}"
```
So if these vars are not set, then it will use the default values same as it happens today, although it you do export these values and is installing more than one application in a single run, then likely they would share the variable values.

@alequint @durera any thoughts about the proposed enhancement?

**Comment by andrercm** [comment]
Fixed by the PR https://github.com/ibm-mas/ansible-devops/pull/966
