### ISSUE TITLE
Documentation: include the characteristics of the storage class in the role

### ISSUE THREAD

**Issue by mattlrx** [ibm-mas/ansible-devops#924]
in the ansible documentation, for some of the roles, when a storage class needs to be defined, it is specified whether it needs to be RWX:
https://ibm-mas.github.io/ansible-devops/roles/suite_app_install/#mas_app_settings_visualinspection_storage_class
https://ibm-mas.github.io/ansible-devops/roles/db2/#db2_meta_storage_class

for others it is not, for example:

https://ibm-mas.github.io/ansible-devops/roles/uds/
https://ibm-mas.github.io/ansible-devops/roles/kafka/#kafka_storage_class
https://ibm-mas.github.io/ansible-devops/roles/suite_app_install/#mas_app_settings_iot_fpl_pvc_storage_class
https://ibm-mas.github.io/ansible-devops/roles/registry/#registry_storage_class
https://ibm-mas.github.io/ansible-devops/roles/mongodb/#mongodb_storage_class
https://ibm-mas.github.io/ansible-devops/roles/suite_app_config/#mas_app_settings_jms_queue_pvc_storage_class
(not all listed)

it would be useful if the documentation could specify for ALL storage class variables what characteristics for the storage class are required, whether it needs to support block or filesystem and RWX or RWO, this would help in choosing the right storage class available on the cluster where MAS is installed.

**Comment by durera** [comment]
https://jsw.ibm.com/browse/MASCORE-4346

**Comment by istrate** [comment]
PR opened to address the request.
