### ISSUE TITLE
MAS Health install with MAS_APP_SETTINGS_PERSISTENT_VOLUMES_FLAG did not set the correct storage class

### ISSUE THREAD

**Issue by caolan-ibm** [ibm-mas/ansible-devops#925]
When install Health using the following ENVs

```
MAS_APP_SETTINGS_PERSISTENT_VOLUMES_FLAG=true
MAS_APP_ID=health
MAS_APPWS_COMPONENTS=health=latest
```

Health maxinst pod failed to start due to PVC can not be created, which was caused by the following missing storageClassName for PVCs.

![image](https://github.com/ibm-mas/ansible-devops/assets/58936064/9a573d74-cab9-41d5-adfa-aa32eba00587)

**Comment by andrercm** [comment]
Hi @ely-barros thanks for the feedback, I'll investigate this issue and get back to you.

**Comment by andrercm** [comment]
Fixed in this pull request: https://github.com/ibm-mas/ansible-devops/pull/945
