### ISSUE TITLE
suite_app_upgrade role fails with missing required values: spec.name, spec.source, spec.sourceNamespace

### ISSUE THREAD

**Issue by ely-barros** [ibm-mas/ansible-devops#926]
The [_Update subscription_](https://github.com/ibm-mas/ansible-devops/blob/d01a5f7afb9b86cc0e274d0462ed764dd7bf5b61/ibm/mas_devops/roles/suite_app_upgrade/tasks/upgrade.yml#L5-L14) task in _roles/suite_app_upgrade/tasks/upgrade.yml_ does not contain some required values so it fails with:

> TASK [ibm.mas_devops.suite_app_upgrade : Update subscription] ******************
> fatal: [cluster]: FAILED! => {"changed": false, "error": 422, "msg": "Subscription ibm-mas-manage: Failed to apply object: b'{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"Subscription.operators.coreos.com \\\\\"ibm-mas-manage\\\\\" is invalid: [spec.name: Required value, spec.source: Required value, spec.sourceNamespace: Required value]\",\"reason\":\"Invalid\",\"details\":{\"name\":\"ibm-mas-manage\",\"group\":\"operators.coreos.com\",\"kind\":\"Subscription\",\"causes\":[{\"reason\":\"FieldValueRequired\",\"message\":\"Required value\",\"field\":\"spec.name\"},{\"reason\":\"FieldValueRequired\",\"message\":\"Required value\",\"field\":\"spec.source\"},{\"reason\":\"FieldValueRequired\",\"message\":\"Required value\",\"field\":\"spec.sourceNamespace\"}]},\"code\":422}\\n'", "reason": "Unprocessable Entity", "status": 422}

**Comment by andrercm** [comment]
hi @ely-barros as our chat in slack, i believe this might have something to due with the subscription not being found to update and instead trying to create a new subscription. Let me know if you can consistently reproduce this in another environment so that we can check what's the subscription name it's trying to patch/update, you can run this command to check the existing subscription:
```
oc get sub -n mas-{{ mas_instance_id }}-manage
```

Maybe we can add a check in the code that ensures the subscription exists prior trying to update it... i think that can be a safe guard if my assumption is right.

**Comment by andrercm** [comment]
Added the check to ensure the sub exists prior updating it:
```
TASK [ibm.mas_devops.suite_app_upgrade : manage : Get subscription for ibm-mas-manage] ***********************************************************************************************************************************************************************
ok: [localhost]

TASK [ibm.mas_devops.suite_app_upgrade : manage : Execute Channel Upgrade] ***********************************************************************************************************************************************************************************
included: /Users/andremarcelino/.ansible/collections/ansible_collections/ibm/mas_devops/roles/suite_app_upgrade/tasks/upgrade.yml for localhost

TASK [ibm.mas_devops.suite_app_upgrade : Lookup subscription] ************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [ibm.mas_devops.suite_app_upgrade : Assert subscription exists] *****************************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [ibm.mas_devops.suite_app_upgrade : Update subscription] ************************************************************************************************************************************************************************************************
changed: [localhost]
```

**Comment by andrercm** [comment]
Fixed in this pull request: https://github.com/ibm-mas/ansible-devops/pull/945
