### ISSUE TITLE
Mongo CA and server certificate contain identical distinguished name

### ISSUE THREAD

**Issue by terenceq** [ibm-mas/ansible-devops#94]
This is in respect to the self-signed CA and server certificate for use with the Mongo CE operator. 

The problem really seems to be with the Common Name (CN) being the same/identical. This causes a problem with Pymongo and hostname validation. The CN for the CA should probably just be something like `Mongo CA`. 

A separate conf file should be created for use when creating the CA. One that contains the different CN and the extensions used when creating it.

**Comment by durera** [comment]
Fixed 👍
