### ISSUE TITLE
oneclick_add_predict playbook generates but does not apply WSL config

### ISSUE THREAD

**Issue by aeisma** [ibm-mas/ansible-devops#944]
In an environment where CP4D had already been installed (successfully) using `ROLE_NAME=cp4d ansible-playbook ibm.mas_devops.run_role`, a later addition of Predict fails to activate due to the generated WatsonStudioCfg not being applied.

We are using the following Predict settings for the installation:
```
export CPD_INSTALL_PLATFORM="false" # At this point CPD is already installed
export CPD_INSTALL_WSL="true"
export CPD_INSTALL_WML="true"
export WML_INSTANCE_ID="openshift"
export WML_URL="https://internal-nginx-svc.ibm-cpd.svc:12443"
export PREDICT_DEPLOYMENT_SIZE="small"

ansible-playbook ibm.mas_devops.oneclick_add_predict
```

The `${MAS_INSTANCE_ID}-watsonstudio-system.yml` did get generated in the config directory by the playbook.
After manually applying the generated config Predict activation progressed and completed successfully.

**Comment by andrercm** [comment]
Hello, can you share the output logs of the playbook run?
If you choose to install WSL, the playbook should take care of generating and applying the Watson Studio configuration for you as defined here: https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/playbooks/oneclick_add_predict.yml#L95

**Comment by aeisma** [comment]
Hi Andre,
Regretfully we lost the log output, the remote session got terminated before we could save the output.
I did notice the following:

1. The gencfg-wsl task in the cpd_service role generates the wsl config file.
2. The roles gencfg_watsonstudio and ibm.mas_devops.suite_config in the oneclick_add_predict playbook get skipped, due to the `when: install_watson_studio == false` clause.

**Comment by andrercm** [comment]
@aeisma yeah it makes sense now, i believe we should remove that condition that skips `ibm.mas_devops.suite_config`, this should run in both cases of when wsl is installed as part of the playbook and even if it's not and just the wsl config yaml is generated... I'll fix that.

**Comment by andrercm** [comment]
Fixed in this pull request: https://github.com/ibm-mas/ansible-devops/pull/945
