### ISSUE TITLE
amqstreams.v2.4.0-2 - Back-off pulling image "registry.redhat.io/amq-streams/kafka-34-rhel8

### ISSUE THREAD

**Issue by aeisma** [ibm-mas/ansible-devops#948]
This morning the AMQ Streams operator as deployed by MAS automatically upgraded to amqstreams.v2.4.0-2, and now the maskafka-entity-operator Deployment fails with Back-off pulling image "registry.redhat.io/amq-streams/kafka-34-rhel8@sha256:83ffd193a211354adb72a80a827f5e43e462dba4a8a12d8a626684841981ff8a".

Is this a problem in the RH update of this operator, or do we need to do something to fix up the deployment?

**Comment by whitfiea** [comment]
@aeisma We are not seeing an issue with pulling that image with that digest tag. Is this an airgap environment you are seeing this issue in?

**Comment by aeisma** [comment]
Hi Andrew, this morning I found the pod running again in all clusters, after >100 restarts.
Apparently RH fixed the issue with the missing image (or image tag).

**Comment by whitfiea** [comment]
@aeisma thanks for the feedback. I will close this issue as it was resolved by RedHat
