### ISSUE TITLE
mas cli v6.3.1 error in workspace display name

### ISSUE THREAD

**Issue by mudspringhiker** [ibm-mas/ansible-devops#952]
We are hitting an error in "MAS Workscpace Display Name", "Workspace name (<>) does not meet requirements." Fatal error[1] See /opt/app-root/.......".

![Screenshot 2023-08-11 at 10 14 42 AM](https://github.com/ibm-mas/ansible-devops/assets/17956412/bb699bd9-d0e7-4774-ba80-da4a8c183533)

We resorted to using v6.3.0 and did not get the error.

**Comment by mudspringhiker** [comment]
Should be on https://github.com/ibm-mas/cli/issues

**Comment by durera** [comment]
Fixed in 6.3.2 FYI ... the use of non-POSIX regex in the pattern was the problem here ... the regex was behaving differently on different OS ... in this case it worked fine on ubuntu, less so on rhel (which is what the CLI container image used).
