### ISSUE TITLE
Multiple Roles are publishing secrets to StdOut

### ISSUE THREAD

**Issue by kumareshsun** [ibm-mas/ansible-devops#955]
Hello,

I noticed there are so many secrets published directly to the stdout, which is not very useful for someone who runs these playbooks via the CI.

For example:-
https://github.com/ibm-mas/ansible-devops/blob/fe851249f72e9f2d9627def731219dcc101092c4/ibm/mas_devops/roles/install_operator/tasks/main.yml#L23C1-L24C1

Based on my observation, the following roles are currently doing this(there could be more)

- install_operator
- ibm.mas_devops.mongodb
- ibm.mas_devops.sls
- ibm.mas_devops.uds
- ibm.mas_devops.suite_install
- ibm.mas_devops.suite_app_install

**Solution:**
Provide a var with a boolean to mask/hide these secrets from the CI and the debug should only print if the var is absent/or present.

**Comment by kumareshsun** [comment]
Thanks @andrercm  can you please check across other roles that reveals the secrets as well?

**Comment by andrercm** [comment]
yeah i added also `no_log: true` in few places other places I spot that are exposing credentials in the debug logs.

**Comment by andrercm** [comment]
Fixed by the PR https://github.com/ibm-mas/ansible-devops/pull/966
