### ISSUE TITLE
Introduce logic to restart the pod only if the provider was changed

### ISSUE THREAD

**Issue by kumareshsun** [ibm-mas/ansible-devops#956]
Currently, this role restarts the pod and causes an outage on manage even though the DB2 has already been updated with the attachments provider during the initial run.

Keeping this role in a CI and running the playbook repeatedly causes an outage to the manage due to the Task behaviour. A Task with a check needs to be introduced to validate the current attachments provider and restart only if this changes.

https://github.com/ibm-mas/ansible-devops/blob/fe851249f72e9f2d9627def731219dcc101092c4/ibm/mas_devops/roles/suite_manage_attachments_config/tasks/main.yml#L146C1-L147C1

**Comment by andrercm** [comment]
@kumareshsun thanks for your feedback, we'll triage this and include a fix in the upcoming ansible collection releases.

**Comment by andrercm** [comment]
This is fixed with the linked pull request.
