### ISSUE TITLE
Add the vars for crypto/cryptox keys for Manage

### ISSUE THREAD

**Issue by aroute** [ibm-mas/ansible-devops#960]
Please add the variables so we can set the crypto/cryptox keys when installing Manage via masdevops. Something like `MAS_APP_SETTINGS_MANAGE_CRYPTOKEY` and `MAS_APP_SETTINGS_MANAGE_CRYPTOX` when the auto-generation of the keys is not desirable.  The relevant documentation is [here](https://www.ibm.com/docs/en/mas-cd/continuous-delivery?topic=encryption-adding-key-secrets) for the manual method.

This will help perform a successful first run backup/restore (from source to the destination instance) of the Manage database. At the moment, the setting of these key/value pair is only possible via the UI.

**Comment by andrercm** [comment]
For reference: https://www.ibm.com/docs/en/mas-cd/continuous-delivery?topic=encryption-database-scenarios

**Comment by andrercm** [comment]
Implemented with the associated PR:

https://github.com/ibm-mas/ansible-devops/pull/972
https://github.com/ibm-mas/cli/pull/439
