### ISSUE TITLE
Issue with deploying DB2

### ISSUE THREAD

**Issue by nerdingitout** [ibm-mas/ansible-devops#964]
I tried using DB2 role and I have come across the following issue:
- DB2 cluster CRDs aren't created in the db2u namespace. The DB2Cluster component and some certificates are created but nothing else happens, the deployment doesn't continue.
The issue might be related to the permissions for db2u project applied from the operator installed in ibm-common-services

The way I solved it is by manually installing it on the db2u namespace, that's why I believe it might be a permission issue.

**Comment by andrercm** [comment]
Hey @nerdingitout can you provide the exported variables you used while installing db2 using the automation? 
Also the output of the logs while running the ansible role which shows the error you've experienced will help on trying to assess what happened. 
Also, did you have `IBM Common Services / Foundation Services` installed prior trying to install DB2?

**Comment by nerdingitout** [comment]
Hi @andrercm

Yes, Foundational services and other operators in the ```ibm-common-services``` project were installed successfully before installing DB2.
Before installing DB2 and other operators, I manually enabled IBM Operator Catalog and didn't use the ```ibm.mas_devops.ibm_catalogs``` role because I faced issues installing common services on the cluster (I can create another issue for this to provide more details)

For the variables I have provided:
```
    db2_instance_name: db2u
    db2_meta_storage_class: "ocs-storagecluster-cephfs"
    db2_data_storage_class: "ocs-storagecluster-ceph-rbd"
    db2_backup_storage_class: "ocs-storagecluster-cephfs"
    db2_logs_storage_class: "ocs-storagecluster-ceph-rbd"
    db2_temp_storage_class: "ocs-storagecluster-ceph-rbd"
    db2_version: "s11.5.8.0"
    db2_channel: "v110508.0"
```

As for output, I barely saw anything running. DB2uCluster resource was created but wouldn't complete the installation. the DB2uCluster was deployed in db2u project, while the DB2u operator was automatically deployed in the ```ibm-common-services``` operator.

**Comment by neilpatt** [comment]
i am seeing a similar problem but the entrypoint is via the cli. I am using the 6.4.2 version of the cli

**Comment by neilpatt** [comment]
i am seeing a similar problem while installing from the cli (version 6.4.2) db2u namespace gets created, along with the cr for the db2ucluster - but the status in the cr looks as though the operator has not picked up the cr
![Screenshot 2023-08-18 at 13 51 09](https://github.com/ibm-mas/ansible-devops/assets/19327092/5cbe9490-cbe9-4a66-b8c0-25db07ab5cdf)

**Comment by andrercm** [comment]
Can you run this to check the current status of the db2 instance deployment? Please provide the output for the following commands:

**1. Check if persistent volumes for the db2 instance are all in bound state:**
```
oc get pvc -n db2u
```

**2. Check if db2 pods are in running state:**
```
oc get pods -n db2u
```

**3. Finally we can check if the db2 formation status (that should show the status of each step during the db2 instantiation):**

First check the db2 formations available (you might have one system db2 or another specifically for manage, as example:
```
oc get formations.db2u.databases.ibm.com -n db2u

NAME                           AGE
mas-devops-fixes-main-manage   23h
mas-devops-fixes-system        23h
```

Then you can check the status of each of then using:
```
oc get formations.db2u.databases.ibm.com mas-devops-fixes-main-manage -n db2u -o yaml
oc get formations.db2u.databases.ibm.com mas-devops-fixes-system -n db2u -o yaml
```

**Comment by nerdingitout** [comment]
@andrercm I re-attempted to install db2 after I forced reinstall of the ansible collection and it seemed to have solved the issue, all resources are created and in ready state. Currently running the latest version 16.0.1

@neilpatt Can you confirm whether the issue got resolved for your cluster?

Thanks!

**Comment by neilpatt** [comment]
I still have the same problem

**Comment by andrercm** [comment]
@neilpatt would you please provide the following output:

1. Check if persistent volumes for the db2 instance are all in bound state:
```
oc get pvc -n db2u
```

2. Check if db2 pods are in running state:
```
oc get pods -n db2u
```

3. Finally we can check if the db2 formation status (that should show the status of each step during the db2 instantiation):

First check the db2 formations available (you might have one system db2 or another specifically for manage, as example:

```
oc get formations.db2u.databases.ibm.com -n db2u

NAME                           AGE
mas-devops-fixes-main-manage   23h
mas-devops-fixes-system        23h
```

Then you can check the status of each of then using:

```
oc get formations.db2u.databases.ibm.com mas-devops-fixes-main-manage -n db2u -o yaml
oc get formations.db2u.databases.ibm.com mas-devops-fixes-system -n db2u -o yaml
```

Also check the current db2 license added to your environment:
```
oc get secrets db2u-license-keys -n ibm-common-services -o yaml
```

**Comment by neilpatt** [comment]
i have no access to the cluster any more

**Comment by andrercm** [comment]
Fixed with the merged pull request.
