### ISSUE TITLE
Multi Roles still publish secrets to stdout

### ISSUE THREAD

**Issue by kumareshsun** [ibm-mas/ansible-devops#973]
Hi @andrercm 

Tested the latest version of the collection following the Merge of https://github.com/ibm-mas/ansible-devops/issues/955 to the main branch.
I noticed the stdout still contains secrets for some tasks, but it looks like a good improvement from where it was before!

Let me list the ones that I'm working on:-

**TASK [ibm.mas_devops.mongodb : community : install : Create MAS MongoCfg (debug)]**
This task displays the Username and password details of Mongo Admin Configuration

**TASK [ibm.mas_devops.install_operator : Debug Entitlement Secret Creation]**

This task displays the entitlement password.

**Comment by andrercm** [comment]
Fixed with the associated PR https://github.com/ibm-mas/ansible-devops/pull/972
