### ISSUE TITLE
Grafana is installed with anonymous access set as default 

### ISSUE THREAD

**Issue by andrercm** [ibm-mas/ansible-devops#978]
This is the location - https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/cluster_monitoring/templates/grafana.yml.j2

Action:
The default Grafana option for authentication option of Grafana should not allow anonymous access.
Reference: https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/grafana/

Additional discussion in Slack - https://ibm-watson-iot.slack.com/archives/C040TETRV2T/p1692116049456159

**Comment by stonepd** [comment]
fixed in https://github.com/ibm-mas/ansible-devops/pull/1188

**Comment by durera** [comment]
Closing issue, this is now resolved
