### ISSUE TITLE
airgap image pull error with icpd-requisite after august catalog update

### ISSUE THREAD

**Issue by terenceq** [ibm-mas/ansible-devops#989]
## The ibm-zen operator in the ibm-cpd namespace cannot become ready

After the update for the august patches there seems to be an issue with mirroring the required images for CP4D 4.6.4. Specifically the following image in the `ibm-cpd` namespace cannot be pulled:

```
      image: >-
        icr.io/cpopen/cpfs/icpd-requisite@sha256:b570ce8ca62b38aff9e91c01dbeba54c2364ab97544290d245b0a4c20c225c33
```

## Possible solutions

1. [Configure CP4D 4.6.4](https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/cp4d/templates/config_maps/olm-utils-cm-4.6.4.yml.j2#L61) to use the following:

```yaml
  zen:
    csv_version: 1.8.5
    cr_version: 4.8.5
```

2. [Mirror two versions](https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/common_vars/casebundles/v8-230829-amd64.yml#L14C1-L14C32) of ibm-cp-common-services` to obtain the necessary images for the older ibm-zen operator

```yaml
common_svcs_version: 1.19.2
common_svcs_version: 1.19.4
```

## Watson Discovery Mirroring Issue

There also seems to be an issue with mirroring content used by Watson Discovery. This seems to be because of the new curated content snapshot in the IBM Maximo Operator Catalog v230829. 

Corrections should be made to the images that are mirrored and needed by Watson Discovery when using v230829 of the IBM Maximo Operator Catalog.

**Comment by andrercm** [comment]
@terenceq  seems we had a merge couple months ago... can we close this issue?
