### ISSUE TITLE
oneclick_core failed to install on fyre for task ibm.mas_devops.mongodb : Load CASE bundle versions

### ISSUE THREAD

**Issue by caolan-ibm** [ibm-mas/ansible-devops#992]
Here are the errors:

```
TASK [ibm.mas_devops.mongodb : Load CASE bundle versions] **********************
fatal: [localhost]: FAILED! => {"ansible_facts": {}, "ansible_included_var_files": [], "changed": false, "message": "Could not find or access '/home/travis/.ansible/collections/ansible_collections/ibm/mas_devops/roles/mongodb/../../common_vars/casebundles/v8-master-amd64.yml' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
NO MORE HOSTS LEFT *************************************************************
PLAY RECAP *********************************************************************
localhost                  : ok=53   changed=7    unreachable=0    failed=1    skipped=8    rescued=0    ignored=0   
The command "ansible-playbook ibm.mas_devops.oneclick_core" exited with 2.
```

Also referenced in https://github.com/ibm-mas/ansible-devops/issues/1001

**Comment by andrercm** [comment]
@racree i think you were looking into that?

**Comment by alicenahas** [comment]
Hello @andrercm @racree, I'm having the same problem, same error, but with a different file:

`TASK [ibm.mas_devops.mongodb : Load CASE bundle versions] **********************
fatal: [localhost]: FAILED! => {"ansible_facts": {}, "ansible_included_var_files": [], "changed": false, "message": "Could not find or access '/root/.ansible/collections/ansible_collections/ibm/mas_devops/roles/mongodb/../../common_vars/casebundles/v8-manage-amd64.yml' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}`

Should I open a new issue for that?

**Comment by creyesibm** [comment]
@andrercm I am having the exact same issue as Alice, is there a workaround for it?  Just for the record, I tried to use v8-230829-amd.yml which exists in the directory but then my CatalogSource/ibm-operator-catalog had a TRANSIENT_FAILURE
![image](https://github.com/ibm-mas/ansible-devops/assets/129990814/966f4dfa-2e55-4c49-b437-04165121fbe9)

**Comment by creyesibm** [comment]
@alicenahas It seems I got around it by creating a soft link. Basically:
cd /root/.ansible/collections/ansible_collections/ibm/mas_devops/roles/mongodb/../../common_vars/casebundles
ln -s  v8-230829-amd.yml v8-manage-amd64.yml
then try the one-click.core again

**Comment by andrercm** [comment]
@racree @durera was there any fix in for this? there are multiple people reporting this problem.

**Comment by karol-czarnecki** [comment]
Hi I would like to correct little bit  @creyesibm workaround: 

```
cd /root/.ansible/collections/ansible_collections/ibm/mas_devops/roles/mongodb/../../common_vars/casebundles/
ln -s v8-230829-amd64.yml v8-master-amd64.yml 
```

**Comment by whitfiea** [comment]
Fixed in https://github.com/ibm-mas/ansible-devops/pull/1011
