### ISSUE TITLE
onclick_manange: Add attachments and BIM roles to the Manage oneclick playbook 

### ISSUE THREAD

**Issue by lokesh-sreedhara** [ibm-mas/ansible-devops#993]
Requesting to add the following roles to Manage oneclick playbook by default. 

ROLE_NAME='suite_manage_attachments_config'
ROLE_NAME='suite_manage_bim_config'

Seems these configurations are needs on Manange add-on by default. when appID=manage please make these roles run as part of onclick_manange playbook

**Comment by andrercm** [comment]
@lokesh-sreedhara do we want to enable these features by default while running `manage_oneclick.yml` playbook? Or we want them to be configure with the playbook but disable them by default?

**Comment by lokesh-sreedhara** [comment]
@andrercm this was something Scott Boudreau had request for IVT. not quite sure if it should be default for Customer. i did ping him about it. but haven't heard back

**Comment by andrercm** [comment]
This is fixed with the linked pull request.
